// Code generator: emits Rust source code from a Gust AST.
//
// Each `machine` becomes:
//   - A state enum with serde derives
//   - A machine struct holding the current state
//   - An impl block with transition methods (type-checked)
//   - Transition methods that enforce valid from-state at runtime
//     (compile-time via enum matching / exhaustiveness)
//   - Effect traits (if machine declares effects)

use crate::ast::*;
use crate::codegen_common::{
    collect_referenced_idents, detect_ctx_param, escape_string_literal, handler_used_channels,
    handler_uses_perform, handler_uses_spawn, to_snake_case,
};
use std::collections::HashSet;

/// Rust code generator. Consumes a validated [`Program`] and emits
/// idiomatic `.g.rs` source targeting the `gust_runtime` crate.
pub struct RustCodegen {
    output: String,
    indent: usize,
    ctx_param: Option<String>,
    from_state_fields: Vec<String>,
    /// Names of user enums whose variants are all payload-free. These derive
    /// `Copy`, so destructured fields of that type must be dereferenced rather
    /// than cloned — `.clone()` on a Copy type trips clippy::clone_on_copy.
    copy_types: HashSet<String>,
    /// Identifiers the handler currently being emitted actually reads, so an
    /// unread `let` can be lowered to `let _` rather than tripping
    /// `unused_variables` in consumers building with `-D warnings`.
    referenced_idents: HashSet<String>,
    /// Hoisted source-state locals that are **not** `Copy`, so `spawn` knows
    /// which arguments it must clone. Moving one into a child machine would
    /// otherwise leave the rest of the handler using a moved value — `spawn
    /// Worker(cfg); goto Running(cfg);` is ordinary Gust and must compile.
    /// Copy locals are excluded so the output does not trip
    /// `clippy::clone_on_copy`.
    clonable_locals: HashSet<String>,
    current_effects: Vec<EffectDecl>,
    tracing: bool,
}

impl RustCodegen {
    /// Construct a new Rust code generator with tracing disabled.
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            ctx_param: None,
            from_state_fields: Vec::new(),
            copy_types: HashSet::new(),
            referenced_idents: HashSet::new(),
            clonable_locals: HashSet::new(),
            current_effects: Vec::new(),
            tracing: false,
        }
    }

    /// Enable tracing instrumentation in generated code.
    ///
    /// When enabled, the generated Rust code will include `#[cfg(feature = "tracing")]`-guarded
    /// span creation and event emission for state transitions and effect invocations.
    /// The user's crate must add `tracing` as an optional dependency and declare a `"tracing"`
    /// feature flag for these hooks to compile in.
    pub fn with_tracing(mut self, enabled: bool) -> Self {
        self.tracing = enabled;
        self
    }

    /// Generate the full `.g.rs` source for `program`.
    pub fn generate(mut self, program: &Program) -> String {
        self.emit_prelude(program);

        self.copy_types = program
            .types
            .iter()
            .filter_map(|decl| match decl {
                TypeDecl::Enum { name, variants, .. }
                    if variants.iter().all(|v| v.payload.is_empty()) =>
                {
                    Some(name.clone())
                }
                _ => None,
            })
            .collect();

        for channel in &program.channels {
            self.emit_channel_decl(channel);
            self.newline();
        }

        // Emit type declarations as Rust structs
        for type_decl in &program.types {
            self.emit_type_decl(type_decl);
            self.newline();
        }

        // Emit each machine
        for machine in &program.machines {
            self.emit_machine(machine, &program.channels);
            self.newline();
        }

        self.finish()
    }

    fn finish(mut self) -> String {
        while self.output.ends_with("\n\n") {
            self.output.pop();
        }
        self.output
    }

    fn emit_prelude(&mut self, program: &Program) {
        self.line("// Generated by Gust compiler — do not edit manually");
        self.line("use serde::{Serialize, Deserialize};");
        // No `use gust_runtime::prelude::*;`.
        //
        // Nothing emitted here depended on it: the two runtime items generated
        // code actually references — `SupervisorRuntime` and `RestartStrategy`,
        // both only for supervision — are written fully qualified, and
        // `thiserror::Error` and `serde` are qualified or imported directly.
        // The glob was therefore inert, but it forced *every* consumer to
        // depend on `gust-runtime`, which pulls `tokio` with `features =
        // ["full"]`. A plain synchronous machine went from a 17-entry
        // dependency tree to 45 for an import it never used.
        //
        // With it gone, `gust-runtime` is needed only by machines that
        // supervise. Channels and timeouts reference `tokio` directly and need
        // that crate, not this one.
        // No `use tokio;` here even for channels and timeouts: every emitted
        // reference is fully qualified (`tokio::time::timeout`,
        // `tokio::sync::broadcast::Sender`), so the import is redundant and
        // trips clippy::single_component_path_imports — a hard error for any
        // consumer building with `-D warnings`, in a file they are told never
        // to edit. See the `timeout` and `channel` fixtures in
        // tests/codegen_backends.rs.
        if self.tracing {
            self.line("#[cfg(feature = \"tracing\")]");
            self.line("use tracing;");
        }
        for use_path in &program.uses {
            if use_path.segments.is_empty() {
                continue;
            }
            // `std::*` is a Gust-virtual namespace for stdlib machines/types
            // (see `gust-stdlib`). The consumer's build pipeline is
            // responsible for compiling the stdlib source and placing it in
            // the same module as the dependent machine, so no Rust `use`
            // statement is emitted. See issue #66.
            if use_path.segments.first().map(String::as_str) == Some("std") {
                continue;
            }
            self.line(&format!("use {};", use_path.segments.join("::")));
        }
        self.newline();
    }

    fn emit_channel_decl(&mut self, channel: &ChannelDecl) {
        let name = &channel.name;
        let message_type = self.type_expr_to_rust(&channel.message_type);
        let channel_struct = format!("{name}Channel");
        let capacity = channel.capacity.unwrap_or(1024).max(1);

        match channel.mode {
            ChannelMode::Broadcast => {
                self.line("#[derive(Clone)]");
                self.line(&format!("pub struct {channel_struct} {{"));
                self.indent += 1;
                self.line(&format!(
                    "sender: tokio::sync::broadcast::Sender<{message_type}>,"
                ));
                self.indent -= 1;
                self.line("}");
                self.line(&format!("impl {channel_struct} {{"));
                self.indent += 1;
                self.line("pub fn new() -> Self {");
                self.indent += 1;
                self.line(&format!(
                    "let (sender, _) = tokio::sync::broadcast::channel({capacity}usize);"
                ));
                self.line("Self { sender }");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "pub fn sender(&self) -> tokio::sync::broadcast::Sender<{message_type}> {{"
                ));
                self.indent += 1;
                self.line("self.sender.clone()");
                self.indent -= 1;
                self.line("}");
                self.line(&format!("pub fn send(&self, msg: {message_type}) {{"));
                self.indent += 1;
                self.line("let _ = self.sender.send(msg);");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "pub fn subscribe(&self) -> tokio::sync::broadcast::Receiver<{message_type}> {{"
                ));
                self.indent += 1;
                self.line("self.sender.subscribe()");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.emit_channel_default(&channel_struct);
            }
            ChannelMode::Mpsc => {
                self.line(&format!("pub struct {channel_struct} {{"));
                self.indent += 1;
                self.line(&format!(
                    "sender: tokio::sync::mpsc::Sender<{message_type}>,"
                ));
                self.line(&format!(
                    "receiver: tokio::sync::Mutex<tokio::sync::mpsc::Receiver<{message_type}>>,"
                ));
                self.indent -= 1;
                self.line("}");
                self.line(&format!("impl {channel_struct} {{"));
                self.indent += 1;
                self.line("pub fn new() -> Self {");
                self.indent += 1;
                self.line(&format!(
                    "let (sender, receiver) = tokio::sync::mpsc::channel({capacity}usize);"
                ));
                self.line("Self { sender, receiver: tokio::sync::Mutex::new(receiver) }");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "pub fn sender(&self) -> tokio::sync::mpsc::Sender<{message_type}> {{"
                ));
                self.indent += 1;
                self.line("self.sender.clone()");
                self.indent -= 1;
                self.line("}");
                self.line(&format!("pub fn try_send(&self, msg: {message_type}) {{"));
                self.indent += 1;
                self.line("let _ = self.sender.try_send(msg);");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "pub async fn receive(&self) -> Option<{message_type}> {{"
                ));
                self.indent += 1;
                self.line("self.receiver.lock().await.recv().await");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.emit_channel_default(&channel_struct);
            }
        }
    }

    /// A nullary `new()` without a matching `Default` trips
    /// `clippy::new_without_default`, which fails any consumer building with
    /// `-D warnings` — in a file they are told never to edit. A channel's
    /// capacity and mode come from the declaration, so the default is exactly
    /// what `new()` builds. Mirrors the same treatment machines already get.
    fn emit_channel_default(&mut self, channel_struct: &str) {
        self.line(&format!("impl Default for {channel_struct} {{"));
        self.indent += 1;
        self.line("fn default() -> Self {");
        self.indent += 1;
        self.line("Self::new()");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    // === Type Declarations ===

    fn emit_type_decl(&mut self, decl: &TypeDecl) {
        match decl {
            TypeDecl::Struct { name, fields, .. } => {
                self.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
                self.line(&format!("pub struct {name} {{"));
                self.indent += 1;
                for field in fields {
                    self.line(&format!(
                        "pub {}: {},",
                        field.name,
                        self.type_expr_to_rust(&field.ty)
                    ));
                }
                self.indent -= 1;
                self.line("}");
            }
            TypeDecl::Enum { name, variants, .. } => {
                // A fieldless enum is a plain tag, and callers routinely read it
                // out of a struct field (`let b = req.bucket;`) and then keep
                // using the struct. Without Copy that is a partial move and the
                // generated code does not compile.
                let all_variants_fieldless = variants.iter().all(|v| v.payload.is_empty());
                if all_variants_fieldless {
                    self.line("#[derive(Debug, Clone, Copy, Serialize, Deserialize)]");
                } else {
                    self.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
                }
                self.line(&format!("pub enum {name} {{"));
                self.indent += 1;
                for variant in variants {
                    if variant.payload.is_empty() {
                        self.line(&format!("{},", variant.name));
                    } else {
                        let payload = variant
                            .payload
                            .iter()
                            .map(|t| self.type_expr_to_rust(t))
                            .collect::<Vec<_>>()
                            .join(", ");
                        self.line(&format!("{}({payload}),", variant.name));
                    }
                }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    // === Machine ===

    fn emit_machine(&mut self, machine: &MachineDecl, channels: &[ChannelDecl]) {
        let name = &machine.name;
        let state_enum = format!("{name}State");
        let generic_decl = rust_generic_decl(&machine.generic_params);
        let generic_use = rust_generic_use(&machine.generic_params);

        // State enum
        self.emit_state_enum(name, &machine.states, &generic_decl);
        self.newline();

        // Effect trait (if machine has effects)
        if !machine.effects.is_empty() {
            self.emit_effect_trait(machine, &generic_decl);
            self.newline();
        }

        // Supervision contract (if this machine supervises children)
        if !machine.supervises.is_empty() {
            self.emit_supervision(machine, &generic_decl);
            self.newline();
        }

        // Machine struct
        self.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
        self.line(&format!("pub struct {name}{generic_decl} {{"));
        self.indent += 1;
        self.line(&format!("pub state: {state_enum}{generic_use},"));
        self.indent -= 1;
        self.line("}");
        self.newline();

        // Transition error type
        self.line(&format!(
            r#"#[derive(Debug, Clone, thiserror::Error)]
pub enum {name}Error {{
    #[error("invalid transition '{{transition}}' from state '{{from}}'")]
    InvalidTransition {{ transition: String, from: String }},
    #[error("transition failed: {{reason}}")]
    Failed {{ reason: String }},
}}"#
        ));
        self.newline();

        // Impl block with transitions.
        //
        // The extra `Debug` bound is on the impl, not the type: the invalid-
        // transition arm formats `self.state` with `{:?}`, and the state enum's
        // derived `Debug` only applies when every type parameter is `Debug`.
        // Without it a generic machine's own methods do not compile. Bounding
        // the impl rather than the struct keeps the bound off `Serialize` /
        // `Deserialize` and off non-generic machines, whose output is unchanged.
        let impl_decl = rust_generic_decl_with_debug(&machine.generic_params);
        self.line(&format!("impl{impl_decl} {name}{generic_use} {{"));
        self.indent += 1;

        // Constructor
        if let Some(first_state) = machine.states.first() {
            self.emit_constructor(name, &state_enum, first_state);
            self.newline();
        }

        // Current state helper
        self.line(&format!(
            "pub fn state(&self) -> &{state_enum}{generic_use} {{"
        ));
        self.indent += 1;
        self.line("&self.state");
        self.indent -= 1;
        self.line("}");
        self.newline();

        // Channel send helpers. These belong inside the impl: they take `&self`,
        // the Go backend emits the same helpers as methods on the machine, and
        // `send_{channel}` is not machine-qualified — as free functions two
        // machines declaring `sends` on the same channel would collide.
        self.emit_channel_helpers(machine, channels);

        // Transition methods
        self.current_effects = machine.effects.clone();
        for transition in &machine.transitions {
            self.emit_transition_method(
                name,
                &state_enum,
                transition,
                &machine.handlers,
                &machine.states,
                &machine.effects,
                channels,
                &generic_use,
            );
            self.newline();
        }
        self.current_effects.clear();

        self.indent -= 1;
        self.line("}");

        // A nullary `new()` without a matching `Default` trips
        // clippy::new_without_default, which fails any consumer building with
        // -D warnings. Machines whose initial state carries fields have no
        // meaningful default, so they are left alone.
        let initial_state_is_fieldless = machine
            .states
            .first()
            .is_some_and(|state| state.fields.is_empty());
        if initial_state_is_fieldless {
            self.newline();
            // `Self::new()` lives in the `Debug`-bounded impl above, so this one
            // needs the same bound to be able to call it.
            self.line(&format!(
                "impl{impl_decl} Default for {name}{generic_use} {{"
            ));
            self.indent += 1;
            self.line("fn default() -> Self {");
            self.indent += 1;
            self.line("Self::new()");
            self.indent -= 1;
            self.line("}");
            self.indent -= 1;
            self.line("}");
        }
    }

    /// Emits the supervision contract for a machine with a `supervises` clause:
    /// a `{Machine}Supervision` trait with one runner per child, and a strategy
    /// table naming each child and its restart policy.
    ///
    /// Gust constructs children — `spawn Worker(cfg)` builds a real `Worker` —
    /// but a machine is passive: its transitions are driven from outside, so
    /// there is no generated loop to hand the supervisor. The host supplies one
    /// per child, exactly as it supplies effects. That keeps the split Gust
    /// already uses (Gust owns the contract, the host owns behaviour) and
    /// matches the Go backend, which has emitted a `SupervisionSpec` table and
    /// a `SupervisorRuntime` interface all along.
    ///
    /// Before this, `supervises` emitted nothing at all in Rust and `spawn`
    /// emitted a future that discarded its arguments and returned `Ok(())`.
    fn emit_supervision(&mut self, machine: &MachineDecl, generic_decl: &str) {
        let name = &machine.name;
        let trait_name = format!("{name}Supervision");

        self.line(&format!(
            "/// Host-supplied runners for the children `{name}` supervises."
        ));
        self.line(&format!("pub trait {trait_name}{generic_decl} {{"));
        self.indent += 1;
        for spec in &machine.supervises {
            let child = &spec.child_machine;
            let runner = format!("run_{}", to_snake_case(child));
            self.line(&format!(
                "/// Drives a supervised `{child}` to completion. Returning `Err`",
            ));
            self.line("/// marks the child failed, which is what the runtime's");
            self.line("/// restart strategy acts on.");
            self.line(&format!(
                // A boxed future rather than RPITIT, deliberately.
                // `SupervisorRuntime::spawn_named` needs `Future + Send +
                // 'static`, and an `impl Future` return on a `&self` method
                // captures that borrow on every edition — so no implementor
                // could ever satisfy `'static` (`E0477`). `Pin<Box<dyn Future
                // + Send>>` carries an implicit `'static`, works on edition
                // 2021 output, and costs one allocation per spawned child.
                "fn {runner}(&self, child: {child}) -> ::core::pin::Pin<::std::boxed::Box<dyn ::core::future::Future<Output = Result<(), String>> + Send>>;"
            ));
        }
        self.indent -= 1;
        self.line("}");
        self.newline();

        // Strategy table. The runtime owns restart semantics
        // (`SupervisorRuntime::restart_scope`); this states which policy applies
        // to which child so a host can drive it without re-parsing the `.gu`.
        self.line(&format!(
            "/// Restart policy per supervised child of `{name}`."
        ));
        self.line(&format!(
            "pub const {}_SUPERVISION: &[(&str, gust_runtime::prelude::RestartStrategy)] = &[",
            to_snake_case(name).to_uppercase()
        ));
        self.indent += 1;
        for spec in &machine.supervises {
            self.line(&format!(
                "(\"{}\", gust_runtime::prelude::RestartStrategy::{}),",
                spec.child_machine,
                match spec.strategy {
                    SupervisionStrategy::OneForOne => "OneForOne",
                    SupervisionStrategy::OneForAll => "OneForAll",
                    SupervisionStrategy::RestForOne => "RestForOne",
                }
            ));
        }
        self.indent -= 1;
        self.line("];");
    }

    fn emit_state_enum(&mut self, machine_name: &str, states: &[StateDecl], generic_decl: &str) {
        let enum_name = format!("{machine_name}State");
        self.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
        self.line(&format!("pub enum {enum_name}{generic_decl} {{"));
        self.indent += 1;
        for state in states {
            if state.fields.is_empty() {
                self.line(&format!("{},", state.name));
            } else {
                self.line(&format!("{} {{", state.name));
                self.indent += 1;
                for field in &state.fields {
                    self.line(&format!(
                        "{}: {},",
                        field.name,
                        self.type_expr_to_rust(&field.ty)
                    ));
                }
                self.indent -= 1;
                self.line("},");
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_effect_trait(&mut self, machine: &MachineDecl, generic_decl: &str) {
        let trait_name = format!("{}Effects", machine.name);
        self.line(&format!("pub trait {trait_name}{generic_decl} {{"));
        self.indent += 1;

        for effect in &machine.effects {
            let params: Vec<String> = effect
                .params
                .iter()
                .map(|p| {
                    if is_copy_type(&p.ty) {
                        format!("{}: {}", p.name, self.type_expr_to_rust(&p.ty))
                    } else {
                        format!("{}: &{}", p.name, self.type_expr_to_rust_ref(&p.ty))
                    }
                })
                .collect();
            let return_type = self.type_expr_to_rust(&effect.return_type);
            let all_params = if params.is_empty() {
                "&self".to_string()
            } else {
                format!("&self, {}", params.join(", "))
            };
            let returns_unit = matches!(effect.return_type, TypeExpr::Unit);
            // `async fn` in a public trait trips the `async_fn_in_trait` lint,
            // because the trait alone does not promise the future is Send and
            // callers holding the machine across an await need that. Desugaring
            // to RPITIT states the bound explicitly. Implementors can still
            // write a plain `async fn`. RPITIT captures all in-scope lifetimes
            // on every edition, so no `+ '_` is needed here.
            let ret_annotation = if effect.is_async {
                let output = if returns_unit {
                    "()".to_string()
                } else {
                    return_type.clone()
                };
                format!(" -> impl ::core::future::Future<Output = {output}> + Send")
            } else if returns_unit {
                String::new()
            } else {
                format!(" -> {return_type}")
            };
            // Keep the annotation directly above the method so downstream
            // tooling can parse generated Rust without reading .gu source.
            self.line(&format!(
                "/// gust:{} -- {}",
                effect.kind.keyword(),
                effect.kind.annotation_description()
            ));
            self.line(&format!(
                "fn {}({}){};",
                effect.name, all_params, ret_annotation
            ));
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_constructor(&mut self, _machine_name: &str, state_enum: &str, first_state: &StateDecl) {
        if first_state.fields.is_empty() {
            self.line("pub fn new() -> Self {");
            self.indent += 1;
            self.line(&format!(
                "Self {{ state: {state_enum}::{} }}",
                first_state.name
            ));
            self.indent -= 1;
            self.line("}");
        } else {
            // Constructor takes initial state fields as params
            let params: Vec<String> = first_state
                .fields
                .iter()
                .map(|f| format!("{}: {}", f.name, self.type_expr_to_rust(&f.ty)))
                .collect();
            self.line(&format!("pub fn new({}) -> Self {{", params.join(", ")));
            self.indent += 1;
            let field_names: Vec<&str> =
                first_state.fields.iter().map(|f| f.name.as_str()).collect();
            self.line(&format!(
                "Self {{ state: {state_enum}::{} {{ {} }} }}",
                first_state.name,
                field_names.join(", ")
            ));
            self.indent -= 1;
            self.line("}");
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_transition_method(
        &mut self,
        machine_name: &str,
        state_enum: &str,
        transition: &TransitionDecl,
        handlers: &[OnHandler],
        states: &[StateDecl],
        effects: &[EffectDecl],
        channels: &[ChannelDecl],
        generic_use: &str,
    ) {
        let error_type = format!("{machine_name}Error");

        // Find matching handler for this transition
        let handler = handlers
            .iter()
            .find(|h| h.transition_name == transition.name);

        let ctx_param_name = handler.and_then(detect_ctx_param);

        // Collect handler params, filtering out the ctx param
        let extra_params = handler
            .map(|h| {
                h.params
                    .iter()
                    .filter(|p| ctx_param_name.as_ref() != Some(&p.name))
                    .filter_map(|p| {
                        let ty = p.ty.as_ref()?;
                        Some(format!("{}: {}", p.name, self.type_expr_to_rust(ty)))
                    })
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();

        // Add effects parameter only if this handler uses perform
        let uses_effects = handler
            .map(|h| handler_uses_perform(&h.body))
            .unwrap_or(false);
        let uses_spawn = handler
            .map(|h| handler_uses_spawn(&h.body))
            .unwrap_or(false);
        let used_channels = handler
            .map(|h| handler_used_channels(&h.body))
            .unwrap_or_default();
        let mut params = vec!["&mut self".to_string()];
        if !extra_params.is_empty() {
            params.push(extra_params);
        }
        if uses_effects && !effects.is_empty() {
            params.push(format!(
                "effects: &impl {}Effects{}",
                machine_name, generic_use
            ));
        }
        if uses_spawn {
            params.push("supervisor: &gust_runtime::prelude::SupervisorRuntime".to_string());
            // Spawning needs the host's child runner as well as the runtime.
            // Gust constructs the child machine — it owns that contract — but
            // a machine is passive: transitions are called from outside, so
            // there is no generated "run" loop to hand the supervisor. The
            // host supplies one through `{Machine}Supervision`, the same shape
            // as the effects trait.
            params.push(format!(
                "children: &impl {}Supervision{}",
                machine_name, generic_use
            ));
        }
        for channel_name in used_channels {
            if let Some(channel) = channels.iter().find(|c| c.name == channel_name) {
                let ty = self.type_expr_to_rust(&channel.message_type);
                let param = match channel.mode {
                    ChannelMode::Broadcast => format!(
                        "{}_tx: &tokio::sync::broadcast::Sender<{ty}>",
                        to_snake_case(&channel.name)
                    ),
                    ChannelMode::Mpsc => format!(
                        "{}_tx: &tokio::sync::mpsc::Sender<{ty}>",
                        to_snake_case(&channel.name)
                    ),
                };
                params.push(param);
            }
        }
        let params_str = params.join(", ");

        self.line(&format!(
            "pub {}fn {}({params_str}) -> Result<(), {error_type}> {{",
            if handler.map(|h| h.is_async).unwrap_or(false) || transition.timeout.is_some() {
                "async "
            } else {
                ""
            },
            transition.name
        ));
        self.indent += 1;

        // Match on current state — only allow transition from the declared `from` state.
        //
        // Borrowed, not cloned: cloning the whole state up front deep-copied
        // every field of every state (including Vec/String payloads) on every
        // call, and did so before the from-state check, so even a rejected
        // transition paid for it. Fields the handler actually uses are cloned
        // individually at arm entry instead.
        self.line("match &self.state {");
        self.indent += 1;

        // Look up the from-state to see if it has fields
        let from_state = states.iter().find(|s| s.name == transition.from);

        // Collect idents referenced by the handler body to prefix unused fields with _
        let referenced_idents = handler
            .map(|h| collect_referenced_idents(&h.body, ctx_param_name.as_deref()))
            .unwrap_or_default();
        self.referenced_idents = referenced_idents.clone();

        // Valid from-state arm with destructuring
        if let Some(state) = from_state {
            if state.fields.is_empty() {
                self.line(&format!("{state_enum}::{} => {{", transition.from));
            } else {
                let field_names: Vec<String> = state
                    .fields
                    .iter()
                    .map(|f| {
                        if referenced_idents.contains(&f.name) {
                            f.name.clone()
                        } else {
                            // Use `field: _field` so the pattern matches the actual field name
                            // while suppressing the unused-variable warning on the binding.
                            format!("{}: _{}", f.name, f.name)
                        }
                    })
                    .collect();
                self.line(&format!(
                    "{state_enum}::{} {{ {} }} => {{",
                    transition.from,
                    field_names.join(", ")
                ));
            }
        } else {
            // Fallback if state not found (shouldn't happen in valid AST)
            self.line(&format!("{state_enum}::{} => {{", transition.from));
        }

        self.indent += 1;

        // Take owned copies of the fields the handler actually uses. The arm
        // binds references (the match scrutinee is `&self.state`), but handler
        // bodies move fields into the target state, and the borrow has to end
        // before `self.state` is reassigned. Copy fields are dereferenced
        // rather than cloned so the output does not trip clippy::clone_on_copy.
        self.clonable_locals.clear();
        if let Some(state) = from_state {
            for field in &state.fields {
                if !referenced_idents.contains(&field.name) {
                    continue;
                }
                let name = &field.name;
                if self.is_copy_in_generated(&field.ty) {
                    self.line(&format!("let {name} = *{name};"));
                } else {
                    self.line(&format!("let {name} = {name}.clone();"));
                    self.clonable_locals.insert(name.clone());
                }
            }
        }

        // Emit tracing instrumentation for state transitions
        if self.tracing {
            let targets_str = transition.targets.join(" | ");
            self.line("#[cfg(feature = \"tracing\")]");
            self.line(&format!(
                "let __tracing_span = tracing::info_span!(\"{}\", machine = \"{}\", from = \"{}\", to = \"{}\");",
                transition.name, machine_name, transition.from, targets_str
            ));
            self.line("#[cfg(feature = \"tracing\")]");
            self.line("let __tracing_guard = __tracing_span.enter();");
            self.line("#[cfg(feature = \"tracing\")]");
            self.line(&format!(
                "tracing::info!(machine = \"{}\", transition = \"{}\", from = \"{}\", to = \"{}\", \"state transition\");",
                machine_name, transition.name, transition.from, targets_str
            ));
        }

        // Set ctx rewriting state for handler body emission
        if let Some(ref ctx_name) = ctx_param_name {
            self.ctx_param = Some(ctx_name.clone());
            if let Some(state) = from_state {
                self.from_state_fields = state.fields.iter().map(|f| f.name.clone()).collect();
            }
        }

        // Emit handler body if present
        if let Some(handler) = handler {
            if let Some(timeout) = transition.timeout {
                self.line("let __transition_result = tokio::time::timeout(");
                self.indent += 1;
                self.line(&format!("{},", self.duration_to_rust(timeout)));
                self.line("async {");
                self.indent += 1;
                // The async block needs its own trailing value, but only when a
                // path can reach it. A `goto` returns from this block, so a
                // body that always gotos would make the value below an
                // `unreachable_expression` — a hard error under `-D warnings`.
                self.emit_block(&handler.body, state_enum, states, effects, channels, true);
                if !block_always_diverges(&handler.body) {
                    self.line(&format!("Ok::<(), {error_type}>(())"));
                }
                self.indent -= 1;
                self.line("},");
                self.indent -= 1;
                self.line(").await;");
                self.line("match __transition_result {");
                self.indent += 1;
                self.line("Ok(Ok(())) => {},");
                self.line("Ok(Err(err)) => return Err(err),");
                self.line("Err(_) => {");
                self.indent += 1;
                self.line(&format!("return Err({error_type}::Failed {{"));
                self.indent += 1;
                self.line(&format!(
                    "reason: format!(\"transition '{}' timed out after {{:?}}\", {}),",
                    transition.name,
                    self.duration_to_rust(timeout)
                ));
                self.indent -= 1;
                self.line("});");
                self.indent -= 1;
                self.line("},");
                self.indent -= 1;
                self.line("}");
            } else {
                self.emit_block(&handler.body, state_enum, states, effects, channels, true);
            }
        } else {
            // Default: transition to first target if no handler
            if let Some(first_target) = transition.targets.first() {
                // Look up target state to see if it needs field initialization
                let target_state = states.iter().find(|s| &s.name == first_target);
                if let Some(target) = target_state {
                    if target.fields.is_empty() {
                        self.line(&format!("self.state = {state_enum}::{first_target};"));
                    } else {
                        // Can't auto-initialize fields without arguments
                        self.line(&format!(
                            "// Cannot auto-transition to {first_target} - requires fields"
                        ));
                    }
                }
            }
        }

        // Clear ctx rewriting state
        self.ctx_param = None;
        self.from_state_fields.clear();

        // Only when some path can actually reach it — every `goto` now returns,
        // so a handler that always gotos would make this unreachable.
        // A `timeout` transition wraps the body and always needs it.
        let needs_trailing_ok = transition.timeout.is_some()
            || handler
                .map(|h| !block_always_diverges(&h.body))
                .unwrap_or(true);
        if needs_trailing_ok {
            self.line("Ok(())");
        }
        self.indent -= 1;
        self.line("}");

        // All other states — invalid transition
        self.line(&format!("_ => Err({error_type}::InvalidTransition {{",));
        self.indent += 1;
        self.line(&format!("transition: \"{}\".to_string(),", transition.name));
        self.line("from: format!(\"{:?}\", self.state),");
        self.indent -= 1;
        self.line("}),");

        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
    }

    // === Statement & Expression Codegen ===

    /// `tail` is true when this block's final statement sits in the tail
    /// position of the transition method, so a `goto` there can be the
    /// function's trailing expression instead of an explicit `return` —
    /// otherwise the output trips `clippy::needless_return`.
    fn emit_block(
        &mut self,
        block: &Block,
        state_enum: &str,
        states: &[StateDecl],
        effects: &[EffectDecl],
        channels: &[ChannelDecl],
        tail: bool,
    ) {
        let last = block.statements.len().saturating_sub(1);
        for (i, stmt) in block.statements.iter().enumerate() {
            self.emit_statement(
                stmt,
                state_enum,
                states,
                effects,
                channels,
                tail && i == last,
            );
        }
    }

    fn emit_statement(
        &mut self,
        stmt: &Statement,
        state_enum: &str,
        states: &[StateDecl],
        effects: &[EffectDecl],
        channels: &[ChannelDecl],
        tail: bool,
    ) {
        let async_effects: HashSet<&str> = effects
            .iter()
            .filter(|e| e.is_async)
            .map(|e| e.name.as_str())
            .collect();
        match stmt {
            Statement::Let {
                name, ty, value, ..
            } => {
                // Emit tracing event for perform expressions used as let values
                if self.tracing {
                    if let Expr::Perform(effect_name, _, _) = value {
                        self.line("#[cfg(feature = \"tracing\")]");
                        self.line(&format!(
                            "tracing::info!(effect = \"{effect_name}\", \"effect invocation\");",
                        ));
                    }
                }
                // A binding the handler never reads becomes `let _`, which
                // still runs the initializer but does not trip
                // `unused_variables` in a consumer building with -D warnings.
                // The validator warns the author separately; codegen's job is
                // to emit code that compiles cleanly regardless.
                let binding = if self.referenced_idents.contains(name) {
                    name.as_str()
                } else {
                    "_"
                };
                if let Some(type_expr) = ty {
                    self.line(&format!(
                        "let {}: {} = {};",
                        binding,
                        self.type_expr_to_rust(type_expr),
                        self.expr_to_rust(value, &async_effects)
                    ));
                } else {
                    self.line(&format!(
                        "let {} = {};",
                        binding,
                        self.expr_to_rust(value, &async_effects)
                    ));
                }
            }
            Statement::Return(expr) => {
                self.line(&format!(
                    "return {};",
                    self.expr_to_rust(expr, &async_effects)
                ));
            }
            Statement::If {
                condition,
                then_block,
                else_block,
                span: _,
            } => {
                let cond = self.expr_to_rust(condition, &async_effects);
                let cond = if cond.starts_with('(') && cond.ends_with(')') {
                    &cond[1..cond.len() - 1]
                } else {
                    &cond
                };
                self.line(&format!("if {cond} {{"));
                self.indent += 1;
                self.emit_block(
                    then_block,
                    state_enum,
                    states,
                    effects,
                    channels,
                    tail && else_block.is_some(),
                );
                self.indent -= 1;
                if let Some(else_blk) = else_block {
                    self.line("} else {");
                    self.indent += 1;
                    self.emit_block(else_blk, state_enum, states, effects, channels, tail);
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::Goto { state, args, .. } => {
                // Look up target state to determine if it has fields
                let target_state = states.iter().find(|s| &s.name == state);
                if let Some(target) = target_state {
                    if target.fields.is_empty() {
                        self.line(&format!("self.state = {state_enum}::{state};"));
                    } else {
                        // Hoist every non-trivial argument into a temporary
                        // before building the literal.
                        //
                        // Struct fields evaluate in written order, so
                        // `goto Compensating(completed, perform len(completed) - 1, err)`
                        // moved `completed` into the first field and then
                        // borrowed it for the second — `E0382`, which is what
                        // kept `saga.gu` from compiling. Evaluating the
                        // borrowing arguments first and leaving bare
                        // identifiers to be moved at construction time fixes
                        // it without an extra clone. The Go backend has always
                        // hoisted these; Rust did not.
                        let mut hoisted: Vec<Option<String>> = Vec::new();
                        for (field, arg) in target.fields.iter().zip(args.iter()) {
                            let value = self.expr_to_rust(arg, &async_effects);
                            // Judged on the rendered form: `ctx.items` is a
                            // FieldAccess that ctx rewriting turns into the
                            // bare local `items`. Hoisting that would move it
                            // before a later argument could borrow it — the
                            // very thing this hoisting exists to prevent.
                            let is_plain_local = !value.is_empty()
                                && value.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
                                && !value.chars().next().unwrap().is_ascii_digit();
                            if is_plain_local {
                                hoisted.push(None);
                                continue;
                            }
                            let tmp = format!(
                                "__goto_{}_{}",
                                to_snake_case(state),
                                to_snake_case(&field.name)
                            );
                            self.line(&format!("let {tmp} = {value};"));
                            hoisted.push(Some(tmp));
                        }

                        // Map args to fields in order
                        let field_inits: Vec<String> = target
                            .fields
                            .iter()
                            .zip(args.iter())
                            .enumerate()
                            .map(|(i, (field, arg))| {
                                let value = match &hoisted[i] {
                                    Some(tmp) => tmp.clone(),
                                    None => self.expr_to_rust(arg, &async_effects),
                                };
                                // `Foo { bar: bar }` trips clippy::redundant_field_names,
                                // which fails any consumer building with -D warnings.
                                if value == field.name {
                                    value
                                } else {
                                    format!("{}: {}", field.name, value)
                                }
                            })
                            .collect();
                        self.line(&format!(
                            "self.state = {state_enum}::{state} {{ {} }};",
                            field_inits.join(", ")
                        ));
                    }
                } else {
                    // Fallback if state not found
                    self.line(&format!("self.state = {state_enum}::{state};"));
                }
                // `goto` ends the handler. Without this it emitted a bare
                // assignment and execution continued, so an early `goto` inside
                // a bare `if` fell through: the machine ended in whichever state
                // the *last* assignment named, and any value moved into the
                // abandoned state left the rest of the handler using a moved
                // value (`E0382`). `gust check` reported nothing. `saga.gu`
                // depends on this idiom and did not compile as Rust because of
                // it.
                if tail {
                    self.line("Ok(())");
                } else {
                    self.line("return Ok(());");
                }
            }
            Statement::Perform { effect, args, .. } => {
                if self.tracing {
                    self.line("#[cfg(feature = \"tracing\")]");
                    self.line(&format!(
                        "tracing::info!(effect = \"{effect}\", \"effect invocation\");",
                    ));
                }
                let effect_decl = effects.iter().find(|e| e.name == *effect);
                let arg_strs: Vec<String> = args
                    .iter()
                    .enumerate()
                    .map(|(i, a)| {
                        let is_copy = effect_decl
                            .and_then(|e| e.params.get(i))
                            .map(|p| is_copy_type(&p.ty))
                            .unwrap_or(false);
                        if is_copy {
                            self.expr_to_rust(a, &async_effects)
                        } else {
                            format!("&{}", self.expr_to_rust(a, &async_effects))
                        }
                    })
                    .collect();
                if async_effects.contains(effect.as_str()) {
                    self.line(&format!(
                        "effects.{}({}).await;",
                        effect,
                        arg_strs.join(", ")
                    ));
                } else {
                    self.line(&format!("effects.{}({});", effect, arg_strs.join(", ")));
                }
            }
            Statement::Send {
                channel, message, ..
            } => {
                let msg = self.expr_to_rust(message, &async_effects);
                let tx_name = format!("{}_tx", to_snake_case(channel));
                let mode = channels
                    .iter()
                    .find(|c| c.name == *channel)
                    .map(|c| c.mode)
                    .unwrap_or(ChannelMode::Broadcast);
                match mode {
                    ChannelMode::Broadcast => {
                        self.line(&format!("let _ = {tx_name}.send({msg});"));
                    }
                    ChannelMode::Mpsc => {
                        self.line(&format!("let _ = {tx_name}.try_send({msg});"));
                    }
                }
            }
            Statement::Spawn { machine, args, .. } => {
                // Construct the child machine and hand it to the host's runner.
                // This previously emitted `async move { let _ = (args); Ok(()) }`
                // — the arguments were discarded and no child was ever built,
                // so `spawn` compiled and did nothing.
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| {
                        let rendered = self.expr_to_rust(a, &async_effects);
                        // Clone a non-`Copy` source-state local rather than
                        // moving it into the child: the handler almost always
                        // still needs it for the following `goto`.
                        //
                        // Matched on the rendered name, not the AST node: a
                        // `ctx.foo` argument is a `FieldAccess` that only
                        // becomes the bare local `foo` after ctx rewriting.
                        if self.clonable_locals.contains(&rendered) {
                            format!("{rendered}.clone()")
                        } else {
                            rendered
                        }
                    })
                    .collect();
                let runner = format!("run_{}", to_snake_case(machine));
                self.line(&format!(
                    "let _child = supervisor.spawn_named(\"{}\", children.{}({}::new({})));",
                    machine,
                    runner,
                    machine,
                    arg_strs.join(", ")
                ));
            }
            Statement::Match { scrutinee, arms } => {
                self.line(&format!(
                    "match {} {{",
                    self.expr_to_rust(scrutinee, &async_effects)
                ));
                self.indent += 1;
                for arm in arms {
                    self.line(&format!("{} => {{", self.pattern_to_rust(&arm.pattern)));
                    self.indent += 1;
                    self.emit_block(&arm.body, state_enum, states, effects, channels, tail);
                    self.indent -= 1;
                    self.line("}");
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::Expr(expr) => {
                self.line(&format!("{};", self.expr_to_rust(expr, &async_effects)));
            }
        }
    }

    /// Whether a type is `Copy` in the generated output — primitives plus any
    /// user enum whose variants are all payload-free.
    fn is_copy_in_generated(&self, ty: &TypeExpr) -> bool {
        is_copy_type(ty) || matches!(ty, TypeExpr::Simple(name) if self.copy_types.contains(name))
    }

    /// Lower an operand of a binary comparison. When `borrow_literals` is set,
    /// a bare string literal stays a `&str` instead of being allocated into a
    /// `String` that the comparison would immediately discard.
    fn expr_to_rust_operand(
        &self,
        expr: &Expr,
        async_effects: &HashSet<&str>,
        borrow_literals: bool,
    ) -> String {
        match expr {
            Expr::StringLit(s) if borrow_literals => {
                format!("\"{}\"", escape_string_literal(s))
            }
            // Parenthesise a binary expression only where it is an operand of
            // another expression, so precedence survives nesting. Emitting the
            // parens unconditionally put them at statement level too —
            // `let next = (attempt + 1);` — which is `unnecessary_parens`, a
            // hard error for consumers building with `-D warnings`.
            Expr::BinOp(..) => format!("({})", self.expr_to_rust(expr, async_effects)),
            _ => self.expr_to_rust(expr, async_effects),
        }
    }

    fn expr_to_rust(&self, expr: &Expr, async_effects: &HashSet<&str>) -> String {
        match expr {
            Expr::IntLit(v) => format!("{v}"),
            Expr::FloatLit(v) => format!("{v}"),
            Expr::StringLit(s) => format!("\"{}\".to_string()", escape_string_literal(s)),
            Expr::BoolLit(b) => if *b { "true" } else { "false" }.to_string(),
            Expr::Ident(name) => name.clone(),
            Expr::FieldAccess(base, field) => {
                if let Expr::Ident(name) = base.as_ref() {
                    if self.ctx_param.as_deref() == Some(name.as_str()) {
                        // ctx.field → field (single-level rewrite)
                        return field.clone();
                    }
                }
                // Recurse into base — handles ctx.config.service_name
                // by first rewriting ctx.config → config, then emitting config.service_name
                let base_str = self.expr_to_rust(base, async_effects);
                format!("{base_str}.{field}")
            }
            Expr::FnCall(name, args) => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_rust(a, async_effects))
                    .collect();
                format!("{}({})", name, arg_strs.join(", "))
            }
            Expr::BinOp(left, op, right, _) => {
                // A string literal normally lowers to an owned `String`, but in
                // comparison position that allocates purely to throw the value
                // away, which is both wasteful and trips clippy::cmp_owned.
                // `String == &str` compares fine without the allocation.
                let borrow_literals = matches!(op, BinOp::Eq | BinOp::Neq);
                format!(
                    "{} {} {}",
                    self.expr_to_rust_operand(left, async_effects, borrow_literals),
                    self.binop_to_rust(op),
                    self.expr_to_rust_operand(right, async_effects, borrow_literals)
                )
            }
            Expr::UnaryOp(op, expr) => {
                // Operand position for the inner expression: `!(a && b)` needs
                // the parens, `!done` does not.
                format!(
                    "{}{}",
                    self.unaryop_to_rust(op),
                    self.expr_to_rust_operand(expr, async_effects, false)
                )
            }
            Expr::Perform(effect, args, _) => {
                let effect_decl = self.current_effects.iter().find(|e| e.name == *effect);
                let arg_strs: Vec<String> = args
                    .iter()
                    .enumerate()
                    .map(|(i, a)| {
                        let is_copy = effect_decl
                            .and_then(|e| e.params.get(i))
                            .map(|p| is_copy_type(&p.ty))
                            .unwrap_or(false);
                        if is_copy {
                            self.expr_to_rust(a, async_effects)
                        } else {
                            format!("&{}", self.expr_to_rust(a, async_effects))
                        }
                    })
                    .collect();
                if async_effects.contains(effect.as_str()) {
                    format!("effects.{}({}).await", effect, arg_strs.join(", "))
                } else {
                    format!("effects.{}({})", effect, arg_strs.join(", "))
                }
            }
            Expr::Path(enum_name, variant) => format!("{enum_name}::{variant}"),
        }
    }

    fn binop_to_rust(&self, op: &BinOp) -> &'static str {
        match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Mod => "%",
            BinOp::Eq => "==",
            BinOp::Neq => "!=",
            BinOp::Lt => "<",
            BinOp::Lte => "<=",
            BinOp::Gt => ">",
            BinOp::Gte => ">=",
            BinOp::And => "&&",
            BinOp::Or => "||",
        }
    }

    fn unaryop_to_rust(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
        }
    }

    // === Helpers ===

    fn type_expr_to_rust(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Unit => "()".to_string(),
            TypeExpr::Simple(name) => map_type_name(name),
            TypeExpr::Generic(name, args) => {
                let mapped = map_type_name(name);
                let arg_strs: Vec<String> =
                    args.iter().map(|a| self.type_expr_to_rust(a)).collect();
                format!("{mapped}<{}>", arg_strs.join(", "))
            }
            TypeExpr::Tuple(types) => {
                let members = types
                    .iter()
                    .map(|t| self.type_expr_to_rust(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({members})")
            }
        }
    }

    /// Like type_expr_to_rust but for use behind a reference (`&`).
    /// Maps `String` → `str` and `Vec<T>` → `[T]` for idiomatic Rust references.
    fn type_expr_to_rust_ref(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Unit => "()".to_string(),
            TypeExpr::Simple(name) if name == "String" => "str".to_string(),
            TypeExpr::Generic(name, args) if name == "Vec" => {
                let inner = args
                    .first()
                    .map(|a| self.type_expr_to_rust(a))
                    .unwrap_or_else(|| "_".to_string());
                format!("[{inner}]")
            }
            _ => self.type_expr_to_rust(ty),
        }
    }

    fn pattern_to_rust(&self, pattern: &Pattern) -> String {
        match pattern {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Ident(name) => name.clone(),
            Pattern::Variant {
                enum_name,
                variant,
                bindings,
            } => {
                let full = if let Some(name) = enum_name {
                    format!("{name}::{variant}")
                } else {
                    variant.clone()
                };
                if bindings.is_empty() {
                    full
                } else {
                    // Underscore-prefix a binding the handler never reads.
                    // `match result { Err(err) => { goto Degraded(status, 1); } }`
                    // binds `err` and ignores it, which is `unused_variables` —
                    // a hard error for the many consumers building with
                    // `-D warnings`, in a file they are told never to edit.
                    // Same `referenced_idents` set that lowers an unread `let`
                    // to `let _`; deliberately coarse in the same way, since a
                    // name read in any arm counts as read.
                    let rendered = bindings
                        .iter()
                        .map(|b| {
                            if b == "_" || self.referenced_idents.contains(b) {
                                b.clone()
                            } else {
                                format!("_{b}")
                            }
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{full}({rendered})")
                }
            }
        }
    }

    fn line(&mut self, text: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(text);
        self.output.push('\n');
    }

    fn newline(&mut self) {
        self.output.push('\n');
    }

    fn duration_to_rust(&self, duration: DurationSpec) -> String {
        match duration.unit {
            TimeUnit::Millis => format!("tokio::time::Duration::from_millis({})", duration.value),
            TimeUnit::Seconds => format!("tokio::time::Duration::from_secs({})", duration.value),
            TimeUnit::Minutes => {
                format!("tokio::time::Duration::from_secs({} * 60)", duration.value)
            }
            TimeUnit::Hours => format!(
                "tokio::time::Duration::from_secs({} * 60 * 60)",
                duration.value
            ),
        }
    }

    fn emit_channel_helpers(&mut self, machine: &MachineDecl, channels: &[ChannelDecl]) {
        for channel_name in &machine.sends {
            if let Some(channel) = channels.iter().find(|c| c.name == *channel_name) {
                let ty = self.type_expr_to_rust(&channel.message_type);
                let method = format!("send_{}", to_snake_case(channel_name));
                let tx_ty = match channel.mode {
                    ChannelMode::Broadcast => {
                        format!("tokio::sync::broadcast::Sender<{ty}>")
                    }
                    ChannelMode::Mpsc => {
                        format!("tokio::sync::mpsc::Sender<{ty}>")
                    }
                };
                self.line(&format!(
                    "pub fn {method}(&self, msg: {ty}, {}_tx: &{tx_ty}) {{",
                    to_snake_case(channel_name)
                ));
                self.indent += 1;
                match channel.mode {
                    ChannelMode::Broadcast => {
                        self.line(&format!(
                            "let _ = {}_tx.send(msg);",
                            to_snake_case(channel_name)
                        ));
                    }
                    ChannelMode::Mpsc => {
                        self.line(&format!(
                            "let _ = {}_tx.try_send(msg);",
                            to_snake_case(channel_name)
                        ));
                    }
                }
                self.indent -= 1;
                self.line("}");
                self.newline();
            }
        }
    }
}

impl Default for RustCodegen {
    fn default() -> Self {
        Self::new()
    }
}

/// Whether a type is Copy in Rust and should be passed by value, not reference.
/// Whether every path through `block` ends in a `goto` or `return`.
///
/// Now that `goto` emits `return Ok(());`, a handler whose every path gotos
/// makes the function's trailing `Ok(())` unreachable — `unreachable_code`,
/// which is a hard error for consumers building with `-D warnings`. So the
/// trailing expression is emitted only when some path can reach it.
///
/// Deliberately conservative: an `if` counts only with an `else` (a bare `if`
/// can fall through), and a `match` counts only if it has arms and all of them
/// diverge. Being wrong in this direction emits a reachable `Ok(())`, which is
/// harmless; the opposite would drop the return value a path needs.
fn block_always_diverges(block: &Block) -> bool {
    match block.statements.last() {
        Some(Statement::Goto { .. }) | Some(Statement::Return { .. }) => true,
        Some(Statement::If {
            then_block,
            else_block: Some(else_block),
            ..
        }) => block_always_diverges(then_block) && block_always_diverges(else_block),
        Some(Statement::Match { arms, .. }) => {
            !arms.is_empty() && arms.iter().all(|arm| block_always_diverges(&arm.body))
        }
        _ => false,
    }
}

fn is_copy_type(ty: &TypeExpr) -> bool {
    matches!(ty, TypeExpr::Unit)
        || matches!(ty, TypeExpr::Simple(name) if matches!(name.as_str(),
            "i64" | "i32" | "u64" | "u32" | "f64" | "f32" | "bool"
        ))
}

/// Map Gust type names to Rust type names.
/// Gust type names are identical to Rust type names, so this is a passthrough.
fn map_type_name(name: &str) -> String {
    name.to_string()
}

fn rust_generic_decl(params: &[GenericParam]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let joined = params
        .iter()
        .map(|p| {
            if p.bounds.is_empty() {
                p.name.clone()
            } else {
                format!("{}: {}", p.name, p.bounds.join(" + "))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("<{joined}>")
}

/// Like [`rust_generic_decl`] but with the bounds a transition impl needs on
/// every parameter: `core::fmt::Debug` and `Clone`.
///
/// `Debug` is for the invalid-transition arm, which formats the state with
/// `{:?}`. `Clone` is for the borrow strategy: reading a state field hoists
/// `let x = x.clone();` out of the `match &self.state` arm, and on a field
/// whose type is a bare type parameter that call resolves to `Clone for &T`
/// and yields `&T` — so the subsequent `goto` fails with `expected type
/// parameter T, found &T`. That is why five of six `gust-stdlib` machines did
/// not compile as Rust; only `retry` did, and only because it never reads a
/// generic-typed state field.
///
/// Both bounds go on the impl rather than the struct, which keeps them off
/// `Serialize`/`Deserialize` and leaves non-generic output byte-identical.
fn rust_generic_decl_with_debug(params: &[GenericParam]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let joined = params
        .iter()
        .map(|p| {
            let mut bounds = p.bounds.clone();
            if !bounds.iter().any(|b| b.ends_with("Debug")) {
                bounds.push("core::fmt::Debug".to_string());
            }
            if !bounds.iter().any(|b| b.ends_with("Clone")) {
                bounds.push("Clone".to_string());
            }
            format!("{}: {}", p.name, bounds.join(" + "))
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("<{joined}>")
}

fn rust_generic_use(params: &[GenericParam]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let joined = params
        .iter()
        .map(|p| p.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    format!("<{joined}>")
}
