/// Go Code Generator: emits Go source code from a Gust AST.
///
/// Each `machine` becomes:
///   - State constants via iota
///   - A state data struct per state variant (Go lacks sum types)
///   - An effects interface
///   - A machine struct with current state + state data
///   - Transition methods with runtime state validation
///
/// Key differences from Rust codegen:
///   - No sum types → use state enum (iota) + interface for state data
///   - No exhaustiveness checking → runtime panics on invalid transitions
///   - Effects trait → Go interface (more idiomatic)
///   - Serde → json struct tags (free with encoding/json)
///   - Error handling → Go error returns, no Result<T,E>

use crate::ast::*;

pub struct GoCodegen {
    output: String,
    indent: usize,
}

impl GoCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn generate(mut self, program: &Program, package_name: &str) -> String {
        self.emit_prelude(package_name);

        // Emit type declarations as Go structs
        for type_decl in &program.types {
            self.emit_type_decl(type_decl);
            self.newline();
        }

        // Emit each machine
        for machine in &program.machines {
            self.emit_machine(machine);
            self.newline();
        }

        self.output
    }

    fn emit_prelude(&mut self, package_name: &str) {
        self.line("// Code generated by Gust compiler — DO NOT EDIT.");
        self.newline();
        self.line(&format!("package {package_name}"));
        self.newline();
        self.line("import (");
        self.indent += 1;
        self.line("\"encoding/json\"");
        self.line("\"fmt\"");
        self.indent -= 1;
        self.line(")");
        self.newline();
        // Suppress unused import warnings
        self.line("var _ = json.Marshal");
        self.line("var _ = fmt.Errorf");
        self.newline();
    }

    // === Type Declarations ===

    fn emit_type_decl(&mut self, decl: &TypeDecl) {
        self.line(&format!("type {} struct {{", decl.name));
        self.indent += 1;
        for field in &decl.fields {
            let field_name = pascal_case(&field.name);
            let go_type = self.type_expr_to_go(&field.ty);
            let json_tag = &field.name;
            self.line(&format!(
                "{field_name} {go_type} `json:\"{json_tag}\"`"
            ));
        }
        self.indent -= 1;
        self.line("}");
    }

    // === Machine ===

    fn emit_machine(&mut self, machine: &MachineDecl) {
        let name = &machine.name;

        // --- State enum via iota ---
        self.emit_state_constants(name, &machine.states);
        self.newline();

        // --- State name helper ---
        self.emit_state_name_func(name, &machine.states);
        self.newline();

        // --- State data structs ---
        for state in &machine.states {
            if !state.fields.is_empty() {
                self.emit_state_data_struct(name, state);
                self.newline();
            }
        }

        // --- Effects interface ---
        if !machine.effects.is_empty() {
            self.emit_effects_interface(name, &machine.effects);
            self.newline();
        }

        // --- Machine struct ---
        self.emit_machine_struct(name, &machine.states);
        self.newline();

        // --- Constructor ---
        self.emit_constructor(name, &machine.states);
        self.newline();

        // --- Transition error ---
        self.emit_transition_error(name);
        self.newline();

        // --- Transition methods ---
        for transition in &machine.transitions {
            self.emit_transition_method(name, transition, &machine.handlers, &machine.states, &machine.effects);
            self.newline();
        }

        // --- JSON marshaling ---
        self.emit_json_helpers(name);
    }

    fn emit_state_constants(&mut self, machine_name: &str, states: &[StateDecl]) {
        let type_name = format!("{machine_name}State");
        self.line(&format!("type {type_name} int"));
        self.newline();
        self.line("const (");
        self.indent += 1;
        for (i, state) in states.iter().enumerate() {
            if i == 0 {
                self.line(&format!(
                    "{machine_name}State{} {type_name} = iota",
                    state.name
                ));
            } else {
                self.line(&format!("{machine_name}State{}", state.name));
            }
        }
        self.indent -= 1;
        self.line(")");
    }

    fn emit_state_name_func(&mut self, machine_name: &str, states: &[StateDecl]) {
        let type_name = format!("{machine_name}State");
        self.line(&format!("func (s {type_name}) String() string {{"));
        self.indent += 1;
        self.line("switch s {");
        for state in states {
            self.line(&format!(
                "case {machine_name}State{}:",
                state.name
            ));
            self.indent += 1;
            self.line(&format!("return \"{}\"", state.name));
            self.indent -= 1;
        }
        self.line("default:");
        self.indent += 1;
        self.line("return \"Unknown\"");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_state_data_struct(&mut self, machine_name: &str, state: &StateDecl) {
        let struct_name = format!("{machine_name}{}Data", state.name);
        self.line(&format!("type {struct_name} struct {{"));
        self.indent += 1;
        for field in &state.fields {
            let field_name = pascal_case(&field.name);
            let go_type = self.type_expr_to_go(&field.ty);
            let json_tag = &field.name;
            self.line(&format!(
                "{field_name} {go_type} `json:\"{json_tag}\"`"
            ));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_effects_interface(&mut self, machine_name: &str, effects: &[EffectDecl]) {
        self.line(&format!("type {machine_name}Effects interface {{"));
        self.indent += 1;
        for effect in effects {
            let method_name = pascal_case(&effect.name);
            let params: Vec<String> = effect
                .params
                .iter()
                .map(|p| format!("{} {}", p.name, self.type_expr_to_go(&p.ty)))
                .collect();
            let return_type = self.type_expr_to_go(&effect.return_type);
            self.line(&format!(
                "{}({}) {}",
                method_name,
                params.join(", "),
                return_type
            ));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_machine_struct(&mut self, machine_name: &str, states: &[StateDecl]) {
        let state_type = format!("{machine_name}State");
        self.line(&format!("type {machine_name} struct {{"));
        self.indent += 1;
        self.line(&format!("State {state_type} `json:\"state\"`"));
        // One optional data field per state that has data
        for state in states {
            if !state.fields.is_empty() {
                let data_type = format!("{machine_name}{}Data", state.name);
                let json_tag = format!("{}_data,omitempty", snake_case(&state.name));
                self.line(&format!(
                    "{}Data *{data_type} `json:\"{json_tag}\"`",
                    state.name
                ));
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_constructor(&mut self, machine_name: &str, states: &[StateDecl]) {
        let first = match states.first() {
            Some(s) => s,
            None => return,
        };

        if first.fields.is_empty() {
            self.line(&format!("func New{machine_name}() *{machine_name} {{"));
            self.indent += 1;
            self.line(&format!("return &{machine_name}{{"));
            self.indent += 1;
            self.line(&format!("State: {machine_name}State{},", first.name));
            self.indent -= 1;
            self.line("}");
            self.indent -= 1;
            self.line("}");
        } else {
            let params: Vec<String> = first
                .fields
                .iter()
                .map(|f| format!("{} {}", f.name, self.type_expr_to_go(&f.ty)))
                .collect();
            self.line(&format!(
                "func New{machine_name}({}) *{machine_name} {{",
                params.join(", ")
            ));
            self.indent += 1;
            self.line(&format!("return &{machine_name}{{"));
            self.indent += 1;
            self.line(&format!("State: {machine_name}State{},", first.name));
            let data_type = format!("{machine_name}{}Data", first.name);
            self.line(&format!("{}Data: &{data_type}{{", first.name));
            self.indent += 1;
            for field in &first.fields {
                self.line(&format!("{}: {},", pascal_case(&field.name), field.name));
            }
            self.indent -= 1;
            self.line("},");
            self.indent -= 1;
            self.line("}");
            self.indent -= 1;
            self.line("}");
        }
    }

    fn emit_transition_error(&mut self, machine_name: &str) {
        self.line(&format!("type {machine_name}Error struct {{"));
        self.indent += 1;
        self.line("Transition string");
        self.line("From      string");
        self.line("Message   string");
        self.indent -= 1;
        self.line("}");
        self.newline();
        self.line(&format!("func (e *{machine_name}Error) Error() string {{"));
        self.indent += 1;
        self.line("if e.Message != \"\" {");
        self.indent += 1;
        self.line("return fmt.Sprintf(\"transition '%s' failed: %s\", e.Transition, e.Message)");
        self.indent -= 1;
        self.line("}");
        self.line("return fmt.Sprintf(\"invalid transition '%s' from state '%s'\", e.Transition, e.From)");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_transition_method(
        &mut self,
        machine_name: &str,
        transition: &TransitionDecl,
        handlers: &[OnHandler],
        states: &[StateDecl],
        effects: &[EffectDecl],
    ) {
        let method_name = pascal_case(&transition.name);
        let handler = handlers.iter().find(|h| h.transition_name == transition.name);

        // Build parameter list
        let mut params = Vec::new();

        // Add handler params
        if let Some(h) = handler {
            for p in &h.params {
                params.push(format!("{} {}", p.name, self.type_expr_to_go(&p.ty)));
            }
        }

        // Add effects param if this handler uses perform
        let uses_effects = handler
            .map(|h| handler_uses_perform(&h.body))
            .unwrap_or(false);
        if uses_effects && !effects.is_empty() {
            params.push(format!("effects {machine_name}Effects"));
        }

        self.line(&format!(
            "func (m *{machine_name}) {method_name}({}) error {{",
            params.join(", ")
        ));
        self.indent += 1;

        // State check
        self.line(&format!(
            "if m.State != {machine_name}State{} {{",
            transition.from
        ));
        self.indent += 1;
        self.line(&format!(
            "return &{machine_name}Error{{Transition: \"{}\", From: m.State.String()}}",
            transition.name
        ));
        self.indent -= 1;
        self.line("}");
        self.newline();

        // Handler body or default transition
        if let Some(h) = handler {
            self.emit_block_go(&h.body, machine_name, states, effects);
        } else if let Some(first_target) = transition.targets.first() {
            self.emit_goto_go(machine_name, first_target, &[], states);
        }

        self.newline();
        self.line("return nil");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_block_go(
        &mut self,
        block: &Block,
        machine_name: &str,
        states: &[StateDecl],
        effects: &[EffectDecl],
    ) {
        for stmt in &block.statements {
            self.emit_statement_go(stmt, machine_name, states, effects);
        }
    }

    fn emit_statement_go(
        &mut self,
        stmt: &Statement,
        machine_name: &str,
        states: &[StateDecl],
        effects: &[EffectDecl],
    ) {
        match stmt {
            Statement::Let { name, ty, value } => {
                let expr = self.expr_to_go(value);
                if let Some(t) = ty {
                    let go_type = self.type_expr_to_go(t);
                    self.line(&format!("var {name} {go_type} = {expr}"));
                } else {
                    self.line(&format!("{name} := {expr}"));
                }
            }
            Statement::Return(expr) => {
                let val = self.expr_to_go(expr);
                self.line(&format!("return {val}"));
            }
            Statement::If {
                condition,
                then_block,
                else_block,
            } => {
                let cond = self.expr_to_go(condition);
                // Strip outer parens for Go if-conditions
                let cond = if cond.starts_with('(') && cond.ends_with(')') {
                    &cond[1..cond.len()-1]
                } else {
                    &cond
                };
                self.line(&format!("if {cond} {{"));
                self.indent += 1;
                self.emit_block_go(then_block, machine_name, states, effects);
                self.indent -= 1;
                if let Some(else_b) = else_block {
                    self.line("} else {");
                    self.indent += 1;
                    self.emit_block_go(else_b, machine_name, states, effects);
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::Goto { state, args } => {
                self.emit_goto_go(machine_name, state, args, states);
            }
            Statement::Perform { effect, args } => {
                let method = pascal_case(effect);
                let arg_strs: Vec<String> = args.iter().map(|a| self.expr_to_go(a)).collect();
                self.line(&format!("effects.{}({})", method, arg_strs.join(", ")));
            }
            Statement::Expr(expr) => {
                let val = self.expr_to_go(expr);
                self.line(&format!("{val}"));
            }
        }
    }

    fn emit_goto_go(
        &mut self,
        machine_name: &str,
        target_state: &str,
        args: &[Expr],
        states: &[StateDecl],
    ) {
        self.line(&format!("m.State = {machine_name}State{target_state}"));

        // Clear all state data pointers
        for state in states {
            if !state.fields.is_empty() {
                self.line(&format!("m.{}Data = nil", state.name));
            }
        }

        // Set the target state's data if it has fields
        let target = states.iter().find(|s| s.name == target_state);
        if let Some(t) = target {
            if !t.fields.is_empty() {
                let data_type = format!("{machine_name}{}Data", target_state);
                self.line(&format!("m.{}Data = &{data_type}{{", target_state));
                self.indent += 1;
                for (i, field) in t.fields.iter().enumerate() {
                    let value = if i < args.len() {
                        self.expr_to_go(&args[i])
                    } else {
                        format!("{} /* TODO: missing arg */", self.zero_value(&field.ty))
                    };
                    self.line(&format!("{}: {},", pascal_case(&field.name), value));
                }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    fn expr_to_go(&self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(v) => format!("{v}"),
            Expr::FloatLit(v) => format!("{v}"),
            Expr::StringLit(s) => format!("\"{s}\""),
            Expr::BoolLit(b) => format!("{b}"),
            Expr::Ident(name) => name.clone(),
            Expr::FieldAccess(base, field) => {
                let base_str = self.expr_to_go(base);
                format!("{base_str}.{}", pascal_case(field))
            }
            Expr::FnCall(name, args) => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.expr_to_go(a)).collect();
                format!("{}({})", name, arg_strs.join(", "))
            }
            Expr::BinOp(left, op, right) => {
                let l = self.expr_to_go(left);
                let r = self.expr_to_go(right);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Lte => "<=",
                    BinOp::Gt => ">",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                format!("({l} {op_str} {r})")
            }
            Expr::UnaryOp(op, inner) => {
                let val = self.expr_to_go(inner);
                match op {
                    UnaryOp::Not => format!("(!{val})"),
                    UnaryOp::Neg => format!("(-{val})"),
                }
            }
            Expr::Perform(name, args) => {
                let method = pascal_case(name);
                let arg_strs: Vec<String> = args.iter().map(|a| self.expr_to_go(a)).collect();
                format!("effects.{}({})", method, arg_strs.join(", "))
            }
        }
    }

    // === Helpers ===

    fn type_expr_to_go(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Simple(name) => map_go_type(name),
            TypeExpr::Generic(name, args) => match name.as_str() {
                "Vec" => {
                    let inner = args.first().map(|a| self.type_expr_to_go(a)).unwrap_or("interface{}".to_string());
                    format!("[]{inner}")
                }
                "Option" => {
                    let inner = args.first().map(|a| self.type_expr_to_go(a)).unwrap_or("interface{}".to_string());
                    format!("*{inner}")
                }
                "Result" => {
                    // Go doesn't have Result — just use the success type + error return
                    args.first().map(|a| self.type_expr_to_go(a)).unwrap_or("interface{}".to_string())
                }
                other => {
                    let arg_strs: Vec<String> = args.iter().map(|a| self.type_expr_to_go(a)).collect();
                    format!("{other}[{}]", arg_strs.join(", "))
                }
            },
        }
    }

    fn zero_value(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Simple(name) => match name.as_str() {
                "String" => "\"\"".to_string(),
                "i64" | "i32" | "u64" | "u32" => "0".to_string(),
                "f64" | "f32" => "0.0".to_string(),
                "bool" => "false".to_string(),
                other => format!("{other}{{}}")
            },
            TypeExpr::Generic(name, _) => match name.as_str() {
                "Vec" => "nil".to_string(),
                "Option" => "nil".to_string(),
                _ => "nil".to_string(),
            },
        }
    }

    fn emit_json_helpers(&mut self, machine_name: &str) {
        // ToJSON
        self.line(&format!("func (m *{machine_name}) ToJSON() ([]byte, error) {{"));
        self.indent += 1;
        self.line("return json.MarshalIndent(m, \"\", \"  \")");
        self.indent -= 1;
        self.line("}");
        self.newline();

        // FromJSON
        self.line(&format!("func {machine_name}FromJSON(data []byte) (*{machine_name}, error) {{"));
        self.indent += 1;
        self.line(&format!("var m {machine_name}"));
        self.line("if err := json.Unmarshal(data, &m); err != nil {");
        self.indent += 1;
        self.line("return nil, err");
        self.indent -= 1;
        self.line("}");
        self.line("return &m, nil");
        self.indent -= 1;
        self.line("}");
    }

    fn line(&mut self, text: &str) {
        let indent = "\t".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(text);
        self.output.push('\n');
    }

    fn newline(&mut self) {
        self.output.push('\n');
    }
}

// === Utility Functions ===

fn map_go_type(name: &str) -> String {
    match name {
        "String" => "string".to_string(),
        "i64" => "int64".to_string(),
        "i32" => "int32".to_string(),
        "u64" => "uint64".to_string(),
        "u32" => "uint32".to_string(),
        "f64" => "float64".to_string(),
        "f32" => "float32".to_string(),
        "bool" => "bool".to_string(),
        other => other.to_string(), // User-defined types pass through
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_ascii_lowercase());
    }
    result
}

/// Check if a handler body uses any `perform` expressions or statements
fn handler_uses_perform(block: &Block) -> bool {
    block.statements.iter().any(|stmt| match stmt {
        Statement::Perform { .. } => true,
        Statement::Let { value, .. } => expr_has_perform(value),
        Statement::Return(expr) => expr_has_perform(expr),
        Statement::Expr(expr) => expr_has_perform(expr),
        Statement::If {
            condition,
            then_block,
            else_block,
        } => {
            expr_has_perform(condition)
                || handler_uses_perform(then_block)
                || else_block.as_ref().map(|b| handler_uses_perform(b)).unwrap_or(false)
        }
        Statement::Goto { args, .. } => args.iter().any(expr_has_perform),
    })
}

fn expr_has_perform(expr: &Expr) -> bool {
    match expr {
        Expr::Perform(_, _) => true,
        Expr::BinOp(l, _, r) => expr_has_perform(l) || expr_has_perform(r),
        Expr::UnaryOp(_, e) => expr_has_perform(e),
        Expr::FnCall(_, args) => args.iter().any(expr_has_perform),
        Expr::FieldAccess(base, _) => expr_has_perform(base),
        _ => false,
    }
}
