// Code generated by Gust compiler — DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type AppState int

const (
	AppStateReady = iota
	AppStateDone
)

func (s AppState) String() string {
	switch s {
	case AppStateReady:
		return "Ready"
	case AppStateDone:
		return "Done"
	default:
		return "Unknown"
	}
}

type App struct {
	State AppState
}

func (m App) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case AppStateReady:
	case AppStateDone:
	default:
		return nil, fmt.Errorf("App: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *App) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Ready":
		m.State = AppStateReady
	case "Done":
		m.State = AppStateDone
	default:
		return fmt.Errorf("App: unknown state %q", envelope.State)
	}
	return nil
}

func NewApp() *App {
	return &App{
		State: AppStateReady,
	}
}

type AppError struct {
	Transition string
	From      string
	Message   string
}

func (e *AppError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *App) Run() error {
	if m.State != AppStateReady {
		return &AppError{Transition: "run", From: m.State.String()}
	}

	m.State = AppStateDone

	return nil
}

func (m *App) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func AppFromJSON(data []byte) (*App, error) {
	var m App
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
