// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AppState {
    Ready,
    Done,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct App {
    pub state: AppState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum AppError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl App {
    pub fn new() -> Self {
        Self { state: AppState::Ready }
    }

    pub fn state(&self) -> &AppState {
        &self.state
    }

    pub fn run(&mut self) -> Result<(), AppError> {
        match &self.state {
            AppState::Ready => {
                self.state = AppState::Done;
                Ok(())
            }
            _ => Err(AppError::InvalidTransition {
                transition: "run".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

impl Default for App {
    fn default() -> Self {
        Self::new()
    }
}
