// Code generated by Gust compiler — DO NOT EDIT.

package async_payment

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Money struct {
	Cents int64 `json:"cents"`
	Currency string `json:"currency"`
}

type AsyncPaymentProcessorState int

const (
	AsyncPaymentProcessorStatePending = iota
	AsyncPaymentProcessorStateCharged
	AsyncPaymentProcessorStateFailed
)

func (s AsyncPaymentProcessorState) String() string {
	switch s {
	case AsyncPaymentProcessorStatePending:
		return "Pending"
	case AsyncPaymentProcessorStateCharged:
		return "Charged"
	case AsyncPaymentProcessorStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type AsyncPaymentProcessorPendingData struct {
	Total Money `json:"total"`
}

type AsyncPaymentProcessorChargedData struct {
	Receipt string `json:"receipt"`
}

type AsyncPaymentProcessorFailedData struct {
	Reason string `json:"reason"`
}

type AsyncPaymentProcessorEffects interface {
	// gust:effect -- replay-safe / idempotent
	ProcessPayment(ctx context.Context, total Money) (string, error)
}

type AsyncPaymentProcessor struct {
	State AsyncPaymentProcessorState `json:"state"`
	PendingData *AsyncPaymentProcessorPendingData `json:"pending_data,omitempty"`
	ChargedData *AsyncPaymentProcessorChargedData `json:"charged_data,omitempty"`
	FailedData *AsyncPaymentProcessorFailedData `json:"failed_data,omitempty"`
}

func (m *AsyncPaymentProcessor) clearStateData() {
	m.PendingData = nil
	m.ChargedData = nil
	m.FailedData = nil
}

func NewAsyncPaymentProcessor(total Money) *AsyncPaymentProcessor {
	return &AsyncPaymentProcessor{
		State: AsyncPaymentProcessorStatePending,
		PendingData: &AsyncPaymentProcessorPendingData{
			Total: total,
		},
	}
}

type AsyncPaymentProcessorError struct {
	Transition string
	From      string
	Message   string
}

func (e *AsyncPaymentProcessorError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *AsyncPaymentProcessor) Charge(ctx context.Context, effects AsyncPaymentProcessorEffects) error {
	if m.State != AsyncPaymentProcessorStatePending {
		return &AsyncPaymentProcessorError{Transition: "charge", From: m.State.String()}
	}

	total := m.PendingData.Total

	receipt, err := effects.ProcessPayment(ctx, total)
	if err != nil {
		return err
	}
	if receipt == "ok" {
		m.State = AsyncPaymentProcessorStateCharged
		m.clearStateData()
		m.ChargedData = &AsyncPaymentProcessorChargedData{
			Receipt: receipt,
		}
	} else {
		m.State = AsyncPaymentProcessorStateFailed
		m.clearStateData()
		m.FailedData = &AsyncPaymentProcessorFailedData{
			Reason: "payment declined",
		}
	}

	return nil
}

func (m *AsyncPaymentProcessor) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func AsyncPaymentProcessorFromJSON(data []byte) (*AsyncPaymentProcessor, error) {
	var m AsyncPaymentProcessor
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
