// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Money {
    pub cents: i64,
    pub currency: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AsyncPaymentProcessorState {
    Pending {
        total: Money,
    },
    Charged {
        receipt: String,
    },
    Failed {
        reason: String,
    },
}

pub trait AsyncPaymentProcessorEffects {
    /// gust:effect -- replay-safe / idempotent
    fn process_payment(&self, total: &Money) -> impl ::core::future::Future<Output = String> + Send;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AsyncPaymentProcessor {
    pub state: AsyncPaymentProcessorState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum AsyncPaymentProcessorError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl AsyncPaymentProcessor {
    pub fn new(total: Money) -> Self {
        Self { state: AsyncPaymentProcessorState::Pending { total } }
    }

    pub fn state(&self) -> &AsyncPaymentProcessorState {
        &self.state
    }

    pub async fn charge(&mut self, effects: &impl AsyncPaymentProcessorEffects) -> Result<(), AsyncPaymentProcessorError> {
        match &self.state {
            AsyncPaymentProcessorState::Pending { total } => {
                let total = total.clone();
                let receipt = effects.process_payment(&total).await;
                if receipt == "ok" {
                    self.state = AsyncPaymentProcessorState::Charged { receipt };
                    Ok(())
                } else {
                    let __goto_failed_reason = "payment declined".to_string();
                    self.state = AsyncPaymentProcessorState::Failed { reason: __goto_failed_reason };
                    Ok(())
                }
            }
            _ => Err(AsyncPaymentProcessorError::InvalidTransition {
                transition: "charge".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
