// Code generated by Gust compiler — DO NOT EDIT.

package circuit_breaker

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type CircuitBreakerState int

const (
	CircuitBreakerStateClosed = iota
	CircuitBreakerStateOpen
	CircuitBreakerStateHalfOpen
)

func (s CircuitBreakerState) String() string {
	switch s {
	case CircuitBreakerStateClosed:
		return "Closed"
	case CircuitBreakerStateOpen:
		return "Open"
	case CircuitBreakerStateHalfOpen:
		return "HalfOpen"
	default:
		return "Unknown"
	}
}

type CircuitBreakerClosedData struct {
	Failures int64 `json:"failures"`
	Threshold int64 `json:"threshold"`
}

type CircuitBreakerOpenData struct {
	OpenedAt int64 `json:"opened_at"`
	TimeoutMs int64 `json:"timeout_ms"`
}

type CircuitBreakerHalfOpenData struct {
	Successes int64 `json:"successes"`
	Needed int64 `json:"needed"`
}

type CircuitBreakerEffects interface {
	// gust:effect -- replay-safe / idempotent
	CurrentTimeMs() int64
}

type CircuitBreaker struct {
	State CircuitBreakerState `json:"state"`
	ClosedData *CircuitBreakerClosedData `json:"closed_data,omitempty"`
	OpenData *CircuitBreakerOpenData `json:"open_data,omitempty"`
	HalfOpenData *CircuitBreakerHalfOpenData `json:"half_open_data,omitempty"`
}

func (m *CircuitBreaker) clearStateData() {
	m.ClosedData = nil
	m.OpenData = nil
	m.HalfOpenData = nil
}

func NewCircuitBreaker(failures int64, threshold int64) *CircuitBreaker {
	return &CircuitBreaker{
		State: CircuitBreakerStateClosed,
		ClosedData: &CircuitBreakerClosedData{
			Failures: failures,
			Threshold: threshold,
		},
	}
}

type CircuitBreakerError struct {
	Transition string
	From      string
	Message   string
}

func (e *CircuitBreakerError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *CircuitBreaker) Fail(effects CircuitBreakerEffects) error {
	if m.State != CircuitBreakerStateClosed {
		return &CircuitBreakerError{Transition: "fail", From: m.State.String()}
	}

	failures := m.ClosedData.Failures
	threshold := m.ClosedData.Threshold

	next_failures := (failures + 1)
	if next_failures >= threshold {
		m.State = CircuitBreakerStateOpen
		m.clearStateData()
		m.OpenData = &CircuitBreakerOpenData{
			OpenedAt: effects.CurrentTimeMs(),
			TimeoutMs: 60000,
		}
	} else {
		m.State = CircuitBreakerStateClosed
		m.clearStateData()
		m.ClosedData = &CircuitBreakerClosedData{
			Failures: next_failures,
			Threshold: threshold,
		}
	}

	return nil
}

func (m *CircuitBreaker) CheckOpen(effects CircuitBreakerEffects) error {
	if m.State != CircuitBreakerStateOpen {
		return &CircuitBreakerError{Transition: "check_open", From: m.State.String()}
	}

	opened_at := m.OpenData.OpenedAt
	timeout_ms := m.OpenData.TimeoutMs

	elapsed := (effects.CurrentTimeMs() - opened_at)
	if elapsed >= timeout_ms {
		m.State = CircuitBreakerStateHalfOpen
		m.clearStateData()
		m.HalfOpenData = &CircuitBreakerHalfOpenData{
			Successes: 0,
			Needed: 3,
		}
	} else {
		m.State = CircuitBreakerStateOpen
		m.clearStateData()
		m.OpenData = &CircuitBreakerOpenData{
			OpenedAt: opened_at,
			TimeoutMs: timeout_ms,
		}
	}

	return nil
}

func (m *CircuitBreaker) SucceedHalf() error {
	if m.State != CircuitBreakerStateHalfOpen {
		return &CircuitBreakerError{Transition: "succeed_half", From: m.State.String()}
	}

	successes := m.HalfOpenData.Successes
	needed := m.HalfOpenData.Needed

	next := (successes + 1)
	if next >= needed {
		m.State = CircuitBreakerStateClosed
		m.clearStateData()
		m.ClosedData = &CircuitBreakerClosedData{
			Failures: 0,
			Threshold: 5,
		}
	} else {
		m.State = CircuitBreakerStateHalfOpen
		m.clearStateData()
		m.HalfOpenData = &CircuitBreakerHalfOpenData{
			Successes: next,
			Needed: needed,
		}
	}

	return nil
}

func (m *CircuitBreaker) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func CircuitBreakerFromJSON(data []byte) (*CircuitBreaker, error) {
	var m CircuitBreaker
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
