// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CircuitBreakerState {
    Closed {
        failures: i64,
        threshold: i64,
    },
    Open {
        opened_at: i64,
        timeout_ms: i64,
    },
    HalfOpen {
        successes: i64,
        needed: i64,
    },
}

pub trait CircuitBreakerEffects {
    /// gust:effect -- replay-safe / idempotent
    fn current_time_ms(&self) -> i64;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircuitBreaker {
    pub state: CircuitBreakerState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum CircuitBreakerError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl CircuitBreaker {
    pub fn new(failures: i64, threshold: i64) -> Self {
        Self { state: CircuitBreakerState::Closed { failures, threshold } }
    }

    pub fn state(&self) -> &CircuitBreakerState {
        &self.state
    }

    pub fn fail(&mut self, effects: &impl CircuitBreakerEffects) -> Result<(), CircuitBreakerError> {
        match &self.state {
            CircuitBreakerState::Closed { failures, threshold } => {
                let failures = *failures;
                let threshold = *threshold;
                let next_failures = failures + 1;
                if next_failures >= threshold {
                    let __goto_open_opened_at = effects.current_time_ms();
                    let __goto_open_timeout_ms = 60000;
                    self.state = CircuitBreakerState::Open { opened_at: __goto_open_opened_at, timeout_ms: __goto_open_timeout_ms };
                    Ok(())
                } else {
                    self.state = CircuitBreakerState::Closed { failures: next_failures, threshold };
                    Ok(())
                }
            }
            _ => Err(CircuitBreakerError::InvalidTransition {
                transition: "fail".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn check_open(&mut self, effects: &impl CircuitBreakerEffects) -> Result<(), CircuitBreakerError> {
        match &self.state {
            CircuitBreakerState::Open { opened_at, timeout_ms } => {
                let opened_at = *opened_at;
                let timeout_ms = *timeout_ms;
                let elapsed = effects.current_time_ms() - opened_at;
                if elapsed >= timeout_ms {
                    let __goto_half_open_successes = 0;
                    let __goto_half_open_needed = 3;
                    self.state = CircuitBreakerState::HalfOpen { successes: __goto_half_open_successes, needed: __goto_half_open_needed };
                    Ok(())
                } else {
                    self.state = CircuitBreakerState::Open { opened_at, timeout_ms };
                    Ok(())
                }
            }
            _ => Err(CircuitBreakerError::InvalidTransition {
                transition: "check_open".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn succeed_half(&mut self) -> Result<(), CircuitBreakerError> {
        match &self.state {
            CircuitBreakerState::HalfOpen { successes, needed } => {
                let successes = *successes;
                let needed = *needed;
                let next = successes + 1;
                if next >= needed {
                    let __goto_closed_failures = 0;
                    let __goto_closed_threshold = 5;
                    self.state = CircuitBreakerState::Closed { failures: __goto_closed_failures, threshold: __goto_closed_threshold };
                    Ok(())
                } else {
                    self.state = CircuitBreakerState::HalfOpen { successes: next, needed };
                    Ok(())
                }
            }
            _ => Err(CircuitBreakerError::InvalidTransition {
                transition: "succeed_half".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
