// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DoorState {
    Closed,
    Open,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Door {
    pub state: DoorState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum DoorError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl Door {
    pub fn new() -> Self {
        Self { state: DoorState::Closed }
    }

    pub fn state(&self) -> &DoorState {
        &self.state
    }

    pub fn open(&mut self) -> Result<(), DoorError> {
        match &self.state {
            DoorState::Closed => {
                self.state = DoorState::Open;
                Ok(())
            }
            _ => Err(DoorError::InvalidTransition {
                transition: "open".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

impl Default for Door {
    fn default() -> Self {
        Self::new()
    }
}
