// Code generated by Gust compiler — DO NOT EDIT.

package engine_failure

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type EngineFailure string

const (
	EngineFailureUserError EngineFailure = "UserError"
	EngineFailureSystemError EngineFailure = "SystemError"
	EngineFailureIntegrationError EngineFailure = "IntegrationError"
	EngineFailureTimeout EngineFailure = "Timeout"
	EngineFailureCancelled EngineFailure = "Cancelled"
)
