// Code generated by Gust compiler — DO NOT EDIT.

package enum_status

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Status string

const (
	StatusPending Status = "Pending"
	StatusApproved Status = "Approved"
	StatusRejected Status = "Rejected"
)

type StatusReporterState int

const (
	StatusReporterStateIdle = iota
	StatusReporterStateFinished
)

func (s StatusReporterState) String() string {
	switch s {
	case StatusReporterStateIdle:
		return "Idle"
	case StatusReporterStateFinished:
		return "Finished"
	default:
		return "Unknown"
	}
}

type StatusReporterIdleData struct {
	Status Status `json:"status"`
}

type StatusReporterFinishedData struct {
	Message string `json:"message"`
}

type StatusReporter struct {
	State StatusReporterState
	IdleData *StatusReporterIdleData
	FinishedData *StatusReporterFinishedData
}

func (m *StatusReporter) clearStateData() {
	m.IdleData = nil
	m.FinishedData = nil
}

func (m StatusReporter) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case StatusReporterStateIdle:
		if m.IdleData != nil {
			envelope.Data = m.IdleData
		}
	case StatusReporterStateFinished:
		if m.FinishedData != nil {
			envelope.Data = m.FinishedData
		}
	default:
		return nil, fmt.Errorf("StatusReporter: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *StatusReporter) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Idle":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("StatusReporter: state 'Idle' requires a data payload")
		}
		data := &StatusReporterIdleData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = StatusReporterStateIdle
		m.IdleData = data
	case "Finished":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("StatusReporter: state 'Finished' requires a data payload")
		}
		data := &StatusReporterFinishedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = StatusReporterStateFinished
		m.FinishedData = data
	default:
		return fmt.Errorf("StatusReporter: unknown state %q", envelope.State)
	}
	return nil
}

func NewStatusReporter(status Status) *StatusReporter {
	return &StatusReporter{
		State: StatusReporterStateIdle,
		IdleData: &StatusReporterIdleData{
			Status: status,
		},
	}
}

type StatusReporterError struct {
	Transition string
	From      string
	Message   string
}

func (e *StatusReporterError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *StatusReporter) Finish() error {
	if m.State != StatusReporterStateIdle {
		return &StatusReporterError{Transition: "finish", From: m.State.String()}
	}

	status := m.IdleData.Status

	switch status {
		case StatusApproved:
			m.State = StatusReporterStateFinished
			m.clearStateData()
			m.FinishedData = &StatusReporterFinishedData{
				Message: msg,
			}
		case StatusRejected:
			m.State = StatusReporterStateFinished
			m.clearStateData()
			m.FinishedData = &StatusReporterFinishedData{
				Message: msg,
			}
		default:
			m.State = StatusReporterStateFinished
			m.clearStateData()
			m.FinishedData = &StatusReporterFinishedData{
				Message: "pending",
			}
	}

	return nil
}

func (m *StatusReporter) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func StatusReporterFromJSON(data []byte) (*StatusReporter, error) {
	var m StatusReporter
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
