// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Status {
    Pending,
    Approved(String),
    Rejected(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StatusReporterState {
    Idle {
        status: Status,
    },
    Finished {
        message: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StatusReporter {
    pub state: StatusReporterState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum StatusReporterError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl StatusReporter {
    pub fn new(status: Status) -> Self {
        Self { state: StatusReporterState::Idle { status } }
    }

    pub fn state(&self) -> &StatusReporterState {
        &self.state
    }

    pub fn finish(&mut self) -> Result<(), StatusReporterError> {
        match &self.state {
            StatusReporterState::Idle { status } => {
                let status = status.clone();
                match status {
                    Status::Approved(msg) => {
                        self.state = StatusReporterState::Finished { message: msg };
                        Ok(())
                    }
                    Status::Rejected(msg) => {
                        self.state = StatusReporterState::Finished { message: msg };
                        Ok(())
                    }
                    _ => {
                        let __goto_finished_message = "pending".to_string();
                        self.state = StatusReporterState::Finished { message: __goto_finished_message };
                        Ok(())
                    }
                }
            }
            _ => Err(StatusReporterError::InvalidTransition {
                transition: "finish".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
