// Code generated by Gust compiler — DO NOT EDIT.

package gu_contracts_order

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Order struct {
	Id string `json:"id"`
	Customer string `json:"customer"`
	TotalCents int64 `json:"total_cents"`
}

type OrderLifecycleState int

const (
	OrderLifecycleStateReceived = iota
	OrderLifecycleStateAccepted
	OrderLifecycleStateRejected
)

func (s OrderLifecycleState) String() string {
	switch s {
	case OrderLifecycleStateReceived:
		return "Received"
	case OrderLifecycleStateAccepted:
		return "Accepted"
	case OrderLifecycleStateRejected:
		return "Rejected"
	default:
		return "Unknown"
	}
}

type OrderLifecycleReceivedData struct {
	Order Order `json:"order"`
}

type OrderLifecycleAcceptedData struct {
	Order Order `json:"order"`
}

type OrderLifecycleRejectedData struct {
	Reason string `json:"reason"`
}

type OrderLifecycle struct {
	State OrderLifecycleState
	ReceivedData *OrderLifecycleReceivedData
	AcceptedData *OrderLifecycleAcceptedData
	RejectedData *OrderLifecycleRejectedData
}

func (m *OrderLifecycle) clearStateData() {
	m.ReceivedData = nil
	m.AcceptedData = nil
	m.RejectedData = nil
}

func (m OrderLifecycle) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case OrderLifecycleStateReceived:
		if m.ReceivedData != nil {
			envelope.Data = m.ReceivedData
		}
	case OrderLifecycleStateAccepted:
		if m.AcceptedData != nil {
			envelope.Data = m.AcceptedData
		}
	case OrderLifecycleStateRejected:
		if m.RejectedData != nil {
			envelope.Data = m.RejectedData
		}
	default:
		return nil, fmt.Errorf("OrderLifecycle: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *OrderLifecycle) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Received":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("OrderLifecycle: state 'Received' requires a data payload")
		}
		data := &OrderLifecycleReceivedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = OrderLifecycleStateReceived
		m.ReceivedData = data
	case "Accepted":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("OrderLifecycle: state 'Accepted' requires a data payload")
		}
		data := &OrderLifecycleAcceptedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = OrderLifecycleStateAccepted
		m.AcceptedData = data
	case "Rejected":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("OrderLifecycle: state 'Rejected' requires a data payload")
		}
		data := &OrderLifecycleRejectedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = OrderLifecycleStateRejected
		m.RejectedData = data
	default:
		return fmt.Errorf("OrderLifecycle: unknown state %q", envelope.State)
	}
	return nil
}

func NewOrderLifecycle(order Order) *OrderLifecycle {
	return &OrderLifecycle{
		State: OrderLifecycleStateReceived,
		ReceivedData: &OrderLifecycleReceivedData{
			Order: order,
		},
	}
}

type OrderLifecycleError struct {
	Transition string
	From      string
	Message   string
}

func (e *OrderLifecycleError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *OrderLifecycle) Accept() error {
	if m.State != OrderLifecycleStateReceived {
		return &OrderLifecycleError{Transition: "accept", From: m.State.String()}
	}

	var __goto_accepted_order Order = m.ReceivedData.Order
	m.State = OrderLifecycleStateAccepted
	m.clearStateData()
	m.AcceptedData = &OrderLifecycleAcceptedData{
		Order: __goto_accepted_order,
	}

	return nil
}

func (m *OrderLifecycle) Reject() error {
	if m.State != OrderLifecycleStateReceived {
		return &OrderLifecycleError{Transition: "reject", From: m.State.String()}
	}

	m.State = OrderLifecycleStateRejected
	m.clearStateData()
	m.RejectedData = &OrderLifecycleRejectedData{
		Reason: "rejected",
	}

	return nil
}

func (m *OrderLifecycle) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func OrderLifecycleFromJSON(data []byte) (*OrderLifecycle, error) {
	var m OrderLifecycle
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
