// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub id: String,
    pub customer: String,
    pub total_cents: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OrderLifecycleState {
    Received {
        order: Order,
    },
    Accepted {
        order: Order,
    },
    Rejected {
        reason: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderLifecycle {
    pub state: OrderLifecycleState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderLifecycleError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl OrderLifecycle {
    pub fn new(order: Order) -> Self {
        Self { state: OrderLifecycleState::Received { order } }
    }

    pub fn state(&self) -> &OrderLifecycleState {
        &self.state
    }

    pub fn accept(&mut self) -> Result<(), OrderLifecycleError> {
        match &self.state {
            OrderLifecycleState::Received { order } => {
                let order = order.clone();
                self.state = OrderLifecycleState::Accepted { order };
                Ok(())
            }
            _ => Err(OrderLifecycleError::InvalidTransition {
                transition: "accept".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn reject(&mut self) -> Result<(), OrderLifecycleError> {
        match &self.state {
            OrderLifecycleState::Received { order: _order } => {
                let __goto_rejected_reason = "rejected".to_string();
                self.state = OrderLifecycleState::Rejected { reason: __goto_rejected_reason };
                Ok(())
            }
            _ => Err(OrderLifecycleError::InvalidTransition {
                transition: "reject".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
