// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HealthCheckState<T> {
    Healthy {
        status: T,
    },
    Degraded {
        status: T,
        failures: i64,
    },
    Unhealthy {
        reason: String,
    },
}

pub trait HealthCheckEffects<T> {
    /// gust:effect -- replay-safe / idempotent
    fn run_probe(&self) -> impl ::core::future::Future<Output = Result<T, String>> + Send;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthCheck<T> {
    pub state: HealthCheckState<T>,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum HealthCheckError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl<T: core::fmt::Debug + Clone> HealthCheck<T> {
    pub fn new(status: T) -> Self {
        Self { state: HealthCheckState::Healthy { status } }
    }

    pub fn state(&self) -> &HealthCheckState<T> {
        &self.state
    }

    pub async fn probe(&mut self, effects: &impl HealthCheckEffects<T>) -> Result<(), HealthCheckError> {
        match &self.state {
            HealthCheckState::Healthy { status } => {
                let status = status.clone();
                let result = effects.run_probe().await;
                match result {
                    Ok(next_status) => {
                        self.state = HealthCheckState::Healthy { status: next_status };
                        Ok(())
                    }
                    Err(_err) => {
                        let __goto_degraded_failures = 1;
                        self.state = HealthCheckState::Degraded { status, failures: __goto_degraded_failures };
                        Ok(())
                    }
                }
            }
            _ => Err(HealthCheckError::InvalidTransition {
                transition: "probe".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn recover(&mut self, effects: &impl HealthCheckEffects<T>) -> Result<(), HealthCheckError> {
        match &self.state {
            HealthCheckState::Degraded { status: _status, failures: _failures } => {
                let result = effects.run_probe().await;
                match result {
                    Ok(next_status) => {
                        self.state = HealthCheckState::Healthy { status: next_status };
                        Ok(())
                    }
                    Err(err) => {
                        self.state = HealthCheckState::Unhealthy { reason: err };
                        Ok(())
                    }
                }
            }
            _ => Err(HealthCheckError::InvalidTransition {
                transition: "recover".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
