// Code generated by Gust compiler — DO NOT EDIT.

package health_check

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type HealthCheckState[T any] int

const (
	HealthCheckStateHealthy = iota
	HealthCheckStateDegraded
	HealthCheckStateUnhealthy
)

func (s HealthCheckState[T]) String() string {
	switch s {
	case HealthCheckStateHealthy:
		return "Healthy"
	case HealthCheckStateDegraded:
		return "Degraded"
	case HealthCheckStateUnhealthy:
		return "Unhealthy"
	default:
		return "Unknown"
	}
}

type HealthCheckHealthyData[T any] struct {
	Status T `json:"status"`
}

type HealthCheckDegradedData[T any] struct {
	Status T `json:"status"`
	Failures int64 `json:"failures"`
}

type HealthCheckUnhealthyData[T any] struct {
	Reason string `json:"reason"`
}

type HealthCheckEffects[T any] interface {
	// gust:effect -- replay-safe / idempotent
	RunProbe(ctx context.Context) (T, error)
}

type HealthCheck[T any] struct {
	State HealthCheckState[T] `json:"state"`
	HealthyData *HealthCheckHealthyData[T] `json:"healthy_data,omitempty"`
	DegradedData *HealthCheckDegradedData[T] `json:"degraded_data,omitempty"`
	UnhealthyData *HealthCheckUnhealthyData[T] `json:"unhealthy_data,omitempty"`
}

func (m *HealthCheck[T]) clearStateData() {
	m.HealthyData = nil
	m.DegradedData = nil
	m.UnhealthyData = nil
}

func NewHealthCheck[T any](status T) *HealthCheck[T] {
	return &HealthCheck[T]{
		State: HealthCheckStateHealthy,
		HealthyData: &HealthCheckHealthyData[T]{
			Status: status,
		},
	}
}

type HealthCheckError struct {
	Transition string
	From      string
	Message   string
}

func (e *HealthCheckError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *HealthCheck[T]) Probe(ctx context.Context, effects HealthCheckEffects[T]) error {
	if m.State != HealthCheckStateHealthy {
		return &HealthCheckError{Transition: "probe", From: m.State.String()}
	}

	status := m.HealthyData.Status

	result, __result_err := effects.RunProbe(ctx)
	if __result_err == nil {
		next_status := result
		m.State = HealthCheckStateHealthy
		m.clearStateData()
		m.HealthyData = &HealthCheckHealthyData[T]{
			Status: next_status,
		}
	} else {
		m.State = HealthCheckStateDegraded
		m.clearStateData()
		m.DegradedData = &HealthCheckDegradedData[T]{
			Status: status,
			Failures: 1,
		}
	}

	return nil
}

func (m *HealthCheck[T]) Recover(ctx context.Context, effects HealthCheckEffects[T]) error {
	if m.State != HealthCheckStateDegraded {
		return &HealthCheckError{Transition: "recover", From: m.State.String()}
	}

	result, __result_err := effects.RunProbe(ctx)
	if __result_err == nil {
		next_status := result
		m.State = HealthCheckStateHealthy
		m.clearStateData()
		m.HealthyData = &HealthCheckHealthyData[T]{
			Status: next_status,
		}
	} else {
		err := __result_err.Error()
		m.State = HealthCheckStateUnhealthy
		m.clearStateData()
		m.UnhealthyData = &HealthCheckUnhealthyData[T]{
			Reason: err,
		}
	}

	return nil
}

func (m *HealthCheck[T]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func HealthCheckFromJSON[T any](data []byte) (*HealthCheck[T], error) {
	var m HealthCheck[T]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
