// Code generated by Gust compiler — DO NOT EDIT.

package order

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Order struct {
	Id string `json:"id"`
	Items string `json:"items"`
	Quantity int64 `json:"quantity"`
}

type Money struct {
	Amount int64 `json:"amount"`
	Currency string `json:"currency"`
}

type Receipt struct {
	TransactionId string `json:"transaction_id"`
	Amount Money `json:"amount"`
}

type OrderMachineState int

const (
	OrderMachineStatePending = iota
	OrderMachineStateValidated
	OrderMachineStateCharged
	OrderMachineStateShipped
	OrderMachineStateFailed
)

func (s OrderMachineState) String() string {
	switch s {
	case OrderMachineStatePending:
		return "Pending"
	case OrderMachineStateValidated:
		return "Validated"
	case OrderMachineStateCharged:
		return "Charged"
	case OrderMachineStateShipped:
		return "Shipped"
	case OrderMachineStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type OrderMachinePendingData struct {
	Order Order `json:"order"`
}

type OrderMachineValidatedData struct {
	Order Order `json:"order"`
	Total Money `json:"total"`
}

type OrderMachineChargedData struct {
	Order Order `json:"order"`
	Receipt Receipt `json:"receipt"`
}

type OrderMachineShippedData struct {
	Order Order `json:"order"`
	Tracking string `json:"tracking"`
}

type OrderMachineFailedData struct {
	Reason string `json:"reason"`
}

type OrderMachineEffects interface {
	// gust:effect -- replay-safe / idempotent
	CalculateTotal(order Order) Money
	// gust:effect -- replay-safe / idempotent
	ProcessPayment(total Money) Receipt
	// gust:effect -- replay-safe / idempotent
	CreateShipment(order Order) string
}

type OrderMachine struct {
	State OrderMachineState `json:"state"`
	PendingData *OrderMachinePendingData `json:"pending_data,omitempty"`
	ValidatedData *OrderMachineValidatedData `json:"validated_data,omitempty"`
	ChargedData *OrderMachineChargedData `json:"charged_data,omitempty"`
	ShippedData *OrderMachineShippedData `json:"shipped_data,omitempty"`
	FailedData *OrderMachineFailedData `json:"failed_data,omitempty"`
}

func (m *OrderMachine) clearStateData() {
	m.PendingData = nil
	m.ValidatedData = nil
	m.ChargedData = nil
	m.ShippedData = nil
	m.FailedData = nil
}

func NewOrderMachine(order Order) *OrderMachine {
	return &OrderMachine{
		State: OrderMachineStatePending,
		PendingData: &OrderMachinePendingData{
			Order: order,
		},
	}
}

type OrderMachineError struct {
	Transition string
	From      string
	Message   string
}

func (e *OrderMachineError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *OrderMachine) Validate(effects OrderMachineEffects) error {
	if m.State != OrderMachineStatePending {
		return &OrderMachineError{Transition: "validate", From: m.State.String()}
	}

	total := effects.CalculateTotal(m.PendingData.Order)
	if total.Amount > 0 {
		var __goto_validated_order Order = m.PendingData.Order
		m.State = OrderMachineStateValidated
		m.clearStateData()
		m.ValidatedData = &OrderMachineValidatedData{
			Order: __goto_validated_order,
			Total: total,
		}
	} else {
		m.State = OrderMachineStateFailed
		m.clearStateData()
		m.FailedData = &OrderMachineFailedData{
			Reason: "invalid order total",
		}
	}

	return nil
}

func (m *OrderMachine) Charge(effects OrderMachineEffects) error {
	if m.State != OrderMachineStateValidated {
		return &OrderMachineError{Transition: "charge", From: m.State.String()}
	}

	receipt := effects.ProcessPayment(m.ValidatedData.Total)
	var __goto_charged_order Order = m.ValidatedData.Order
	m.State = OrderMachineStateCharged
	m.clearStateData()
	m.ChargedData = &OrderMachineChargedData{
		Order: __goto_charged_order,
		Receipt: receipt,
	}

	return nil
}

func (m *OrderMachine) Ship(effects OrderMachineEffects) error {
	if m.State != OrderMachineStateCharged {
		return &OrderMachineError{Transition: "ship", From: m.State.String()}
	}

	tracking := effects.CreateShipment(m.ChargedData.Order)
	var __goto_shipped_order Order = m.ChargedData.Order
	m.State = OrderMachineStateShipped
	m.clearStateData()
	m.ShippedData = &OrderMachineShippedData{
		Order: __goto_shipped_order,
		Tracking: tracking,
	}

	return nil
}

func (m *OrderMachine) Fail() error {
	if m.State != OrderMachineStatePending {
		return &OrderMachineError{Transition: "fail", From: m.State.String()}
	}

	m.State = OrderMachineStateFailed
	m.clearStateData()
	m.FailedData = &OrderMachineFailedData{
		Reason: "payment declined",
	}

	return nil
}

func (m *OrderMachine) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func OrderMachineFromJSON(data []byte) (*OrderMachine, error) {
	var m OrderMachine
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
