// Code generated by Gust compiler — DO NOT EDIT.

package payment

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type PayMoney struct {
	Amount int64 `json:"amount"`
	Currency string `json:"currency"`
}

type PayReceipt struct {
	TransactionId string `json:"transaction_id"`
	Amount PayMoney `json:"amount"`
}

type PaymentMachineState int

const (
	PaymentMachineStateAwaiting = iota
	PaymentMachineStateProcessing
	PaymentMachineStateSettled
	PaymentMachineStateDeclined
)

func (s PaymentMachineState) String() string {
	switch s {
	case PaymentMachineStateAwaiting:
		return "Awaiting"
	case PaymentMachineStateProcessing:
		return "Processing"
	case PaymentMachineStateSettled:
		return "Settled"
	case PaymentMachineStateDeclined:
		return "Declined"
	default:
		return "Unknown"
	}
}

type PaymentMachineAwaitingData struct {
	Amount PayMoney `json:"amount"`
}

type PaymentMachineProcessingData struct {
	TxId string `json:"tx_id"`
	Amount PayMoney `json:"amount"`
}

type PaymentMachineSettledData struct {
	Receipt PayReceipt `json:"receipt"`
}

type PaymentMachineDeclinedData struct {
	Reason string `json:"reason"`
}

type PaymentMachineEffects interface {
	// gust:effect -- replay-safe / idempotent
	InitiateCharge(amount PayMoney) string
	// gust:effect -- replay-safe / idempotent
	ConfirmCharge(tx_id string, amount PayMoney) PayReceipt
}

type PaymentMachine struct {
	State PaymentMachineState
	AwaitingData *PaymentMachineAwaitingData
	ProcessingData *PaymentMachineProcessingData
	SettledData *PaymentMachineSettledData
	DeclinedData *PaymentMachineDeclinedData
}

func (m *PaymentMachine) clearStateData() {
	m.AwaitingData = nil
	m.ProcessingData = nil
	m.SettledData = nil
	m.DeclinedData = nil
}

func (m PaymentMachine) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case PaymentMachineStateAwaiting:
		if m.AwaitingData != nil {
			envelope.Data = m.AwaitingData
		}
	case PaymentMachineStateProcessing:
		if m.ProcessingData != nil {
			envelope.Data = m.ProcessingData
		}
	case PaymentMachineStateSettled:
		if m.SettledData != nil {
			envelope.Data = m.SettledData
		}
	case PaymentMachineStateDeclined:
		if m.DeclinedData != nil {
			envelope.Data = m.DeclinedData
		}
	default:
		return nil, fmt.Errorf("PaymentMachine: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *PaymentMachine) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Awaiting":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("PaymentMachine: state 'Awaiting' requires a data payload")
		}
		data := &PaymentMachineAwaitingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = PaymentMachineStateAwaiting
		m.AwaitingData = data
	case "Processing":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("PaymentMachine: state 'Processing' requires a data payload")
		}
		data := &PaymentMachineProcessingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = PaymentMachineStateProcessing
		m.ProcessingData = data
	case "Settled":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("PaymentMachine: state 'Settled' requires a data payload")
		}
		data := &PaymentMachineSettledData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = PaymentMachineStateSettled
		m.SettledData = data
	case "Declined":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("PaymentMachine: state 'Declined' requires a data payload")
		}
		data := &PaymentMachineDeclinedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = PaymentMachineStateDeclined
		m.DeclinedData = data
	default:
		return fmt.Errorf("PaymentMachine: unknown state %q", envelope.State)
	}
	return nil
}

func NewPaymentMachine(amount PayMoney) *PaymentMachine {
	return &PaymentMachine{
		State: PaymentMachineStateAwaiting,
		AwaitingData: &PaymentMachineAwaitingData{
			Amount: amount,
		},
	}
}

type PaymentMachineError struct {
	Transition string
	From      string
	Message   string
}

func (e *PaymentMachineError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *PaymentMachine) Initiate(effects PaymentMachineEffects) error {
	if m.State != PaymentMachineStateAwaiting {
		return &PaymentMachineError{Transition: "initiate", From: m.State.String()}
	}

	tx_id := effects.InitiateCharge(m.AwaitingData.Amount)
	if m.AwaitingData.Amount.Amount > 0 {
		var __goto_processing_amount PayMoney = m.AwaitingData.Amount
		m.State = PaymentMachineStateProcessing
		m.clearStateData()
		m.ProcessingData = &PaymentMachineProcessingData{
			TxId: tx_id,
			Amount: __goto_processing_amount,
		}
	} else {
		m.State = PaymentMachineStateDeclined
		m.clearStateData()
		m.DeclinedData = &PaymentMachineDeclinedData{
			Reason: "amount must be positive",
		}
	}

	return nil
}

func (m *PaymentMachine) Confirm(effects PaymentMachineEffects) error {
	if m.State != PaymentMachineStateProcessing {
		return &PaymentMachineError{Transition: "confirm", From: m.State.String()}
	}

	receipt := effects.ConfirmCharge(m.ProcessingData.TxId, m.ProcessingData.Amount)
	m.State = PaymentMachineStateSettled
	m.clearStateData()
	m.SettledData = &PaymentMachineSettledData{
		Receipt: receipt,
	}

	return nil
}

func (m *PaymentMachine) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func PaymentMachineFromJSON(data []byte) (*PaymentMachine, error) {
	var m PaymentMachine
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
