// Code generated by Gust compiler — DO NOT EDIT.

package processor

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Event struct {
	Source string `json:"source"`
	Payload string `json:"payload"`
	Priority int64 `json:"priority"`
}

type ProcessedResult struct {
	EventId string `json:"event_id"`
	Output string `json:"output"`
}

type EventProcessorState int

const (
	EventProcessorStateIdle = iota
	EventProcessorStateReceiving
	EventProcessorStateValidating
	EventProcessorStateCompleted
	EventProcessorStateFailed
)

func (s EventProcessorState) String() string {
	switch s {
	case EventProcessorStateIdle:
		return "Idle"
	case EventProcessorStateReceiving:
		return "Receiving"
	case EventProcessorStateValidating:
		return "Validating"
	case EventProcessorStateCompleted:
		return "Completed"
	case EventProcessorStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type EventProcessorReceivingData struct {
	Event Event `json:"event"`
}

type EventProcessorValidatingData struct {
	Event Event `json:"event"`
}

type EventProcessorCompletedData struct {
	Result ProcessedResult `json:"result"`
}

type EventProcessorFailedData struct {
	Reason string `json:"reason"`
}

type EventProcessorEffects interface {
	// gust:effect -- replay-safe / idempotent
	ValidateEvent(event Event) string
	// gust:effect -- replay-safe / idempotent
	ProcessEvent(event Event) ProcessedResult
}

type EventProcessor struct {
	State EventProcessorState
	ReceivingData *EventProcessorReceivingData
	ValidatingData *EventProcessorValidatingData
	CompletedData *EventProcessorCompletedData
	FailedData *EventProcessorFailedData
}

func (m *EventProcessor) clearStateData() {
	m.ReceivingData = nil
	m.ValidatingData = nil
	m.CompletedData = nil
	m.FailedData = nil
}

func (m EventProcessor) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case EventProcessorStateIdle:
	case EventProcessorStateReceiving:
		if m.ReceivingData != nil {
			envelope.Data = m.ReceivingData
		}
	case EventProcessorStateValidating:
		if m.ValidatingData != nil {
			envelope.Data = m.ValidatingData
		}
	case EventProcessorStateCompleted:
		if m.CompletedData != nil {
			envelope.Data = m.CompletedData
		}
	case EventProcessorStateFailed:
		if m.FailedData != nil {
			envelope.Data = m.FailedData
		}
	default:
		return nil, fmt.Errorf("EventProcessor: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *EventProcessor) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Idle":
		m.clearStateData()
		m.State = EventProcessorStateIdle
	case "Receiving":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("EventProcessor: state 'Receiving' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"event"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("EventProcessor: state 'Receiving' is missing required field %q", field)
			}
		}
		data := &EventProcessorReceivingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = EventProcessorStateReceiving
		m.ReceivingData = data
	case "Validating":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("EventProcessor: state 'Validating' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"event"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("EventProcessor: state 'Validating' is missing required field %q", field)
			}
		}
		data := &EventProcessorValidatingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = EventProcessorStateValidating
		m.ValidatingData = data
	case "Completed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("EventProcessor: state 'Completed' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"result"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("EventProcessor: state 'Completed' is missing required field %q", field)
			}
		}
		data := &EventProcessorCompletedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = EventProcessorStateCompleted
		m.CompletedData = data
	case "Failed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("EventProcessor: state 'Failed' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"reason"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("EventProcessor: state 'Failed' is missing required field %q", field)
			}
		}
		data := &EventProcessorFailedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = EventProcessorStateFailed
		m.FailedData = data
	default:
		return fmt.Errorf("EventProcessor: unknown state %q", envelope.State)
	}
	return nil
}

func NewEventProcessor() *EventProcessor {
	return &EventProcessor{
		State: EventProcessorStateIdle,
	}
}

type EventProcessorError struct {
	Transition string
	From      string
	Message   string
}

func (e *EventProcessorError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *EventProcessor) Receive(incoming Event) error {
	if m.State != EventProcessorStateIdle {
		return &EventProcessorError{Transition: "receive", From: m.State.String()}
	}

	m.State = EventProcessorStateReceiving
	m.clearStateData()
	m.ReceivingData = &EventProcessorReceivingData{
		Event: incoming,
	}

	return nil
}

func (m *EventProcessor) Validate(effects EventProcessorEffects) error {
	if m.State != EventProcessorStateReceiving {
		return &EventProcessorError{Transition: "validate", From: m.State.String()}
	}

	effects.ValidateEvent(m.ReceivingData.Event)
	if m.ReceivingData.Event.Priority > 0 {
		var __goto_validating_event Event = m.ReceivingData.Event
		m.State = EventProcessorStateValidating
		m.clearStateData()
		m.ValidatingData = &EventProcessorValidatingData{
			Event: __goto_validating_event,
		}
	} else {
		m.State = EventProcessorStateFailed
		m.clearStateData()
		m.FailedData = &EventProcessorFailedData{
			Reason: "event priority must be positive",
		}
	}

	return nil
}

func (m *EventProcessor) Process(effects EventProcessorEffects) error {
	if m.State != EventProcessorStateValidating {
		return &EventProcessorError{Transition: "process", From: m.State.String()}
	}

	result := effects.ProcessEvent(m.ValidatingData.Event)
	m.State = EventProcessorStateCompleted
	m.clearStateData()
	m.CompletedData = &EventProcessorCompletedData{
		Result: result,
	}

	return nil
}

func (m *EventProcessor) Reset() error {
	if m.State != EventProcessorStateCompleted {
		return &EventProcessorError{Transition: "reset", From: m.State.String()}
	}

	m.State = EventProcessorStateIdle
	m.clearStateData()

	return nil
}

func (m *EventProcessor) Retry() error {
	if m.State != EventProcessorStateFailed {
		return &EventProcessorError{Transition: "retry", From: m.State.String()}
	}

	m.State = EventProcessorStateIdle
	m.clearStateData()

	return nil
}

func (m *EventProcessor) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func EventProcessorFromJSON(data []byte) (*EventProcessor, error) {
	var m EventProcessor
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
