// Code generated by Gust compiler — DO NOT EDIT.

package rate_limiter

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type RateLimiterState int

const (
	RateLimiterStateAvailable = iota
	RateLimiterStateExhausted
)

func (s RateLimiterState) String() string {
	switch s {
	case RateLimiterStateAvailable:
		return "Available"
	case RateLimiterStateExhausted:
		return "Exhausted"
	default:
		return "Unknown"
	}
}

type RateLimiterAvailableData struct {
	Tokens int64 `json:"tokens"`
	MaxTokens int64 `json:"max_tokens"`
}

type RateLimiterExhaustedData struct {
	RetryAfterMs int64 `json:"retry_after_ms"`
	MaxTokens int64 `json:"max_tokens"`
}

type RateLimiterEffects interface {
	// gust:effect -- replay-safe / idempotent
	NowMs() int64
}

type RateLimiter struct {
	State RateLimiterState
	AvailableData *RateLimiterAvailableData
	ExhaustedData *RateLimiterExhaustedData
}

func (m *RateLimiter) clearStateData() {
	m.AvailableData = nil
	m.ExhaustedData = nil
}

func (m RateLimiter) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case RateLimiterStateAvailable:
		if m.AvailableData != nil {
			envelope.Data = m.AvailableData
		}
	case RateLimiterStateExhausted:
		if m.ExhaustedData != nil {
			envelope.Data = m.ExhaustedData
		}
	default:
		return nil, fmt.Errorf("RateLimiter: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *RateLimiter) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Available":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RateLimiter: state 'Available' requires a data payload")
		}
		data := &RateLimiterAvailableData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RateLimiterStateAvailable
		m.AvailableData = data
	case "Exhausted":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RateLimiter: state 'Exhausted' requires a data payload")
		}
		data := &RateLimiterExhaustedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RateLimiterStateExhausted
		m.ExhaustedData = data
	default:
		return fmt.Errorf("RateLimiter: unknown state %q", envelope.State)
	}
	return nil
}

func NewRateLimiter(tokens int64, max_tokens int64) *RateLimiter {
	return &RateLimiter{
		State: RateLimiterStateAvailable,
		AvailableData: &RateLimiterAvailableData{
			Tokens: tokens,
			MaxTokens: max_tokens,
		},
	}
}

type RateLimiterError struct {
	Transition string
	From      string
	Message   string
}

func (e *RateLimiterError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *RateLimiter) Acquire(effects RateLimiterEffects) error {
	if m.State != RateLimiterStateAvailable {
		return &RateLimiterError{Transition: "acquire", From: m.State.String()}
	}

	tokens := m.AvailableData.Tokens
	max_tokens := m.AvailableData.MaxTokens

	if tokens > 0 {
		m.State = RateLimiterStateAvailable
		m.clearStateData()
		m.AvailableData = &RateLimiterAvailableData{
			Tokens: (tokens - 1),
			MaxTokens: max_tokens,
		}
	} else {
		m.State = RateLimiterStateExhausted
		m.clearStateData()
		m.ExhaustedData = &RateLimiterExhaustedData{
			RetryAfterMs: effects.NowMs(),
			MaxTokens: max_tokens,
		}
	}

	return nil
}

func (m *RateLimiter) Refill() error {
	if m.State != RateLimiterStateExhausted {
		return &RateLimiterError{Transition: "refill", From: m.State.String()}
	}

	max_tokens := m.ExhaustedData.MaxTokens

	m.State = RateLimiterStateAvailable
	m.clearStateData()
	m.AvailableData = &RateLimiterAvailableData{
		Tokens: max_tokens,
		MaxTokens: max_tokens,
	}

	return nil
}

func (m *RateLimiter) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func RateLimiterFromJSON(data []byte) (*RateLimiter, error) {
	var m RateLimiter
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
