// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RateLimiterState {
    Available {
        tokens: i64,
        max_tokens: i64,
    },
    Exhausted {
        retry_after_ms: i64,
        max_tokens: i64,
    },
}

pub trait RateLimiterEffects {
    /// gust:effect -- replay-safe / idempotent
    fn now_ms(&self) -> i64;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RateLimiter {
    pub state: RateLimiterState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum RateLimiterError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl RateLimiter {
    pub fn new(tokens: i64, max_tokens: i64) -> Self {
        Self { state: RateLimiterState::Available { tokens, max_tokens } }
    }

    pub fn state(&self) -> &RateLimiterState {
        &self.state
    }

    pub fn acquire(&mut self, effects: &impl RateLimiterEffects) -> Result<(), RateLimiterError> {
        match &self.state {
            RateLimiterState::Available { tokens, max_tokens } => {
                let tokens = *tokens;
                let max_tokens = *max_tokens;
                if tokens > 0 {
                    let __goto_available_tokens = tokens - 1;
                    self.state = RateLimiterState::Available { tokens: __goto_available_tokens, max_tokens };
                    Ok(())
                } else {
                    let __goto_exhausted_retry_after_ms = effects.now_ms();
                    self.state = RateLimiterState::Exhausted { retry_after_ms: __goto_exhausted_retry_after_ms, max_tokens };
                    Ok(())
                }
            }
            _ => Err(RateLimiterError::InvalidTransition {
                transition: "acquire".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn refill(&mut self) -> Result<(), RateLimiterError> {
        match &self.state {
            RateLimiterState::Exhausted { retry_after_ms: _retry_after_ms, max_tokens } => {
                let max_tokens = *max_tokens;
                self.state = RateLimiterState::Available { tokens: max_tokens, max_tokens };
                Ok(())
            }
            _ => Err(RateLimiterError::InvalidTransition {
                transition: "refill".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
