// Code generated by Gust compiler — DO NOT EDIT.

package regressions

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type SupervisionStrategy string

const (
	OneForOne SupervisionStrategy = "one_for_one"
	OneForAll SupervisionStrategy = "one_for_all"
	RestForOne SupervisionStrategy = "rest_for_one"
)

type SupervisionSpec struct {
	Child string
	Strategy SupervisionStrategy
}

type SupervisorRuntime interface {
	SpawnNamed(name string, fn func() error) error
}

type Config struct {
	Service string `json:"service"`
	Retries int64 `json:"retries"`
}

type Tier string

const (
	TierFast Tier = "Fast"
	TierSlow Tier = "Slow"
)

type BranchingGotoState int

const (
	BranchingGotoStatePending = iota
	BranchingGotoStateAccepted
	BranchingGotoStateRejected
)

func (s BranchingGotoState) String() string {
	switch s {
	case BranchingGotoStatePending:
		return "Pending"
	case BranchingGotoStateAccepted:
		return "Accepted"
	case BranchingGotoStateRejected:
		return "Rejected"
	default:
		return "Unknown"
	}
}

type BranchingGotoPendingData struct {
	Cfg Config `json:"cfg"`
	Attempt int64 `json:"attempt"`
}

type BranchingGotoAcceptedData struct {
	Cfg Config `json:"cfg"`
}

type BranchingGotoRejectedData struct {
	Reason string `json:"reason"`
}

type BranchingGotoEffects interface {
	// gust:effect -- replay-safe / idempotent
	Approve(service string) bool
}

type BranchingGoto struct {
	State BranchingGotoState `json:"state"`
	PendingData *BranchingGotoPendingData `json:"pending_data,omitempty"`
	AcceptedData *BranchingGotoAcceptedData `json:"accepted_data,omitempty"`
	RejectedData *BranchingGotoRejectedData `json:"rejected_data,omitempty"`
}

func (m *BranchingGoto) clearStateData() {
	m.PendingData = nil
	m.AcceptedData = nil
	m.RejectedData = nil
}

func NewBranchingGoto(cfg Config, attempt int64) *BranchingGoto {
	return &BranchingGoto{
		State: BranchingGotoStatePending,
		PendingData: &BranchingGotoPendingData{
			Cfg: cfg,
			Attempt: attempt,
		},
	}
}

type BranchingGotoError struct {
	Transition string
	From      string
	Message   string
}

func (e *BranchingGotoError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BranchingGoto) Decide(effects BranchingGotoEffects) error {
	if m.State != BranchingGotoStatePending {
		return &BranchingGotoError{Transition: "decide", From: m.State.String()}
	}

	ok := effects.Approve(m.PendingData.Cfg.Service)
	if ok {
		var __goto_accepted_cfg Config = m.PendingData.Cfg
		m.State = BranchingGotoStateAccepted
		m.clearStateData()
		m.AcceptedData = &BranchingGotoAcceptedData{
			Cfg: __goto_accepted_cfg,
		}
		return nil
	}
	m.State = BranchingGotoStateRejected
	m.clearStateData()
	m.RejectedData = &BranchingGotoRejectedData{
		Reason: "declined",
	}

	return nil
}

func (m *BranchingGoto) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BranchingGotoFromJSON(data []byte) (*BranchingGoto, error) {
	var m BranchingGoto
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BranchingGotoWithElseState int

const (
	BranchingGotoWithElseStateStart = iota
	BranchingGotoWithElseStateBig
	BranchingGotoWithElseStateSmall
)

func (s BranchingGotoWithElseState) String() string {
	switch s {
	case BranchingGotoWithElseStateStart:
		return "Start"
	case BranchingGotoWithElseStateBig:
		return "Big"
	case BranchingGotoWithElseStateSmall:
		return "Small"
	default:
		return "Unknown"
	}
}

type BranchingGotoWithElseStartData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElseBigData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElseSmallData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElse struct {
	State BranchingGotoWithElseState `json:"state"`
	StartData *BranchingGotoWithElseStartData `json:"start_data,omitempty"`
	BigData *BranchingGotoWithElseBigData `json:"big_data,omitempty"`
	SmallData *BranchingGotoWithElseSmallData `json:"small_data,omitempty"`
}

func (m *BranchingGotoWithElse) clearStateData() {
	m.StartData = nil
	m.BigData = nil
	m.SmallData = nil
}

func NewBranchingGotoWithElse(n int64) *BranchingGotoWithElse {
	return &BranchingGotoWithElse{
		State: BranchingGotoWithElseStateStart,
		StartData: &BranchingGotoWithElseStartData{
			N: n,
		},
	}
}

type BranchingGotoWithElseError struct {
	Transition string
	From      string
	Message   string
}

func (e *BranchingGotoWithElseError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BranchingGotoWithElse) Split() error {
	if m.State != BranchingGotoWithElseStateStart {
		return &BranchingGotoWithElseError{Transition: "split", From: m.State.String()}
	}

	if m.StartData.N > 10 {
		var __goto_big_n int64 = m.StartData.N
		m.State = BranchingGotoWithElseStateBig
		m.clearStateData()
		m.BigData = &BranchingGotoWithElseBigData{
			N: __goto_big_n,
		}
	} else {
		var __goto_small_n int64 = m.StartData.N
		m.State = BranchingGotoWithElseStateSmall
		m.clearStateData()
		m.SmallData = &BranchingGotoWithElseSmallData{
			N: __goto_small_n,
		}
	}

	return nil
}

func (m *BranchingGotoWithElse) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BranchingGotoWithElseFromJSON(data []byte) (*BranchingGotoWithElse, error) {
	var m BranchingGotoWithElse
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type WorkerState int

const (
	WorkerStateWaiting = iota
	WorkerStateBusy
)

func (s WorkerState) String() string {
	switch s {
	case WorkerStateWaiting:
		return "Waiting"
	case WorkerStateBusy:
		return "Busy"
	default:
		return "Unknown"
	}
}

type WorkerWaitingData struct {
	Job string `json:"job"`
}

type WorkerBusyData struct {
	Job string `json:"job"`
}

type Worker struct {
	State WorkerState `json:"state"`
	WaitingData *WorkerWaitingData `json:"waiting_data,omitempty"`
	BusyData *WorkerBusyData `json:"busy_data,omitempty"`
}

func (m *Worker) clearStateData() {
	m.WaitingData = nil
	m.BusyData = nil
}

func NewWorker(job string) *Worker {
	return &Worker{
		State: WorkerStateWaiting,
		WaitingData: &WorkerWaitingData{
			Job: job,
		},
	}
}

type WorkerError struct {
	Transition string
	From      string
	Message   string
}

func (e *WorkerError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Worker) Start() error {
	if m.State != WorkerStateWaiting {
		return &WorkerError{Transition: "start", From: m.State.String()}
	}

	var __goto_busy_job string = m.WaitingData.Job
	m.State = WorkerStateBusy
	m.clearStateData()
	m.BusyData = &WorkerBusyData{
		Job: __goto_busy_job,
	}

	return nil
}

func (m *Worker) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func WorkerFromJSON(data []byte) (*Worker, error) {
	var m Worker
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BossState int

const (
	BossStateIdle = iota
	BossStateRunning
)

func (s BossState) String() string {
	switch s {
	case BossStateIdle:
		return "Idle"
	case BossStateRunning:
		return "Running"
	default:
		return "Unknown"
	}
}

type BossIdleData struct {
	Job string `json:"job"`
}

type BossRunningData struct {
	Current string `json:"current"`
}

type Boss struct {
	State BossState `json:"state"`
	IdleData *BossIdleData `json:"idle_data,omitempty"`
	RunningData *BossRunningData `json:"running_data,omitempty"`
}

func (m *Boss) clearStateData() {
	m.IdleData = nil
	m.RunningData = nil
}

func NewBoss(job string) *Boss {
	return &Boss{
		State: BossStateIdle,
		IdleData: &BossIdleData{
			Job: job,
		},
	}
}

// BossChildren supplies a runner for each child Boss supervises.
type BossChildren interface {
	// RunWorker drives a supervised Worker to completion. A non-nil
	// error marks the child failed, which is what the restart
	// strategy acts on.
	RunWorker(child *Worker) error
}

var BossSupervision = []SupervisionSpec{
	{Child: "Worker", Strategy: OneForOne},
}

type BossError struct {
	Transition string
	From      string
	Message   string
}

func (e *BossError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Boss) Begin(supervisor SupervisorRuntime, children BossChildren) error {
	if m.State != BossStateIdle {
		return &BossError{Transition: "begin", From: m.State.String()}
	}

	if err := supervisor.SpawnNamed("Worker", func() error {
		return children.RunWorker(NewWorker(m.IdleData.Job))
	}); err != nil {
		return err
	}
	var __goto_running_current string = m.IdleData.Job
	m.State = BossStateRunning
	m.clearStateData()
	m.RunningData = &BossRunningData{
		Current: __goto_running_current,
	}

	return nil
}

func (m *Boss) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BossFromJSON(data []byte) (*Boss, error) {
	var m Boss
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type ResultMatchingState int

const (
	ResultMatchingStateIdle = iota
	ResultMatchingStateOk2
	ResultMatchingStateFailed
)

func (s ResultMatchingState) String() string {
	switch s {
	case ResultMatchingStateIdle:
		return "Idle"
	case ResultMatchingStateOk2:
		return "Ok2"
	case ResultMatchingStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type ResultMatchingIdleData struct {
	Id string `json:"id"`
}

type ResultMatchingOk2Data struct {
	Token string `json:"token"`
}

type ResultMatchingFailedData struct {
	Why string `json:"why"`
}

type ResultMatchingEffects interface {
	// gust:effect -- replay-safe / idempotent
	Lookup(ctx context.Context, id string) (string, error)
}

type ResultMatching struct {
	State ResultMatchingState `json:"state"`
	IdleData *ResultMatchingIdleData `json:"idle_data,omitempty"`
	Ok2Data *ResultMatchingOk2Data `json:"ok2_data,omitempty"`
	FailedData *ResultMatchingFailedData `json:"failed_data,omitempty"`
}

func (m *ResultMatching) clearStateData() {
	m.IdleData = nil
	m.Ok2Data = nil
	m.FailedData = nil
}

func NewResultMatching(id string) *ResultMatching {
	return &ResultMatching{
		State: ResultMatchingStateIdle,
		IdleData: &ResultMatchingIdleData{
			Id: id,
		},
	}
}

type ResultMatchingError struct {
	Transition string
	From      string
	Message   string
}

func (e *ResultMatchingError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *ResultMatching) Fetch(ctx context.Context, effects ResultMatchingEffects) error {
	if m.State != ResultMatchingStateIdle {
		return &ResultMatchingError{Transition: "fetch", From: m.State.String()}
	}

	r, __r_err := effects.Lookup(ctx, m.IdleData.Id)
	if __r_err == nil {
		token := r
		m.State = ResultMatchingStateOk2
		m.clearStateData()
		m.Ok2Data = &ResultMatchingOk2Data{
			Token: token,
		}
	} else {
		e := __r_err.Error()
		m.State = ResultMatchingStateFailed
		m.clearStateData()
		m.FailedData = &ResultMatchingFailedData{
			Why: e,
		}
	}

	return nil
}

func (m *ResultMatching) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func ResultMatchingFromJSON(data []byte) (*ResultMatching, error) {
	var m ResultMatching
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type HolderState[T any] int

const (
	HolderStateEmpty = iota
	HolderStateFull
)

func (s HolderState[T]) String() string {
	switch s {
	case HolderStateEmpty:
		return "Empty"
	case HolderStateFull:
		return "Full"
	default:
		return "Unknown"
	}
}

type HolderFullData[T any] struct {
	Value T `json:"value"`
}

type Holder[T any] struct {
	State HolderState[T] `json:"state"`
	FullData *HolderFullData[T] `json:"full_data,omitempty"`
}

func (m *Holder[T]) clearStateData() {
	m.FullData = nil
}

func NewHolder[T any]() *Holder[T] {
	return &Holder[T]{
		State: HolderStateEmpty,
	}
}

type HolderError struct {
	Transition string
	From      string
	Message   string
}

func (e *HolderError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Holder[T]) Put(value T) error {
	if m.State != HolderStateEmpty {
		return &HolderError{Transition: "put", From: m.State.String()}
	}

	m.State = HolderStateFull
	m.clearStateData()
	m.FullData = &HolderFullData[T]{
		Value: value,
	}

	return nil
}

func (m *Holder[T]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func HolderFromJSON[T any](data []byte) (*Holder[T], error) {
	var m Holder[T]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BareFieldReadsState int

const (
	BareFieldReadsStateConfigured = iota
	BareFieldReadsStateLive
)

func (s BareFieldReadsState) String() string {
	switch s {
	case BareFieldReadsStateConfigured:
		return "Configured"
	case BareFieldReadsStateLive:
		return "Live"
	default:
		return "Unknown"
	}
}

type BareFieldReadsConfiguredData struct {
	Service string `json:"service"`
	Tier Tier `json:"tier"`
}

type BareFieldReadsLiveData struct {
	Service string `json:"service"`
}

type BareFieldReadsEffects interface {
	// gust:effect -- replay-safe / idempotent
	Announce(name string)
}

type BareFieldReads struct {
	State BareFieldReadsState `json:"state"`
	ConfiguredData *BareFieldReadsConfiguredData `json:"configured_data,omitempty"`
	LiveData *BareFieldReadsLiveData `json:"live_data,omitempty"`
}

func (m *BareFieldReads) clearStateData() {
	m.ConfiguredData = nil
	m.LiveData = nil
}

func NewBareFieldReads(service string, tier Tier) *BareFieldReads {
	return &BareFieldReads{
		State: BareFieldReadsStateConfigured,
		ConfiguredData: &BareFieldReadsConfiguredData{
			Service: service,
			Tier: tier,
		},
	}
}

type BareFieldReadsError struct {
	Transition string
	From      string
	Message   string
}

func (e *BareFieldReadsError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BareFieldReads) Launch(effects BareFieldReadsEffects) error {
	if m.State != BareFieldReadsStateConfigured {
		return &BareFieldReadsError{Transition: "launch", From: m.State.String()}
	}

	service := m.ConfiguredData.Service

	effects.Announce(service)
	var __goto_live_service string = m.ConfiguredData.Service
	m.State = BareFieldReadsStateLive
	m.clearStateData()
	m.LiveData = &BareFieldReadsLiveData{
		Service: __goto_live_service,
	}

	return nil
}

func (m *BareFieldReads) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BareFieldReadsFromJSON(data []byte) (*BareFieldReads, error) {
	var m BareFieldReads
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
