// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub service: String,
    pub retries: i64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum Tier {
    Fast,
    Slow,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BranchingGotoState {
    Pending {
        cfg: Config,
        attempt: i64,
    },
    Accepted {
        cfg: Config,
    },
    Rejected {
        reason: String,
    },
}

pub trait BranchingGotoEffects {
    /// gust:effect -- replay-safe / idempotent
    fn approve(&self, service: &str) -> bool;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchingGoto {
    pub state: BranchingGotoState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum BranchingGotoError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl BranchingGoto {
    pub fn new(cfg: Config, attempt: i64) -> Self {
        Self { state: BranchingGotoState::Pending { cfg, attempt } }
    }

    pub fn state(&self) -> &BranchingGotoState {
        &self.state
    }

    pub fn decide(&mut self, effects: &impl BranchingGotoEffects) -> Result<(), BranchingGotoError> {
        match &self.state {
            BranchingGotoState::Pending { cfg, attempt: _attempt } => {
                let cfg = cfg.clone();
                let ok = effects.approve(&cfg.service);
                if ok {
                    self.state = BranchingGotoState::Accepted { cfg };
                    return Ok(());
                }
                let __goto_rejected_reason = "declined".to_string();
                self.state = BranchingGotoState::Rejected { reason: __goto_rejected_reason };
                Ok(())
            }
            _ => Err(BranchingGotoError::InvalidTransition {
                transition: "decide".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BranchingGotoWithElseState {
    Start {
        n: i64,
    },
    Big {
        n: i64,
    },
    Small {
        n: i64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchingGotoWithElse {
    pub state: BranchingGotoWithElseState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum BranchingGotoWithElseError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl BranchingGotoWithElse {
    pub fn new(n: i64) -> Self {
        Self { state: BranchingGotoWithElseState::Start { n } }
    }

    pub fn state(&self) -> &BranchingGotoWithElseState {
        &self.state
    }

    pub fn split(&mut self) -> Result<(), BranchingGotoWithElseError> {
        match &self.state {
            BranchingGotoWithElseState::Start { n } => {
                let n = *n;
                if n > 10 {
                    self.state = BranchingGotoWithElseState::Big { n };
                    Ok(())
                } else {
                    self.state = BranchingGotoWithElseState::Small { n };
                    Ok(())
                }
            }
            _ => Err(BranchingGotoWithElseError::InvalidTransition {
                transition: "split".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorkerState {
    Waiting {
        job: String,
    },
    Busy {
        job: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Worker {
    pub state: WorkerState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum WorkerError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl Worker {
    pub fn new(job: String) -> Self {
        Self { state: WorkerState::Waiting { job } }
    }

    pub fn state(&self) -> &WorkerState {
        &self.state
    }

    pub fn start(&mut self) -> Result<(), WorkerError> {
        match &self.state {
            WorkerState::Waiting { job } => {
                let job = job.clone();
                self.state = WorkerState::Busy { job };
                Ok(())
            }
            _ => Err(WorkerError::InvalidTransition {
                transition: "start".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BossState {
    Idle {
        job: String,
    },
    Running {
        current: String,
    },
}

/// Host-supplied runners for the children `Boss` supervises.
pub trait BossSupervision {
    /// Drives a supervised `Worker` to completion. Returning `Err`
    /// marks the child failed, which is what the runtime's
    /// restart strategy acts on.
    fn run_worker(&self, child: Worker) -> ::core::pin::Pin<::std::boxed::Box<dyn ::core::future::Future<Output = Result<(), String>> + Send>>;
}

/// Restart policy per supervised child of `Boss`.
pub const BOSS_SUPERVISION: &[(&str, gust_runtime::prelude::RestartStrategy)] = &[
    ("Worker", gust_runtime::prelude::RestartStrategy::OneForOne),
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Boss {
    pub state: BossState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum BossError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl Boss {
    pub fn new(job: String) -> Self {
        Self { state: BossState::Idle { job } }
    }

    pub fn state(&self) -> &BossState {
        &self.state
    }

    pub fn begin(&mut self, supervisor: &gust_runtime::prelude::SupervisorRuntime, children: &impl BossSupervision) -> Result<(), BossError> {
        match &self.state {
            BossState::Idle { job } => {
                let job = job.clone();
                let _child = supervisor.spawn_named("Worker", children.run_worker(Worker::new(job.clone())));
                self.state = BossState::Running { current: job };
                Ok(())
            }
            _ => Err(BossError::InvalidTransition {
                transition: "begin".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ResultMatchingState {
    Idle {
        id: String,
    },
    Ok2 {
        token: String,
    },
    Failed {
        why: String,
    },
}

pub trait ResultMatchingEffects {
    /// gust:effect -- replay-safe / idempotent
    fn lookup(&self, id: &str) -> impl ::core::future::Future<Output = Result<String, String>> + Send;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResultMatching {
    pub state: ResultMatchingState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum ResultMatchingError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl ResultMatching {
    pub fn new(id: String) -> Self {
        Self { state: ResultMatchingState::Idle { id } }
    }

    pub fn state(&self) -> &ResultMatchingState {
        &self.state
    }

    pub async fn fetch(&mut self, effects: &impl ResultMatchingEffects) -> Result<(), ResultMatchingError> {
        match &self.state {
            ResultMatchingState::Idle { id } => {
                let id = id.clone();
                let r = effects.lookup(&id).await;
                match r {
                    Ok(token) => {
                        self.state = ResultMatchingState::Ok2 { token };
                        Ok(())
                    }
                    Err(e) => {
                        self.state = ResultMatchingState::Failed { why: e };
                        Ok(())
                    }
                }
            }
            _ => Err(ResultMatchingError::InvalidTransition {
                transition: "fetch".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HolderState<T: Clone> {
    Empty,
    Full {
        value: T,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Holder<T: Clone> {
    pub state: HolderState<T>,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum HolderError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl<T: Clone + core::fmt::Debug> Holder<T> {
    pub fn new() -> Self {
        Self { state: HolderState::Empty }
    }

    pub fn state(&self) -> &HolderState<T> {
        &self.state
    }

    pub fn put(&mut self, value: T) -> Result<(), HolderError> {
        match &self.state {
            HolderState::Empty => {
                self.state = HolderState::Full { value };
                Ok(())
            }
            _ => Err(HolderError::InvalidTransition {
                transition: "put".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

impl<T: Clone + core::fmt::Debug> Default for Holder<T> {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BareFieldReadsState {
    Configured {
        service: String,
        tier: Tier,
    },
    Live {
        service: String,
    },
}

pub trait BareFieldReadsEffects {
    /// gust:effect -- replay-safe / idempotent
    fn announce(&self, name: &str);
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BareFieldReads {
    pub state: BareFieldReadsState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum BareFieldReadsError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl BareFieldReads {
    pub fn new(service: String, tier: Tier) -> Self {
        Self { state: BareFieldReadsState::Configured { service, tier } }
    }

    pub fn state(&self) -> &BareFieldReadsState {
        &self.state
    }

    pub fn launch(&mut self, effects: &impl BareFieldReadsEffects) -> Result<(), BareFieldReadsError> {
        match &self.state {
            BareFieldReadsState::Configured { service, tier: _tier } => {
                let service = service.clone();
                effects.announce(&service);
                self.state = BareFieldReadsState::Live { service };
                Ok(())
            }
            _ => Err(BareFieldReadsError::InvalidTransition {
                transition: "launch".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
