// Code generated by Gust compiler — DO NOT EDIT.

package regressions

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type SupervisionStrategy string

const (
	OneForOne SupervisionStrategy = "one_for_one"
	OneForAll SupervisionStrategy = "one_for_all"
	RestForOne SupervisionStrategy = "rest_for_one"
)

type SupervisionSpec struct {
	Child string
	Strategy SupervisionStrategy
}

type SupervisorRuntime interface {
	SpawnNamed(name string, fn func() error) error
}

type Config struct {
	Service string `json:"service"`
	Retries int64 `json:"retries"`
}

type Tier string

const (
	TierFast Tier = "Fast"
	TierSlow Tier = "Slow"
)

type BranchingGotoState int

const (
	BranchingGotoStatePending = iota
	BranchingGotoStateAccepted
	BranchingGotoStateRejected
)

func (s BranchingGotoState) String() string {
	switch s {
	case BranchingGotoStatePending:
		return "Pending"
	case BranchingGotoStateAccepted:
		return "Accepted"
	case BranchingGotoStateRejected:
		return "Rejected"
	default:
		return "Unknown"
	}
}

type BranchingGotoPendingData struct {
	Cfg Config `json:"cfg"`
	Attempt int64 `json:"attempt"`
}

type BranchingGotoAcceptedData struct {
	Cfg Config `json:"cfg"`
}

type BranchingGotoRejectedData struct {
	Reason string `json:"reason"`
}

type BranchingGotoEffects interface {
	// gust:effect -- replay-safe / idempotent
	Approve(service string) bool
}

type BranchingGoto struct {
	State BranchingGotoState
	PendingData *BranchingGotoPendingData
	AcceptedData *BranchingGotoAcceptedData
	RejectedData *BranchingGotoRejectedData
}

func (m *BranchingGoto) clearStateData() {
	m.PendingData = nil
	m.AcceptedData = nil
	m.RejectedData = nil
}

func (m BranchingGoto) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case BranchingGotoStatePending:
		if m.PendingData != nil {
			envelope.Data = m.PendingData
		}
	case BranchingGotoStateAccepted:
		if m.AcceptedData != nil {
			envelope.Data = m.AcceptedData
		}
	case BranchingGotoStateRejected:
		if m.RejectedData != nil {
			envelope.Data = m.RejectedData
		}
	default:
		return nil, fmt.Errorf("BranchingGoto: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *BranchingGoto) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Pending":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGoto: state 'Pending' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"cfg", "attempt"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGoto: state 'Pending' is missing required field %q", field)
			}
		}
		data := &BranchingGotoPendingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoStatePending
		m.PendingData = data
	case "Accepted":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGoto: state 'Accepted' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"cfg"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGoto: state 'Accepted' is missing required field %q", field)
			}
		}
		data := &BranchingGotoAcceptedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoStateAccepted
		m.AcceptedData = data
	case "Rejected":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGoto: state 'Rejected' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"reason"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGoto: state 'Rejected' is missing required field %q", field)
			}
		}
		data := &BranchingGotoRejectedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoStateRejected
		m.RejectedData = data
	default:
		return fmt.Errorf("BranchingGoto: unknown state %q", envelope.State)
	}
	return nil
}

func NewBranchingGoto(cfg Config, attempt int64) *BranchingGoto {
	return &BranchingGoto{
		State: BranchingGotoStatePending,
		PendingData: &BranchingGotoPendingData{
			Cfg: cfg,
			Attempt: attempt,
		},
	}
}

type BranchingGotoError struct {
	Transition string
	From      string
	Message   string
}

func (e *BranchingGotoError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BranchingGoto) Decide(effects BranchingGotoEffects) error {
	if m.State != BranchingGotoStatePending {
		return &BranchingGotoError{Transition: "decide", From: m.State.String()}
	}

	ok := effects.Approve(m.PendingData.Cfg.Service)
	if ok {
		var __goto_accepted_cfg Config = m.PendingData.Cfg
		m.State = BranchingGotoStateAccepted
		m.clearStateData()
		m.AcceptedData = &BranchingGotoAcceptedData{
			Cfg: __goto_accepted_cfg,
		}
		return nil
	}
	m.State = BranchingGotoStateRejected
	m.clearStateData()
	m.RejectedData = &BranchingGotoRejectedData{
		Reason: "declined",
	}

	return nil
}

func (m *BranchingGoto) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BranchingGotoFromJSON(data []byte) (*BranchingGoto, error) {
	var m BranchingGoto
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BranchingGotoWithElseState int

const (
	BranchingGotoWithElseStateStart = iota
	BranchingGotoWithElseStateBig
	BranchingGotoWithElseStateSmall
)

func (s BranchingGotoWithElseState) String() string {
	switch s {
	case BranchingGotoWithElseStateStart:
		return "Start"
	case BranchingGotoWithElseStateBig:
		return "Big"
	case BranchingGotoWithElseStateSmall:
		return "Small"
	default:
		return "Unknown"
	}
}

type BranchingGotoWithElseStartData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElseBigData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElseSmallData struct {
	N int64 `json:"n"`
}

type BranchingGotoWithElse struct {
	State BranchingGotoWithElseState
	StartData *BranchingGotoWithElseStartData
	BigData *BranchingGotoWithElseBigData
	SmallData *BranchingGotoWithElseSmallData
}

func (m *BranchingGotoWithElse) clearStateData() {
	m.StartData = nil
	m.BigData = nil
	m.SmallData = nil
}

func (m BranchingGotoWithElse) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case BranchingGotoWithElseStateStart:
		if m.StartData != nil {
			envelope.Data = m.StartData
		}
	case BranchingGotoWithElseStateBig:
		if m.BigData != nil {
			envelope.Data = m.BigData
		}
	case BranchingGotoWithElseStateSmall:
		if m.SmallData != nil {
			envelope.Data = m.SmallData
		}
	default:
		return nil, fmt.Errorf("BranchingGotoWithElse: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *BranchingGotoWithElse) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Start":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGotoWithElse: state 'Start' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"n"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGotoWithElse: state 'Start' is missing required field %q", field)
			}
		}
		data := &BranchingGotoWithElseStartData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoWithElseStateStart
		m.StartData = data
	case "Big":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGotoWithElse: state 'Big' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"n"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGotoWithElse: state 'Big' is missing required field %q", field)
			}
		}
		data := &BranchingGotoWithElseBigData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoWithElseStateBig
		m.BigData = data
	case "Small":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BranchingGotoWithElse: state 'Small' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"n"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BranchingGotoWithElse: state 'Small' is missing required field %q", field)
			}
		}
		data := &BranchingGotoWithElseSmallData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BranchingGotoWithElseStateSmall
		m.SmallData = data
	default:
		return fmt.Errorf("BranchingGotoWithElse: unknown state %q", envelope.State)
	}
	return nil
}

func NewBranchingGotoWithElse(n int64) *BranchingGotoWithElse {
	return &BranchingGotoWithElse{
		State: BranchingGotoWithElseStateStart,
		StartData: &BranchingGotoWithElseStartData{
			N: n,
		},
	}
}

type BranchingGotoWithElseError struct {
	Transition string
	From      string
	Message   string
}

func (e *BranchingGotoWithElseError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BranchingGotoWithElse) Split() error {
	if m.State != BranchingGotoWithElseStateStart {
		return &BranchingGotoWithElseError{Transition: "split", From: m.State.String()}
	}

	if m.StartData.N > 10 {
		var __goto_big_n int64 = m.StartData.N
		m.State = BranchingGotoWithElseStateBig
		m.clearStateData()
		m.BigData = &BranchingGotoWithElseBigData{
			N: __goto_big_n,
		}
	} else {
		var __goto_small_n int64 = m.StartData.N
		m.State = BranchingGotoWithElseStateSmall
		m.clearStateData()
		m.SmallData = &BranchingGotoWithElseSmallData{
			N: __goto_small_n,
		}
	}

	return nil
}

func (m *BranchingGotoWithElse) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BranchingGotoWithElseFromJSON(data []byte) (*BranchingGotoWithElse, error) {
	var m BranchingGotoWithElse
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type WorkerState int

const (
	WorkerStateWaiting = iota
	WorkerStateBusy
)

func (s WorkerState) String() string {
	switch s {
	case WorkerStateWaiting:
		return "Waiting"
	case WorkerStateBusy:
		return "Busy"
	default:
		return "Unknown"
	}
}

type WorkerWaitingData struct {
	Job string `json:"job"`
}

type WorkerBusyData struct {
	Job string `json:"job"`
}

type Worker struct {
	State WorkerState
	WaitingData *WorkerWaitingData
	BusyData *WorkerBusyData
}

func (m *Worker) clearStateData() {
	m.WaitingData = nil
	m.BusyData = nil
}

func (m Worker) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case WorkerStateWaiting:
		if m.WaitingData != nil {
			envelope.Data = m.WaitingData
		}
	case WorkerStateBusy:
		if m.BusyData != nil {
			envelope.Data = m.BusyData
		}
	default:
		return nil, fmt.Errorf("Worker: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *Worker) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Waiting":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Worker: state 'Waiting' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"job"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("Worker: state 'Waiting' is missing required field %q", field)
			}
		}
		data := &WorkerWaitingData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = WorkerStateWaiting
		m.WaitingData = data
	case "Busy":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Worker: state 'Busy' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"job"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("Worker: state 'Busy' is missing required field %q", field)
			}
		}
		data := &WorkerBusyData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = WorkerStateBusy
		m.BusyData = data
	default:
		return fmt.Errorf("Worker: unknown state %q", envelope.State)
	}
	return nil
}

func NewWorker(job string) *Worker {
	return &Worker{
		State: WorkerStateWaiting,
		WaitingData: &WorkerWaitingData{
			Job: job,
		},
	}
}

type WorkerError struct {
	Transition string
	From      string
	Message   string
}

func (e *WorkerError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Worker) Start() error {
	if m.State != WorkerStateWaiting {
		return &WorkerError{Transition: "start", From: m.State.String()}
	}

	var __goto_busy_job string = m.WaitingData.Job
	m.State = WorkerStateBusy
	m.clearStateData()
	m.BusyData = &WorkerBusyData{
		Job: __goto_busy_job,
	}

	return nil
}

func (m *Worker) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func WorkerFromJSON(data []byte) (*Worker, error) {
	var m Worker
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BossState int

const (
	BossStateIdle = iota
	BossStateRunning
)

func (s BossState) String() string {
	switch s {
	case BossStateIdle:
		return "Idle"
	case BossStateRunning:
		return "Running"
	default:
		return "Unknown"
	}
}

type BossIdleData struct {
	Job string `json:"job"`
}

type BossRunningData struct {
	Current string `json:"current"`
}

type Boss struct {
	State BossState
	IdleData *BossIdleData
	RunningData *BossRunningData
}

func (m *Boss) clearStateData() {
	m.IdleData = nil
	m.RunningData = nil
}

func (m Boss) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case BossStateIdle:
		if m.IdleData != nil {
			envelope.Data = m.IdleData
		}
	case BossStateRunning:
		if m.RunningData != nil {
			envelope.Data = m.RunningData
		}
	default:
		return nil, fmt.Errorf("Boss: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *Boss) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Idle":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Boss: state 'Idle' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"job"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("Boss: state 'Idle' is missing required field %q", field)
			}
		}
		data := &BossIdleData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BossStateIdle
		m.IdleData = data
	case "Running":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Boss: state 'Running' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"current"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("Boss: state 'Running' is missing required field %q", field)
			}
		}
		data := &BossRunningData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BossStateRunning
		m.RunningData = data
	default:
		return fmt.Errorf("Boss: unknown state %q", envelope.State)
	}
	return nil
}

func NewBoss(job string) *Boss {
	return &Boss{
		State: BossStateIdle,
		IdleData: &BossIdleData{
			Job: job,
		},
	}
}

// BossChildren supplies a runner for each child Boss supervises.
type BossChildren interface {
	// RunWorker drives a supervised Worker to completion. A non-nil
	// error marks the child failed, which is what the restart
	// strategy acts on.
	RunWorker(child *Worker) error
}

var BossSupervision = []SupervisionSpec{
	{Child: "Worker", Strategy: OneForOne},
}

type BossError struct {
	Transition string
	From      string
	Message   string
}

func (e *BossError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Boss) Begin(supervisor SupervisorRuntime, children BossChildren) error {
	if m.State != BossStateIdle {
		return &BossError{Transition: "begin", From: m.State.String()}
	}

	if err := supervisor.SpawnNamed("Worker", func() error {
		return children.RunWorker(NewWorker(m.IdleData.Job))
	}); err != nil {
		return err
	}
	var __goto_running_current string = m.IdleData.Job
	m.State = BossStateRunning
	m.clearStateData()
	m.RunningData = &BossRunningData{
		Current: __goto_running_current,
	}

	return nil
}

func (m *Boss) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BossFromJSON(data []byte) (*Boss, error) {
	var m Boss
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type ResultMatchingState int

const (
	ResultMatchingStateIdle = iota
	ResultMatchingStateOk2
	ResultMatchingStateFailed
)

func (s ResultMatchingState) String() string {
	switch s {
	case ResultMatchingStateIdle:
		return "Idle"
	case ResultMatchingStateOk2:
		return "Ok2"
	case ResultMatchingStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type ResultMatchingIdleData struct {
	Id string `json:"id"`
}

type ResultMatchingOk2Data struct {
	Token string `json:"token"`
}

type ResultMatchingFailedData struct {
	Why string `json:"why"`
}

type ResultMatchingEffects interface {
	// gust:effect -- replay-safe / idempotent
	Lookup(ctx context.Context, id string) (string, error)
}

type ResultMatching struct {
	State ResultMatchingState
	IdleData *ResultMatchingIdleData
	Ok2Data *ResultMatchingOk2Data
	FailedData *ResultMatchingFailedData
}

func (m *ResultMatching) clearStateData() {
	m.IdleData = nil
	m.Ok2Data = nil
	m.FailedData = nil
}

func (m ResultMatching) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case ResultMatchingStateIdle:
		if m.IdleData != nil {
			envelope.Data = m.IdleData
		}
	case ResultMatchingStateOk2:
		if m.Ok2Data != nil {
			envelope.Data = m.Ok2Data
		}
	case ResultMatchingStateFailed:
		if m.FailedData != nil {
			envelope.Data = m.FailedData
		}
	default:
		return nil, fmt.Errorf("ResultMatching: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *ResultMatching) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Idle":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("ResultMatching: state 'Idle' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"id"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("ResultMatching: state 'Idle' is missing required field %q", field)
			}
		}
		data := &ResultMatchingIdleData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = ResultMatchingStateIdle
		m.IdleData = data
	case "Ok2":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("ResultMatching: state 'Ok2' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"token"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("ResultMatching: state 'Ok2' is missing required field %q", field)
			}
		}
		data := &ResultMatchingOk2Data{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = ResultMatchingStateOk2
		m.Ok2Data = data
	case "Failed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("ResultMatching: state 'Failed' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"why"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("ResultMatching: state 'Failed' is missing required field %q", field)
			}
		}
		data := &ResultMatchingFailedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = ResultMatchingStateFailed
		m.FailedData = data
	default:
		return fmt.Errorf("ResultMatching: unknown state %q", envelope.State)
	}
	return nil
}

func NewResultMatching(id string) *ResultMatching {
	return &ResultMatching{
		State: ResultMatchingStateIdle,
		IdleData: &ResultMatchingIdleData{
			Id: id,
		},
	}
}

type ResultMatchingError struct {
	Transition string
	From      string
	Message   string
}

func (e *ResultMatchingError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *ResultMatching) Fetch(ctx context.Context, effects ResultMatchingEffects) error {
	if m.State != ResultMatchingStateIdle {
		return &ResultMatchingError{Transition: "fetch", From: m.State.String()}
	}

	r, __r_err := effects.Lookup(ctx, m.IdleData.Id)
	if __r_err == nil {
		token := r
		m.State = ResultMatchingStateOk2
		m.clearStateData()
		m.Ok2Data = &ResultMatchingOk2Data{
			Token: token,
		}
	} else {
		e := __r_err.Error()
		m.State = ResultMatchingStateFailed
		m.clearStateData()
		m.FailedData = &ResultMatchingFailedData{
			Why: e,
		}
	}

	return nil
}

func (m *ResultMatching) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func ResultMatchingFromJSON(data []byte) (*ResultMatching, error) {
	var m ResultMatching
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type HolderState[T any] int

const (
	HolderStateEmpty = iota
	HolderStateFull
)

func (s HolderState[T]) String() string {
	switch s {
	case HolderStateEmpty:
		return "Empty"
	case HolderStateFull:
		return "Full"
	default:
		return "Unknown"
	}
}

type HolderFullData[T any] struct {
	Value T `json:"value"`
}

type Holder[T any] struct {
	State HolderState[T]
	FullData *HolderFullData[T]
}

func (m *Holder[T]) clearStateData() {
	m.FullData = nil
}

func (m Holder[T]) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case HolderStateEmpty:
	case HolderStateFull:
		if m.FullData != nil {
			envelope.Data = m.FullData
		}
	default:
		return nil, fmt.Errorf("Holder: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *Holder[T]) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Empty":
		m.clearStateData()
		m.State = HolderStateEmpty
	case "Full":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Holder: state 'Full' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"value"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("Holder: state 'Full' is missing required field %q", field)
			}
		}
		data := &HolderFullData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = HolderStateFull
		m.FullData = data
	default:
		return fmt.Errorf("Holder: unknown state %q", envelope.State)
	}
	return nil
}

func NewHolder[T any]() *Holder[T] {
	return &Holder[T]{
		State: HolderStateEmpty,
	}
}

type HolderError struct {
	Transition string
	From      string
	Message   string
}

func (e *HolderError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Holder[T]) Put(value T) error {
	if m.State != HolderStateEmpty {
		return &HolderError{Transition: "put", From: m.State.String()}
	}

	m.State = HolderStateFull
	m.clearStateData()
	m.FullData = &HolderFullData[T]{
		Value: value,
	}

	return nil
}

func (m *Holder[T]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func HolderFromJSON[T any](data []byte) (*Holder[T], error) {
	var m Holder[T]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type BareFieldReadsState int

const (
	BareFieldReadsStateConfigured = iota
	BareFieldReadsStateLive
)

func (s BareFieldReadsState) String() string {
	switch s {
	case BareFieldReadsStateConfigured:
		return "Configured"
	case BareFieldReadsStateLive:
		return "Live"
	default:
		return "Unknown"
	}
}

type BareFieldReadsConfiguredData struct {
	Service string `json:"service"`
	Tier Tier `json:"tier"`
}

type BareFieldReadsLiveData struct {
	Service string `json:"service"`
}

type BareFieldReadsEffects interface {
	// gust:effect -- replay-safe / idempotent
	Announce(name string)
}

type BareFieldReads struct {
	State BareFieldReadsState
	ConfiguredData *BareFieldReadsConfiguredData
	LiveData *BareFieldReadsLiveData
}

func (m *BareFieldReads) clearStateData() {
	m.ConfiguredData = nil
	m.LiveData = nil
}

func (m BareFieldReads) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case BareFieldReadsStateConfigured:
		if m.ConfiguredData != nil {
			envelope.Data = m.ConfiguredData
		}
	case BareFieldReadsStateLive:
		if m.LiveData != nil {
			envelope.Data = m.LiveData
		}
	default:
		return nil, fmt.Errorf("BareFieldReads: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *BareFieldReads) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Configured":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BareFieldReads: state 'Configured' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"service", "tier"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BareFieldReads: state 'Configured' is missing required field %q", field)
			}
		}
		data := &BareFieldReadsConfiguredData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BareFieldReadsStateConfigured
		m.ConfiguredData = data
	case "Live":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("BareFieldReads: state 'Live' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"service"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("BareFieldReads: state 'Live' is missing required field %q", field)
			}
		}
		data := &BareFieldReadsLiveData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = BareFieldReadsStateLive
		m.LiveData = data
	default:
		return fmt.Errorf("BareFieldReads: unknown state %q", envelope.State)
	}
	return nil
}

func NewBareFieldReads(service string, tier Tier) *BareFieldReads {
	return &BareFieldReads{
		State: BareFieldReadsStateConfigured,
		ConfiguredData: &BareFieldReadsConfiguredData{
			Service: service,
			Tier: tier,
		},
	}
}

type BareFieldReadsError struct {
	Transition string
	From      string
	Message   string
}

func (e *BareFieldReadsError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *BareFieldReads) Launch(effects BareFieldReadsEffects) error {
	if m.State != BareFieldReadsStateConfigured {
		return &BareFieldReadsError{Transition: "launch", From: m.State.String()}
	}

	service := m.ConfiguredData.Service

	effects.Announce(service)
	var __goto_live_service string = m.ConfiguredData.Service
	m.State = BareFieldReadsStateLive
	m.clearStateData()
	m.LiveData = &BareFieldReadsLiveData{
		Service: __goto_live_service,
	}

	return nil
}

func (m *BareFieldReads) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func BareFieldReadsFromJSON(data []byte) (*BareFieldReads, error) {
	var m BareFieldReads
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
