// Code generated by Gust compiler — DO NOT EDIT.

package request_response

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type RequestResponseState[T any, R any] int

const (
	RequestResponseStatePending = iota
	RequestResponseStateCompleted
	RequestResponseStateFailed
	RequestResponseStateTimedOut
)

func (s RequestResponseState[T, R]) String() string {
	switch s {
	case RequestResponseStatePending:
		return "Pending"
	case RequestResponseStateCompleted:
		return "Completed"
	case RequestResponseStateFailed:
		return "Failed"
	case RequestResponseStateTimedOut:
		return "TimedOut"
	default:
		return "Unknown"
	}
}

type RequestResponsePendingData[T any, R any] struct {
	Request T `json:"request"`
	TimeoutMs int64 `json:"timeout_ms"`
}

type RequestResponseCompletedData[T any, R any] struct {
	Response R `json:"response"`
}

type RequestResponseFailedData[T any, R any] struct {
	Error string `json:"error"`
}

type RequestResponseTimedOutData[T any, R any] struct {
	ElapsedMs int64 `json:"elapsed_ms"`
}

type RequestResponseEffects[T any, R any] interface {
	// gust:effect -- replay-safe / idempotent
	WaitForResponse(ctx context.Context, request T, timeout_ms int64) (R, error)
	// gust:effect -- replay-safe / idempotent
	CurrentTimeMs() int64
}

type RequestResponse[T any, R any] struct {
	State RequestResponseState[T, R]
	PendingData *RequestResponsePendingData[T, R]
	CompletedData *RequestResponseCompletedData[T, R]
	FailedData *RequestResponseFailedData[T, R]
	TimedOutData *RequestResponseTimedOutData[T, R]
}

func (m *RequestResponse[T, R]) clearStateData() {
	m.PendingData = nil
	m.CompletedData = nil
	m.FailedData = nil
	m.TimedOutData = nil
}

func (m RequestResponse[T, R]) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case RequestResponseStatePending:
		if m.PendingData != nil {
			envelope.Data = m.PendingData
		}
	case RequestResponseStateCompleted:
		if m.CompletedData != nil {
			envelope.Data = m.CompletedData
		}
	case RequestResponseStateFailed:
		if m.FailedData != nil {
			envelope.Data = m.FailedData
		}
	case RequestResponseStateTimedOut:
		if m.TimedOutData != nil {
			envelope.Data = m.TimedOutData
		}
	default:
		return nil, fmt.Errorf("RequestResponse: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *RequestResponse[T, R]) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Pending":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RequestResponse: state 'Pending' requires a data payload")
		}
		data := &RequestResponsePendingData[T, R]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RequestResponseStatePending
		m.PendingData = data
	case "Completed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RequestResponse: state 'Completed' requires a data payload")
		}
		data := &RequestResponseCompletedData[T, R]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RequestResponseStateCompleted
		m.CompletedData = data
	case "Failed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RequestResponse: state 'Failed' requires a data payload")
		}
		data := &RequestResponseFailedData[T, R]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RequestResponseStateFailed
		m.FailedData = data
	case "TimedOut":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("RequestResponse: state 'TimedOut' requires a data payload")
		}
		data := &RequestResponseTimedOutData[T, R]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RequestResponseStateTimedOut
		m.TimedOutData = data
	default:
		return fmt.Errorf("RequestResponse: unknown state %q", envelope.State)
	}
	return nil
}

func NewRequestResponse[T any, R any](request T, timeout_ms int64) *RequestResponse[T, R] {
	return &RequestResponse[T, R]{
		State: RequestResponseStatePending,
		PendingData: &RequestResponsePendingData[T, R]{
			Request: request,
			TimeoutMs: timeout_ms,
		},
	}
}

type RequestResponseError struct {
	Transition string
	From      string
	Message   string
}

func (e *RequestResponseError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *RequestResponse[T, R]) Send() error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "send", From: m.State.String()}
	}

	request := m.PendingData.Request
	timeout_ms := m.PendingData.TimeoutMs

	m.State = RequestResponseStatePending
	m.clearStateData()
	m.PendingData = &RequestResponsePendingData[T, R]{
		Request: request,
		TimeoutMs: timeout_ms,
	}

	return nil
}

func (m *RequestResponse[T, R]) Receive(ctx context.Context, effects RequestResponseEffects[T, R]) error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "receive", From: m.State.String()}
	}

	request := m.PendingData.Request
	timeout_ms := m.PendingData.TimeoutMs

	result, __result_err := effects.WaitForResponse(ctx, request, timeout_ms)
	if __result_err == nil {
		response := result
		m.State = RequestResponseStateCompleted
		m.clearStateData()
		m.CompletedData = &RequestResponseCompletedData[T, R]{
			Response: response,
		}
	} else {
		err := __result_err.Error()
		m.State = RequestResponseStateFailed
		m.clearStateData()
		m.FailedData = &RequestResponseFailedData[T, R]{
			Error: err,
		}
	}

	return nil
}

func (m *RequestResponse[T, R]) Timeout(effects RequestResponseEffects[T, R]) error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "timeout", From: m.State.String()}
	}

	elapsed := effects.CurrentTimeMs()
	m.State = RequestResponseStateTimedOut
	m.clearStateData()
	m.TimedOutData = &RequestResponseTimedOutData[T, R]{
		ElapsedMs: elapsed,
	}

	return nil
}

func (m *RequestResponse[T, R]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func RequestResponseFromJSON[T any, R any](data []byte) (*RequestResponse[T, R], error) {
	var m RequestResponse[T, R]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
