// Code generated by Gust compiler — DO NOT EDIT.

package request_response

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type RequestResponseState[T any, R any] int

const (
	RequestResponseStatePending = iota
	RequestResponseStateCompleted
	RequestResponseStateFailed
	RequestResponseStateTimedOut
)

func (s RequestResponseState[T, R]) String() string {
	switch s {
	case RequestResponseStatePending:
		return "Pending"
	case RequestResponseStateCompleted:
		return "Completed"
	case RequestResponseStateFailed:
		return "Failed"
	case RequestResponseStateTimedOut:
		return "TimedOut"
	default:
		return "Unknown"
	}
}

type RequestResponsePendingData[T any, R any] struct {
	Request T `json:"request"`
	TimeoutMs int64 `json:"timeout_ms"`
}

type RequestResponseCompletedData[T any, R any] struct {
	Response R `json:"response"`
}

type RequestResponseFailedData[T any, R any] struct {
	Error string `json:"error"`
}

type RequestResponseTimedOutData[T any, R any] struct {
	ElapsedMs int64 `json:"elapsed_ms"`
}

type RequestResponseEffects[T any, R any] interface {
	// gust:effect -- replay-safe / idempotent
	WaitForResponse(ctx context.Context, request T, timeout_ms int64) (R, error)
	// gust:effect -- replay-safe / idempotent
	CurrentTimeMs() int64
}

type RequestResponse[T any, R any] struct {
	State RequestResponseState[T, R] `json:"state"`
	PendingData *RequestResponsePendingData[T, R] `json:"pending_data,omitempty"`
	CompletedData *RequestResponseCompletedData[T, R] `json:"completed_data,omitempty"`
	FailedData *RequestResponseFailedData[T, R] `json:"failed_data,omitempty"`
	TimedOutData *RequestResponseTimedOutData[T, R] `json:"timed_out_data,omitempty"`
}

func (m *RequestResponse[T, R]) clearStateData() {
	m.PendingData = nil
	m.CompletedData = nil
	m.FailedData = nil
	m.TimedOutData = nil
}

func NewRequestResponse[T any, R any](request T, timeout_ms int64) *RequestResponse[T, R] {
	return &RequestResponse[T, R]{
		State: RequestResponseStatePending,
		PendingData: &RequestResponsePendingData[T, R]{
			Request: request,
			TimeoutMs: timeout_ms,
		},
	}
}

type RequestResponseError struct {
	Transition string
	From      string
	Message   string
}

func (e *RequestResponseError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *RequestResponse[T, R]) Send() error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "send", From: m.State.String()}
	}

	request := m.PendingData.Request
	timeout_ms := m.PendingData.TimeoutMs

	m.State = RequestResponseStatePending
	m.clearStateData()
	m.PendingData = &RequestResponsePendingData[T, R]{
		Request: request,
		TimeoutMs: timeout_ms,
	}

	return nil
}

func (m *RequestResponse[T, R]) Receive(ctx context.Context, effects RequestResponseEffects[T, R]) error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "receive", From: m.State.String()}
	}

	request := m.PendingData.Request
	timeout_ms := m.PendingData.TimeoutMs

	result, __result_err := effects.WaitForResponse(ctx, request, timeout_ms)
	if __result_err == nil {
		response := result
		m.State = RequestResponseStateCompleted
		m.clearStateData()
		m.CompletedData = &RequestResponseCompletedData[T, R]{
			Response: response,
		}
	} else {
		err := __result_err.Error()
		m.State = RequestResponseStateFailed
		m.clearStateData()
		m.FailedData = &RequestResponseFailedData[T, R]{
			Error: err,
		}
	}

	return nil
}

func (m *RequestResponse[T, R]) Timeout(effects RequestResponseEffects[T, R]) error {
	if m.State != RequestResponseStatePending {
		return &RequestResponseError{Transition: "timeout", From: m.State.String()}
	}

	elapsed := effects.CurrentTimeMs()
	m.State = RequestResponseStateTimedOut
	m.clearStateData()
	m.TimedOutData = &RequestResponseTimedOutData[T, R]{
		ElapsedMs: elapsed,
	}

	return nil
}

func (m *RequestResponse[T, R]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func RequestResponseFromJSON[T any, R any](data []byte) (*RequestResponse[T, R], error) {
	var m RequestResponse[T, R]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
