// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RequestResponseState<T, R> {
    Pending {
        request: T,
        timeout_ms: i64,
    },
    Completed {
        response: R,
    },
    Failed {
        error: String,
    },
    TimedOut {
        elapsed_ms: i64,
    },
}

pub trait RequestResponseEffects<T, R> {
    /// gust:effect -- replay-safe / idempotent
    fn wait_for_response(&self, request: &T, timeout_ms: i64) -> impl ::core::future::Future<Output = Result<R, String>> + Send;
    /// gust:effect -- replay-safe / idempotent
    fn current_time_ms(&self) -> i64;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestResponse<T, R> {
    pub state: RequestResponseState<T, R>,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum RequestResponseError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl<T: core::fmt::Debug + Clone, R: core::fmt::Debug + Clone> RequestResponse<T, R> {
    pub fn new(request: T, timeout_ms: i64) -> Self {
        Self { state: RequestResponseState::Pending { request, timeout_ms } }
    }

    pub fn state(&self) -> &RequestResponseState<T, R> {
        &self.state
    }

    pub fn send(&mut self) -> Result<(), RequestResponseError> {
        match &self.state {
            RequestResponseState::Pending { request, timeout_ms } => {
                let request = request.clone();
                let timeout_ms = *timeout_ms;
                self.state = RequestResponseState::Pending { request, timeout_ms };
                Ok(())
            }
            _ => Err(RequestResponseError::InvalidTransition {
                transition: "send".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn receive(&mut self, effects: &impl RequestResponseEffects<T, R>) -> Result<(), RequestResponseError> {
        match &self.state {
            RequestResponseState::Pending { request, timeout_ms } => {
                let request = request.clone();
                let timeout_ms = *timeout_ms;
                let result = effects.wait_for_response(&request, timeout_ms).await;
                match result {
                    Ok(response) => {
                        self.state = RequestResponseState::Completed { response };
                        Ok(())
                    }
                    Err(err) => {
                        self.state = RequestResponseState::Failed { error: err };
                        Ok(())
                    }
                }
            }
            _ => Err(RequestResponseError::InvalidTransition {
                transition: "receive".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn timeout(&mut self, effects: &impl RequestResponseEffects<T, R>) -> Result<(), RequestResponseError> {
        match &self.state {
            RequestResponseState::Pending { request: _request, timeout_ms: _timeout_ms } => {
                let elapsed = effects.current_time_ms();
                self.state = RequestResponseState::TimedOut { elapsed_ms: elapsed };
                Ok(())
            }
            _ => Err(RequestResponseError::InvalidTransition {
                transition: "timeout".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
