// Code generated by Gust compiler — DO NOT EDIT.

package retry

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type RetryState[T any] int

const (
	RetryStateReady = iota
	RetryStateAttempting
	RetryStateWaiting
	RetryStateSucceeded
	RetryStateFailed
)

func (s RetryState[T]) String() string {
	switch s {
	case RetryStateReady:
		return "Ready"
	case RetryStateAttempting:
		return "Attempting"
	case RetryStateWaiting:
		return "Waiting"
	case RetryStateSucceeded:
		return "Succeeded"
	case RetryStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type RetryReadyData[T any] struct {
	MaxAttempts int64 `json:"max_attempts"`
	BaseDelayMs int64 `json:"base_delay_ms"`
	MaxDelayMs int64 `json:"max_delay_ms"`
	JitterPct int64 `json:"jitter_pct"`
}

type RetryAttemptingData[T any] struct {
	Attempt int64 `json:"attempt"`
	MaxAttempts int64 `json:"max_attempts"`
	BaseDelayMs int64 `json:"base_delay_ms"`
	MaxDelayMs int64 `json:"max_delay_ms"`
	JitterPct int64 `json:"jitter_pct"`
}

type RetryWaitingData[T any] struct {
	Attempt int64 `json:"attempt"`
	DelayMs int64 `json:"delay_ms"`
	MaxAttempts int64 `json:"max_attempts"`
	BaseDelayMs int64 `json:"base_delay_ms"`
	MaxDelayMs int64 `json:"max_delay_ms"`
	JitterPct int64 `json:"jitter_pct"`
}

type RetrySucceededData[T any] struct {
	Value T `json:"value"`
	Attempts int64 `json:"attempts"`
}

type RetryFailedData[T any] struct {
	Error string `json:"error"`
	Attempts int64 `json:"attempts"`
}

type RetryEffects[T any] interface {
	// gust:effect -- replay-safe / idempotent
	ExecuteOperation(ctx context.Context) (T, error)
	// gust:effect -- replay-safe / idempotent
	SleepMs(ctx context.Context, duration_ms int64) (int64, error)
	// gust:effect -- replay-safe / idempotent
	ComputeBackoff(base_delay_ms int64, attempt int64, max_delay_ms int64, jitter_pct int64) int64
}

type Retry[T any] struct {
	State RetryState[T]
	ReadyData *RetryReadyData[T]
	AttemptingData *RetryAttemptingData[T]
	WaitingData *RetryWaitingData[T]
	SucceededData *RetrySucceededData[T]
	FailedData *RetryFailedData[T]
}

func (m *Retry[T]) clearStateData() {
	m.ReadyData = nil
	m.AttemptingData = nil
	m.WaitingData = nil
	m.SucceededData = nil
	m.FailedData = nil
}

func (m Retry[T]) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case RetryStateReady:
		if m.ReadyData != nil {
			envelope.Data = m.ReadyData
		}
	case RetryStateAttempting:
		if m.AttemptingData != nil {
			envelope.Data = m.AttemptingData
		}
	case RetryStateWaiting:
		if m.WaitingData != nil {
			envelope.Data = m.WaitingData
		}
	case RetryStateSucceeded:
		if m.SucceededData != nil {
			envelope.Data = m.SucceededData
		}
	case RetryStateFailed:
		if m.FailedData != nil {
			envelope.Data = m.FailedData
		}
	default:
		return nil, fmt.Errorf("Retry: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *Retry[T]) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Ready":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Retry: state 'Ready' requires a data payload")
		}
		data := &RetryReadyData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RetryStateReady
		m.ReadyData = data
	case "Attempting":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Retry: state 'Attempting' requires a data payload")
		}
		data := &RetryAttemptingData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RetryStateAttempting
		m.AttemptingData = data
	case "Waiting":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Retry: state 'Waiting' requires a data payload")
		}
		data := &RetryWaitingData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RetryStateWaiting
		m.WaitingData = data
	case "Succeeded":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Retry: state 'Succeeded' requires a data payload")
		}
		data := &RetrySucceededData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RetryStateSucceeded
		m.SucceededData = data
	case "Failed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Retry: state 'Failed' requires a data payload")
		}
		data := &RetryFailedData[T]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = RetryStateFailed
		m.FailedData = data
	default:
		return fmt.Errorf("Retry: unknown state %q", envelope.State)
	}
	return nil
}

func NewRetry[T any](max_attempts int64, base_delay_ms int64, max_delay_ms int64, jitter_pct int64) *Retry[T] {
	return &Retry[T]{
		State: RetryStateReady,
		ReadyData: &RetryReadyData[T]{
			MaxAttempts: max_attempts,
			BaseDelayMs: base_delay_ms,
			MaxDelayMs: max_delay_ms,
			JitterPct: jitter_pct,
		},
	}
}

type RetryError struct {
	Transition string
	From      string
	Message   string
}

func (e *RetryError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Retry[T]) Begin() error {
	if m.State != RetryStateReady {
		return &RetryError{Transition: "begin", From: m.State.String()}
	}

	max_attempts := m.ReadyData.MaxAttempts
	base_delay_ms := m.ReadyData.BaseDelayMs
	max_delay_ms := m.ReadyData.MaxDelayMs
	jitter_pct := m.ReadyData.JitterPct

	m.State = RetryStateAttempting
	m.clearStateData()
	m.AttemptingData = &RetryAttemptingData[T]{
		Attempt: 1,
		MaxAttempts: max_attempts,
		BaseDelayMs: base_delay_ms,
		MaxDelayMs: max_delay_ms,
		JitterPct: jitter_pct,
	}

	return nil
}

func (m *Retry[T]) Run(ctx context.Context, effects RetryEffects[T]) error {
	if m.State != RetryStateAttempting {
		return &RetryError{Transition: "run", From: m.State.String()}
	}

	attempt := m.AttemptingData.Attempt
	max_attempts := m.AttemptingData.MaxAttempts
	base_delay_ms := m.AttemptingData.BaseDelayMs
	max_delay_ms := m.AttemptingData.MaxDelayMs
	jitter_pct := m.AttemptingData.JitterPct

	result, __result_err := effects.ExecuteOperation(ctx)
	if __result_err == nil {
		value := result
		m.State = RetryStateSucceeded
		m.clearStateData()
		m.SucceededData = &RetrySucceededData[T]{
			Value: value,
			Attempts: attempt,
		}
	} else {
		err := __result_err.Error()
		if attempt >= max_attempts {
			m.State = RetryStateFailed
			m.clearStateData()
			m.FailedData = &RetryFailedData[T]{
				Error: err,
				Attempts: attempt,
			}
		} else {
			delay := effects.ComputeBackoff(base_delay_ms, attempt, max_delay_ms, jitter_pct)
			m.State = RetryStateWaiting
			m.clearStateData()
			m.WaitingData = &RetryWaitingData[T]{
				Attempt: attempt,
				DelayMs: delay,
				MaxAttempts: max_attempts,
				BaseDelayMs: base_delay_ms,
				MaxDelayMs: max_delay_ms,
				JitterPct: jitter_pct,
			}
		}
	}

	return nil
}

func (m *Retry[T]) WaitComplete(ctx context.Context, effects RetryEffects[T]) error {
	if m.State != RetryStateWaiting {
		return &RetryError{Transition: "wait_complete", From: m.State.String()}
	}

	attempt := m.WaitingData.Attempt
	delay_ms := m.WaitingData.DelayMs
	max_attempts := m.WaitingData.MaxAttempts
	base_delay_ms := m.WaitingData.BaseDelayMs
	max_delay_ms := m.WaitingData.MaxDelayMs
	jitter_pct := m.WaitingData.JitterPct

	if _, err := effects.SleepMs(ctx, delay_ms); err != nil {
		return err
	}
	m.State = RetryStateAttempting
	m.clearStateData()
	m.AttemptingData = &RetryAttemptingData[T]{
		Attempt: (attempt + 1),
		MaxAttempts: max_attempts,
		BaseDelayMs: base_delay_ms,
		MaxDelayMs: max_delay_ms,
		JitterPct: jitter_pct,
	}

	return nil
}

func (m *Retry[T]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func RetryFromJSON[T any](data []byte) (*Retry[T], error) {
	var m Retry[T]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
