// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RetryState<T> {
    Ready {
        max_attempts: i64,
        base_delay_ms: i64,
        max_delay_ms: i64,
        jitter_pct: i64,
    },
    Attempting {
        attempt: i64,
        max_attempts: i64,
        base_delay_ms: i64,
        max_delay_ms: i64,
        jitter_pct: i64,
    },
    Waiting {
        attempt: i64,
        delay_ms: i64,
        max_attempts: i64,
        base_delay_ms: i64,
        max_delay_ms: i64,
        jitter_pct: i64,
    },
    Succeeded {
        value: T,
        attempts: i64,
    },
    Failed {
        error: String,
        attempts: i64,
    },
}

pub trait RetryEffects<T> {
    /// gust:effect -- replay-safe / idempotent
    fn execute_operation(&self) -> impl ::core::future::Future<Output = Result<T, String>> + Send;
    /// gust:effect -- replay-safe / idempotent
    fn sleep_ms(&self, duration_ms: i64) -> impl ::core::future::Future<Output = i64> + Send;
    /// gust:effect -- replay-safe / idempotent
    fn compute_backoff(&self, base_delay_ms: i64, attempt: i64, max_delay_ms: i64, jitter_pct: i64) -> i64;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Retry<T> {
    pub state: RetryState<T>,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum RetryError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl<T: core::fmt::Debug + Clone> Retry<T> {
    pub fn new(max_attempts: i64, base_delay_ms: i64, max_delay_ms: i64, jitter_pct: i64) -> Self {
        Self { state: RetryState::Ready { max_attempts, base_delay_ms, max_delay_ms, jitter_pct } }
    }

    pub fn state(&self) -> &RetryState<T> {
        &self.state
    }

    pub fn begin(&mut self) -> Result<(), RetryError> {
        match &self.state {
            RetryState::Ready { max_attempts, base_delay_ms, max_delay_ms, jitter_pct } => {
                let max_attempts = *max_attempts;
                let base_delay_ms = *base_delay_ms;
                let max_delay_ms = *max_delay_ms;
                let jitter_pct = *jitter_pct;
                let __goto_attempting_attempt = 1;
                self.state = RetryState::Attempting { attempt: __goto_attempting_attempt, max_attempts, base_delay_ms, max_delay_ms, jitter_pct };
                Ok(())
            }
            _ => Err(RetryError::InvalidTransition {
                transition: "begin".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn run(&mut self, effects: &impl RetryEffects<T>) -> Result<(), RetryError> {
        match &self.state {
            RetryState::Attempting { attempt, max_attempts, base_delay_ms, max_delay_ms, jitter_pct } => {
                let attempt = *attempt;
                let max_attempts = *max_attempts;
                let base_delay_ms = *base_delay_ms;
                let max_delay_ms = *max_delay_ms;
                let jitter_pct = *jitter_pct;
                let result = effects.execute_operation().await;
                match result {
                    Ok(value) => {
                        self.state = RetryState::Succeeded { value, attempts: attempt };
                        Ok(())
                    }
                    Err(err) => {
                        if attempt >= max_attempts {
                            self.state = RetryState::Failed { error: err, attempts: attempt };
                            Ok(())
                        } else {
                            let delay = effects.compute_backoff(base_delay_ms, attempt, max_delay_ms, jitter_pct);
                            self.state = RetryState::Waiting { attempt, delay_ms: delay, max_attempts, base_delay_ms, max_delay_ms, jitter_pct };
                            Ok(())
                        }
                    }
                }
            }
            _ => Err(RetryError::InvalidTransition {
                transition: "run".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn wait_complete(&mut self, effects: &impl RetryEffects<T>) -> Result<(), RetryError> {
        match &self.state {
            RetryState::Waiting { attempt, delay_ms, max_attempts, base_delay_ms, max_delay_ms, jitter_pct } => {
                let attempt = *attempt;
                let delay_ms = *delay_ms;
                let max_attempts = *max_attempts;
                let base_delay_ms = *base_delay_ms;
                let max_delay_ms = *max_delay_ms;
                let jitter_pct = *jitter_pct;
                effects.sleep_ms(delay_ms).await;
                let __goto_attempting_attempt = attempt + 1;
                self.state = RetryState::Attempting { attempt: __goto_attempting_attempt, max_attempts, base_delay_ms, max_delay_ms, jitter_pct };
                Ok(())
            }
            _ => Err(RetryError::InvalidTransition {
                transition: "wait_complete".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
