// Code generated by Gust compiler — DO NOT EDIT.

package saga

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type SagaState[S any] int

const (
	SagaStatePlanning = iota
	SagaStateExecuting
	SagaStateCompensating
	SagaStateCommitted
	SagaStateAborted
)

func (s SagaState[S]) String() string {
	switch s {
	case SagaStatePlanning:
		return "Planning"
	case SagaStateExecuting:
		return "Executing"
	case SagaStateCompensating:
		return "Compensating"
	case SagaStateCommitted:
		return "Committed"
	case SagaStateAborted:
		return "Aborted"
	default:
		return "Unknown"
	}
}

type SagaPlanningData[S any] struct {
	Steps []S `json:"steps"`
}

type SagaExecutingData[S any] struct {
	Steps []S `json:"steps"`
	Index int64 `json:"index"`
	Completed []S `json:"completed"`
}

type SagaCompensatingData[S any] struct {
	Completed []S `json:"completed"`
	Index int64 `json:"index"`
	Reason string `json:"reason"`
}

type SagaCommittedData[S any] struct {
	Completed []S `json:"completed"`
}

type SagaAbortedData[S any] struct {
	Reason string `json:"reason"`
	CompensatedCount int64 `json:"compensated_count"`
}

type SagaEffects[S any] interface {
	// gust:effect -- replay-safe / idempotent
	ExecuteForward(ctx context.Context, step S) (S, error)
	// gust:effect -- replay-safe / idempotent
	ExecuteCompensate(ctx context.Context, step S) (int64, error)
	// gust:effect -- replay-safe / idempotent
	Len(steps []S) int64
	// gust:effect -- replay-safe / idempotent
	GetStep(steps []S, index int64) S
	// gust:effect -- replay-safe / idempotent
	PushStep(steps []S, step S) []S
	// gust:effect -- replay-safe / idempotent
	EmptySteps() []S
}

type Saga[S any] struct {
	State SagaState[S]
	PlanningData *SagaPlanningData[S]
	ExecutingData *SagaExecutingData[S]
	CompensatingData *SagaCompensatingData[S]
	CommittedData *SagaCommittedData[S]
	AbortedData *SagaAbortedData[S]
}

func (m *Saga[S]) clearStateData() {
	m.PlanningData = nil
	m.ExecutingData = nil
	m.CompensatingData = nil
	m.CommittedData = nil
	m.AbortedData = nil
}

func (m Saga[S]) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case SagaStatePlanning:
		if m.PlanningData != nil {
			envelope.Data = m.PlanningData
		}
	case SagaStateExecuting:
		if m.ExecutingData != nil {
			envelope.Data = m.ExecutingData
		}
	case SagaStateCompensating:
		if m.CompensatingData != nil {
			envelope.Data = m.CompensatingData
		}
	case SagaStateCommitted:
		if m.CommittedData != nil {
			envelope.Data = m.CommittedData
		}
	case SagaStateAborted:
		if m.AbortedData != nil {
			envelope.Data = m.AbortedData
		}
	default:
		return nil, fmt.Errorf("Saga: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *Saga[S]) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Planning":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Saga: state 'Planning' requires a data payload")
		}
		data := &SagaPlanningData[S]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SagaStatePlanning
		m.PlanningData = data
	case "Executing":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Saga: state 'Executing' requires a data payload")
		}
		data := &SagaExecutingData[S]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SagaStateExecuting
		m.ExecutingData = data
	case "Compensating":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Saga: state 'Compensating' requires a data payload")
		}
		data := &SagaCompensatingData[S]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SagaStateCompensating
		m.CompensatingData = data
	case "Committed":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Saga: state 'Committed' requires a data payload")
		}
		data := &SagaCommittedData[S]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SagaStateCommitted
		m.CommittedData = data
	case "Aborted":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("Saga: state 'Aborted' requires a data payload")
		}
		data := &SagaAbortedData[S]{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SagaStateAborted
		m.AbortedData = data
	default:
		return fmt.Errorf("Saga: unknown state %q", envelope.State)
	}
	return nil
}

func NewSaga[S any](steps []S) *Saga[S] {
	return &Saga[S]{
		State: SagaStatePlanning,
		PlanningData: &SagaPlanningData[S]{
			Steps: steps,
		},
	}
}

type SagaError struct {
	Transition string
	From      string
	Message   string
}

func (e *SagaError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *Saga[S]) Begin(effects SagaEffects[S]) error {
	if m.State != SagaStatePlanning {
		return &SagaError{Transition: "begin", From: m.State.String()}
	}

	steps := m.PlanningData.Steps

	m.State = SagaStateExecuting
	m.clearStateData()
	m.ExecutingData = &SagaExecutingData[S]{
		Steps: steps,
		Index: 0,
		Completed: effects.EmptySteps(),
	}

	return nil
}

func (m *Saga[S]) ExecuteNext(ctx context.Context, effects SagaEffects[S]) error {
	if m.State != SagaStateExecuting {
		return &SagaError{Transition: "execute_next", From: m.State.String()}
	}

	steps := m.ExecutingData.Steps
	index := m.ExecutingData.Index
	completed := m.ExecutingData.Completed

	if index >= effects.Len(steps) {
		m.State = SagaStateCommitted
		m.clearStateData()
		m.CommittedData = &SagaCommittedData[S]{
			Completed: completed,
		}
		return nil
	}
	current := effects.GetStep(steps, index)
	result, __result_err := effects.ExecuteForward(ctx, current)
	if __result_err == nil {
		done := result
		next_completed := effects.PushStep(completed, done)
		m.State = SagaStateExecuting
		m.clearStateData()
		m.ExecutingData = &SagaExecutingData[S]{
			Steps: steps,
			Index: (index + 1),
			Completed: next_completed,
		}
	} else {
		err := __result_err.Error()
		m.State = SagaStateCompensating
		m.clearStateData()
		m.CompensatingData = &SagaCompensatingData[S]{
			Completed: completed,
			Index: (effects.Len(completed) - 1),
			Reason: err,
		}
	}

	return nil
}

func (m *Saga[S]) CompensateNext(ctx context.Context, effects SagaEffects[S]) error {
	if m.State != SagaStateCompensating {
		return &SagaError{Transition: "compensate_next", From: m.State.String()}
	}

	completed := m.CompensatingData.Completed
	index := m.CompensatingData.Index
	reason := m.CompensatingData.Reason

	if index < 0 {
		m.State = SagaStateAborted
		m.clearStateData()
		m.AbortedData = &SagaAbortedData[S]{
			Reason: reason,
			CompensatedCount: effects.Len(completed),
		}
		return nil
	}
	current := effects.GetStep(completed, index)
	_, __result_err := effects.ExecuteCompensate(ctx, current)
	if __result_err == nil {
		m.State = SagaStateCompensating
		m.clearStateData()
		m.CompensatingData = &SagaCompensatingData[S]{
			Completed: completed,
			Index: (index - 1),
			Reason: reason,
		}
	} else {
		err := __result_err.Error()
		m.State = SagaStateAborted
		m.clearStateData()
		m.AbortedData = &SagaAbortedData[S]{
			Reason: err,
			CompensatedCount: (effects.Len(completed) - index),
		}
	}

	return nil
}

func (m *Saga[S]) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func SagaFromJSON[S any](data []byte) (*Saga[S], error) {
	var m Saga[S]
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
