// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SagaState<S> {
    Planning {
        steps: Vec<S>,
    },
    Executing {
        steps: Vec<S>,
        index: i64,
        completed: Vec<S>,
    },
    Compensating {
        completed: Vec<S>,
        index: i64,
        reason: String,
    },
    Committed {
        completed: Vec<S>,
    },
    Aborted {
        reason: String,
        compensated_count: i64,
    },
}

pub trait SagaEffects<S> {
    /// gust:effect -- replay-safe / idempotent
    fn execute_forward(&self, step: &S) -> impl ::core::future::Future<Output = Result<S, String>> + Send;
    /// gust:effect -- replay-safe / idempotent
    fn execute_compensate(&self, step: &S) -> impl ::core::future::Future<Output = Result<i64, String>> + Send;
    /// gust:effect -- replay-safe / idempotent
    fn len(&self, steps: &[S]) -> i64;
    /// gust:effect -- replay-safe / idempotent
    fn get_step(&self, steps: &[S], index: i64) -> S;
    /// gust:effect -- replay-safe / idempotent
    fn push_step(&self, steps: &[S], step: &S) -> Vec<S>;
    /// gust:effect -- replay-safe / idempotent
    fn empty_steps(&self) -> Vec<S>;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Saga<S> {
    pub state: SagaState<S>,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum SagaError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl<S: core::fmt::Debug + Clone> Saga<S> {
    pub fn new(steps: Vec<S>) -> Self {
        Self { state: SagaState::Planning { steps } }
    }

    pub fn state(&self) -> &SagaState<S> {
        &self.state
    }

    pub fn begin(&mut self, effects: &impl SagaEffects<S>) -> Result<(), SagaError> {
        match &self.state {
            SagaState::Planning { steps } => {
                let steps = steps.clone();
                let __goto_executing_index = 0;
                let __goto_executing_completed = effects.empty_steps();
                self.state = SagaState::Executing { steps, index: __goto_executing_index, completed: __goto_executing_completed };
                Ok(())
            }
            _ => Err(SagaError::InvalidTransition {
                transition: "begin".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn execute_next(&mut self, effects: &impl SagaEffects<S>) -> Result<(), SagaError> {
        match &self.state {
            SagaState::Executing { steps, index, completed } => {
                let steps = steps.clone();
                let index = *index;
                let completed = completed.clone();
                if index >= effects.len(&steps) {
                    self.state = SagaState::Committed { completed };
                    return Ok(());
                }
                let current = effects.get_step(&steps, index);
                let result = effects.execute_forward(&current).await;
                match result {
                    Ok(done) => {
                        let next_completed = effects.push_step(&completed, &done);
                        let __goto_executing_index = index + 1;
                        self.state = SagaState::Executing { steps, index: __goto_executing_index, completed: next_completed };
                        Ok(())
                    }
                    Err(err) => {
                        let __goto_compensating_index = effects.len(&completed) - 1;
                        self.state = SagaState::Compensating { completed, index: __goto_compensating_index, reason: err };
                        Ok(())
                    }
                }
            }
            _ => Err(SagaError::InvalidTransition {
                transition: "execute_next".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub async fn compensate_next(&mut self, effects: &impl SagaEffects<S>) -> Result<(), SagaError> {
        match &self.state {
            SagaState::Compensating { completed, index, reason } => {
                let completed = completed.clone();
                let index = *index;
                let reason = reason.clone();
                if index < 0 {
                    let __goto_aborted_compensated_count = effects.len(&completed);
                    self.state = SagaState::Aborted { reason, compensated_count: __goto_aborted_compensated_count };
                    return Ok(());
                }
                let current = effects.get_step(&completed, index);
                let result = effects.execute_compensate(&current).await;
                match result {
                    Ok(_) => {
                        let __goto_compensating_index = index - 1;
                        self.state = SagaState::Compensating { completed, index: __goto_compensating_index, reason };
                        Ok(())
                    }
                    Err(err) => {
                        let __goto_aborted_compensated_count = effects.len(&completed) - index;
                        self.state = SagaState::Aborted { reason: err, compensated_count: __goto_aborted_compensated_count };
                        Ok(())
                    }
                }
            }
            _ => Err(SagaError::InvalidTransition {
                transition: "compensate_next".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
