// Code generated by Gust compiler — DO NOT EDIT.

package supervisor

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type SupervisorMachineState int

const (
	SupervisorMachineStateRunning = iota
	SupervisorMachineStateDegraded
	SupervisorMachineStateShutdown
)

func (s SupervisorMachineState) String() string {
	switch s {
	case SupervisorMachineStateRunning:
		return "Running"
	case SupervisorMachineStateDegraded:
		return "Degraded"
	case SupervisorMachineStateShutdown:
		return "Shutdown"
	default:
		return "Unknown"
	}
}

type SupervisorMachineDegradedData struct {
	FailureCount int64 `json:"failure_count"`
}

type SupervisorMachine struct {
	State SupervisorMachineState
	DegradedData *SupervisorMachineDegradedData
}

func (m *SupervisorMachine) clearStateData() {
	m.DegradedData = nil
}

func (m SupervisorMachine) MarshalJSON() ([]byte, error) {
	envelope := struct {
		State string `json:"state"`
		Data interface{} `json:"data,omitempty"`
	}{State: m.State.String()}
	switch m.State {
	case SupervisorMachineStateRunning:
	case SupervisorMachineStateDegraded:
		if m.DegradedData != nil {
			envelope.Data = m.DegradedData
		}
	case SupervisorMachineStateShutdown:
	default:
		return nil, fmt.Errorf("SupervisorMachine: cannot marshal unknown state %d", int(m.State))
	}
	return json.Marshal(envelope)
}

func (m *SupervisorMachine) UnmarshalJSON(b []byte) error {
	var envelope struct {
		State string `json:"state"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(b, &envelope); err != nil {
		return err
	}
	switch envelope.State {
	case "Running":
		m.clearStateData()
		m.State = SupervisorMachineStateRunning
	case "Degraded":
		if len(envelope.Data) == 0 {
			return fmt.Errorf("SupervisorMachine: state 'Degraded' requires a data payload")
		}
		var present map[string]json.RawMessage
		if err := json.Unmarshal(envelope.Data, &present); err != nil {
			return err
		}
		for _, field := range []string{"failure_count"} {
			if _, ok := present[field]; !ok {
				return fmt.Errorf("SupervisorMachine: state 'Degraded' is missing required field %q", field)
			}
		}
		data := &SupervisorMachineDegradedData{}
		if err := json.Unmarshal(envelope.Data, data); err != nil {
			return err
		}
		m.clearStateData()
		m.State = SupervisorMachineStateDegraded
		m.DegradedData = data
	case "Shutdown":
		m.clearStateData()
		m.State = SupervisorMachineStateShutdown
	default:
		return fmt.Errorf("SupervisorMachine: unknown state %q", envelope.State)
	}
	return nil
}

func NewSupervisorMachine() *SupervisorMachine {
	return &SupervisorMachine{
		State: SupervisorMachineStateRunning,
	}
}

type SupervisorMachineError struct {
	Transition string
	From      string
	Message   string
}

func (e *SupervisorMachineError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *SupervisorMachine) ReportFailure(count int64) error {
	if m.State != SupervisorMachineStateRunning {
		return &SupervisorMachineError{Transition: "report_failure", From: m.State.String()}
	}

	m.State = SupervisorMachineStateDegraded
	m.clearStateData()
	m.DegradedData = &SupervisorMachineDegradedData{
		FailureCount: count,
	}

	return nil
}

func (m *SupervisorMachine) Recover() error {
	if m.State != SupervisorMachineStateDegraded {
		return &SupervisorMachineError{Transition: "recover", From: m.State.String()}
	}

	m.State = SupervisorMachineStateRunning
	m.clearStateData()

	return nil
}

func (m *SupervisorMachine) Shutdown() error {
	if m.State != SupervisorMachineStateDegraded {
		return &SupervisorMachineError{Transition: "shutdown", From: m.State.String()}
	}

	m.State = SupervisorMachineStateShutdown
	m.clearStateData()

	return nil
}

func (m *SupervisorMachine) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func SupervisorMachineFromJSON(data []byte) (*SupervisorMachine, error) {
	var m SupervisorMachine
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}
