// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    pub source: String,
    pub payload: String,
    pub priority: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessedResult {
    pub event_id: String,
    pub output: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventProcessorState {
    Idle,
    Receiving {
        event: Event,
    },
    Validating {
        event: Event,
    },
    Completed {
        result: ProcessedResult,
    },
    Failed {
        reason: String,
    },
}

pub trait EventProcessorEffects {
    fn validate_event(&self, event: &Event) -> String;
    fn process_event(&self, event: &Event) -> ProcessedResult;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventProcessor {
    pub state: EventProcessorState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum EventProcessorError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl EventProcessor {
    pub fn new() -> Self {
        Self { state: EventProcessorState::Idle }
    }

    pub fn state(&self) -> &EventProcessorState {
        &self.state
    }

    pub fn receive(&mut self, incoming: Event) -> Result<(), EventProcessorError> {
        match self.state.clone() {
            EventProcessorState::Idle => {
                self.state = EventProcessorState::Receiving { event: incoming };
                Ok(())
            }
            _ => Err(EventProcessorError::InvalidTransition {
                transition: "receive".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn validate(&mut self, effects: &impl EventProcessorEffects) -> Result<(), EventProcessorError> {
        match self.state.clone() {
            EventProcessorState::Receiving { event } => {
                let validation_result = effects.validate_event(&event);
                if event.priority > 0 {
                    self.state = EventProcessorState::Validating { event: event };
                } else {
                    self.state = EventProcessorState::Failed { reason: "event priority must be positive".to_string() };
                }
                Ok(())
            }
            _ => Err(EventProcessorError::InvalidTransition {
                transition: "validate".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn process(&mut self, effects: &impl EventProcessorEffects) -> Result<(), EventProcessorError> {
        match self.state.clone() {
            EventProcessorState::Validating { event } => {
                let result = effects.process_event(&event);
                self.state = EventProcessorState::Completed { result: result };
                Ok(())
            }
            _ => Err(EventProcessorError::InvalidTransition {
                transition: "process".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn reset(&mut self) -> Result<(), EventProcessorError> {
        match self.state.clone() {
            EventProcessorState::Completed { result } => {
                self.state = EventProcessorState::Idle;
                Ok(())
            }
            _ => Err(EventProcessorError::InvalidTransition {
                transition: "reset".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn retry(&mut self) -> Result<(), EventProcessorError> {
        match self.state.clone() {
            EventProcessorState::Failed { reason } => {
                self.state = EventProcessorState::Idle;
                Ok(())
            }
            _ => Err(EventProcessorError::InvalidTransition {
                transition: "retry".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

