// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub id: String,
    pub items: String,
    pub quantity: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Money {
    pub amount: i64,
    pub currency: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Receipt {
    pub transaction_id: String,
    pub amount: Money,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OrderMachineState {
    Pending {
        order: Order,
    },
    Validated {
        order: Order,
        total: Money,
    },
    Charged {
        order: Order,
        receipt: Receipt,
    },
    Shipped {
        order: Order,
        tracking: String,
    },
    Failed {
        reason: String,
    },
}

pub trait OrderMachineEffects {
    fn calculate_total(&self, order: &Order) -> Money;
    fn process_payment(&self, total: &Money) -> Receipt;
    fn create_shipment(&self, order: &Order) -> String;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderMachine {
    pub state: OrderMachineState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderMachineError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl OrderMachine {
    pub fn new(order: Order) -> Self {
        Self { state: OrderMachineState::Pending { order } }
    }

    pub fn state(&self) -> &OrderMachineState {
        &self.state
    }

    pub fn validate(&mut self, effects: &impl OrderMachineEffects) -> Result<(), OrderMachineError> {
        match self.state.clone() {
            OrderMachineState::Pending { order } => {
                let total = effects.calculate_total(&order);
                if total.amount > 0 {
                    self.state = OrderMachineState::Validated { order: order, total: total };
                } else {
                    self.state = OrderMachineState::Failed { reason: "invalid order total".to_string() };
                }
                Ok(())
            }
            _ => Err(OrderMachineError::InvalidTransition {
                transition: "validate".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn charge(&mut self, effects: &impl OrderMachineEffects) -> Result<(), OrderMachineError> {
        match self.state.clone() {
            OrderMachineState::Validated { order, total } => {
                let receipt = effects.process_payment(&total);
                self.state = OrderMachineState::Charged { order: order, receipt: receipt };
                Ok(())
            }
            _ => Err(OrderMachineError::InvalidTransition {
                transition: "charge".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn ship(&mut self, effects: &impl OrderMachineEffects) -> Result<(), OrderMachineError> {
        match self.state.clone() {
            OrderMachineState::Charged { order, receipt: _receipt } => {
                let tracking = effects.create_shipment(&order);
                self.state = OrderMachineState::Shipped { order: order, tracking: tracking };
                Ok(())
            }
            _ => Err(OrderMachineError::InvalidTransition {
                transition: "ship".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn fail(&mut self) -> Result<(), OrderMachineError> {
        match self.state.clone() {
            OrderMachineState::Pending { order: _order } => {
                self.state = OrderMachineState::Failed { reason: "payment declined".to_string() };
                Ok(())
            }
            _ => Err(OrderMachineError::InvalidTransition {
                transition: "fail".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

