// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SupervisorMachineState {
    Running,
    Degraded {
        failure_count: i64,
    },
    Shutdown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupervisorMachine {
    pub state: SupervisorMachineState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum SupervisorMachineError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl SupervisorMachine {
    pub fn new() -> Self {
        Self { state: SupervisorMachineState::Running }
    }

    pub fn state(&self) -> &SupervisorMachineState {
        &self.state
    }

    pub fn report_failure(&mut self, count: i64) -> Result<(), SupervisorMachineError> {
        match self.state.clone() {
            SupervisorMachineState::Running => {
                self.state = SupervisorMachineState::Degraded { failure_count: count };
                Ok(())
            }
            _ => Err(SupervisorMachineError::InvalidTransition {
                transition: "report_failure".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn recover(&mut self) -> Result<(), SupervisorMachineError> {
        match self.state.clone() {
            SupervisorMachineState::Degraded { failure_count: _failure_count } => {
                self.state = SupervisorMachineState::Running;
                Ok(())
            }
            _ => Err(SupervisorMachineError::InvalidTransition {
                transition: "recover".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn shutdown(&mut self) -> Result<(), SupervisorMachineError> {
        match self.state.clone() {
            SupervisorMachineState::Degraded { failure_count: _failure_count } => {
                self.state = SupervisorMachineState::Shutdown;
                Ok(())
            }
            _ => Err(SupervisorMachineError::InvalidTransition {
                transition: "shutdown".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

