// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EngineFailure {
    UserError(String),
    SystemError(String, i64),
    IntegrationError(String, i64, String),
    Timeout(i64),
    Cancelled(String),
}

