// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowConfig {
    pub name: String,
    pub total_steps: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StepRunnerState {
    Idle,
    Running {
        step: String,
    },
    Done {
        result: String,
    },
}

pub trait StepRunnerEffects {
    fn run_step(&self, step: &str) -> String;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepRunner {
    pub state: StepRunnerState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum StepRunnerError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl StepRunner {
    pub fn new() -> Self {
        Self { state: StepRunnerState::Idle }
    }

    pub fn state(&self) -> &StepRunnerState {
        &self.state
    }

    pub fn start(&mut self, step: String) -> Result<(), StepRunnerError> {
        match self.state.clone() {
            StepRunnerState::Idle => {
                self.state = StepRunnerState::Running { step: step };
                Ok(())
            }
            _ => Err(StepRunnerError::InvalidTransition {
                transition: "start".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn complete(&mut self, effects: &impl StepRunnerEffects) -> Result<(), StepRunnerError> {
        match self.state.clone() {
            StepRunnerState::Running { step } => {
                let result = effects.run_step(&step);
                self.state = StepRunnerState::Done { result: result };
                Ok(())
            }
            _ => Err(StepRunnerError::InvalidTransition {
                transition: "complete".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorkflowEngineState {
    Created {
        config: WorkflowConfig,
    },
    Running {
        current_step: String,
        remaining: i64,
    },
    AwaitingApproval {
        current_step: String,
        remaining: i64,
    },
    Completed {
        total_steps: i64,
    },
    Failed {
        step_name: String,
        failure: EngineFailure,
    },
}

pub trait WorkflowEngineEffects {
    fn execute_step(&self, step_name: &str) -> String;
    fn needs_approval(&self, step_name: &str) -> bool;
    fn next_step_name(&self, current_step: &str) -> String;
    fn produce_failure(&self, reason: &str) -> EngineFailure;
    /// action — not replay-safe / externally visible (#40).
    fn notify_rejection(&self, step_name: &str, reason: &str) -> String;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowEngine {
    pub state: WorkflowEngineState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum WorkflowEngineError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl WorkflowEngine {
    pub fn new(config: WorkflowConfig) -> Self {
        Self { state: WorkflowEngineState::Created { config } }
    }

    pub fn state(&self) -> &WorkflowEngineState {
        &self.state
    }

    pub fn start(&mut self, first_step: String) -> Result<(), WorkflowEngineError> {
        match self.state.clone() {
            WorkflowEngineState::Created { config } => {
                self.state = WorkflowEngineState::Running { current_step: first_step, remaining: config.total_steps };
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "start".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn advance(&mut self, effects: &impl WorkflowEngineEffects) -> Result<(), WorkflowEngineError> {
        match self.state.clone() {
            WorkflowEngineState::Running { current_step, remaining } => {
                let output = effects.execute_step(&current_step);
                let next_remaining = (remaining - 1);
                if next_remaining > 0 {
                    let next_step = effects.next_step_name(&current_step);
                    let approval_needed = effects.needs_approval(&next_step);
                    if approval_needed {
                        self.state = WorkflowEngineState::AwaitingApproval { current_step: next_step, remaining: next_remaining };
                    } else {
                        self.state = WorkflowEngineState::Running { current_step: next_step, remaining: next_remaining };
                    }
                } else {
                    self.state = WorkflowEngineState::Completed { total_steps: remaining };
                }
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "advance".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn approve(&mut self, next_step: String) -> Result<(), WorkflowEngineError> {
        match self.state.clone() {
            WorkflowEngineState::AwaitingApproval { current_step: _current_step, remaining } => {
                if remaining > 1 {
                    self.state = WorkflowEngineState::Running { current_step: next_step, remaining: (remaining - 1) };
                } else {
                    self.state = WorkflowEngineState::Completed { total_steps: remaining };
                }
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "approve".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn reject(&mut self, reason: String, effects: &impl WorkflowEngineEffects) -> Result<(), WorkflowEngineError> {
        match self.state.clone() {
            WorkflowEngineState::AwaitingApproval { current_step, remaining: _remaining } => {
                let failure = effects.produce_failure(&reason);
                let _notif = effects.notify_rejection(&current_step, &reason);
                self.state = WorkflowEngineState::Failed { step_name: current_step, failure: failure };
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "reject".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

