// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowConfig {
    pub name: String,
    pub total_steps: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StepRunnerState {
    Idle,
    Running {
        step: String,
    },
    Done {
        result: String,
    },
}

pub trait StepRunnerEffects {
    /// gust:effect -- replay-safe / idempotent
    fn run_step(&self, step: &str) -> String;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepRunner {
    pub state: StepRunnerState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum StepRunnerError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl StepRunner {
    pub fn new() -> Self {
        Self { state: StepRunnerState::Idle }
    }

    pub fn state(&self) -> &StepRunnerState {
        &self.state
    }

    pub fn start(&mut self, step: String) -> Result<(), StepRunnerError> {
        match &self.state {
            StepRunnerState::Idle => {
                self.state = StepRunnerState::Running { step };
                Ok(())
            }
            _ => Err(StepRunnerError::InvalidTransition {
                transition: "start".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn complete(&mut self, effects: &impl StepRunnerEffects) -> Result<(), StepRunnerError> {
        match &self.state {
            StepRunnerState::Running { step } => {
                let step = step.clone();
                let result = effects.run_step(&step);
                self.state = StepRunnerState::Done { result };
                Ok(())
            }
            _ => Err(StepRunnerError::InvalidTransition {
                transition: "complete".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

impl Default for StepRunner {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorkflowEngineState {
    Created {
        config: WorkflowConfig,
    },
    Running {
        current_step: String,
        remaining: i64,
    },
    AwaitingApproval {
        current_step: String,
        remaining: i64,
    },
    Completed {
        total_steps: i64,
    },
    Failed {
        step_name: String,
        failure: EngineFailure,
    },
}

pub trait WorkflowEngineEffects {
    /// gust:effect -- replay-safe / idempotent
    fn execute_step(&self, step_name: &str) -> String;
    /// gust:effect -- replay-safe / idempotent
    fn needs_approval(&self, step_name: &str) -> bool;
    /// gust:effect -- replay-safe / idempotent
    fn next_step_name(&self, current_step: &str) -> String;
    /// gust:effect -- replay-safe / idempotent
    fn produce_failure(&self, reason: &str) -> EngineFailure;
    /// gust:action -- not replay-safe / externally visible
    fn notify_rejection(&self, step_name: &str, reason: &str) -> String;
}

/// Host-supplied runners for the children `WorkflowEngine` supervises.
pub trait WorkflowEngineSupervision {
    /// Drives a supervised `StepRunner` to completion. Returning `Err`
    /// marks the child failed, which is what the runtime's
    /// restart strategy acts on.
    fn run_step_runner(&self, child: StepRunner) -> ::core::pin::Pin<::std::boxed::Box<dyn ::core::future::Future<Output = Result<(), String>> + Send>>;
}

/// Restart policy per supervised child of `WorkflowEngine`.
pub const WORKFLOW_ENGINE_SUPERVISION: &[(&str, gust_runtime::prelude::RestartStrategy)] = &[
    ("StepRunner", gust_runtime::prelude::RestartStrategy::OneForOne),
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowEngine {
    pub state: WorkflowEngineState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum WorkflowEngineError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl WorkflowEngine {
    pub fn new(config: WorkflowConfig) -> Self {
        Self { state: WorkflowEngineState::Created { config } }
    }

    pub fn state(&self) -> &WorkflowEngineState {
        &self.state
    }

    pub fn start(&mut self, first_step: String) -> Result<(), WorkflowEngineError> {
        match &self.state {
            WorkflowEngineState::Created { config } => {
                let config = config.clone();
                let __goto_running_remaining = config.total_steps;
                self.state = WorkflowEngineState::Running { current_step: first_step, remaining: __goto_running_remaining };
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "start".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn advance(&mut self, effects: &impl WorkflowEngineEffects) -> Result<(), WorkflowEngineError> {
        match &self.state {
            WorkflowEngineState::Running { current_step, remaining } => {
                let current_step = current_step.clone();
                let remaining = *remaining;
                effects.execute_step(&current_step);
                let next_remaining = remaining - 1;
                if next_remaining > 0 {
                    let next_step = effects.next_step_name(&current_step);
                    let approval_needed = effects.needs_approval(&next_step);
                    if approval_needed {
                        self.state = WorkflowEngineState::AwaitingApproval { current_step: next_step, remaining: next_remaining };
                        Ok(())
                    } else {
                        self.state = WorkflowEngineState::Running { current_step: next_step, remaining: next_remaining };
                        Ok(())
                    }
                } else {
                    self.state = WorkflowEngineState::Completed { total_steps: remaining };
                    Ok(())
                }
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "advance".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn approve(&mut self, next_step: String) -> Result<(), WorkflowEngineError> {
        match &self.state {
            WorkflowEngineState::AwaitingApproval { current_step: _current_step, remaining } => {
                let remaining = *remaining;
                if remaining > 1 {
                    let __goto_running_remaining = remaining - 1;
                    self.state = WorkflowEngineState::Running { current_step: next_step, remaining: __goto_running_remaining };
                    Ok(())
                } else {
                    self.state = WorkflowEngineState::Completed { total_steps: remaining };
                    Ok(())
                }
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "approve".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn reject(&mut self, reason: String, effects: &impl WorkflowEngineEffects) -> Result<(), WorkflowEngineError> {
        match &self.state {
            WorkflowEngineState::AwaitingApproval { current_step, remaining: _remaining } => {
                let current_step = current_step.clone();
                let failure = effects.produce_failure(&reason);
                effects.notify_rejection(&current_step, &reason);
                self.state = WorkflowEngineState::Failed { step_name: current_step, failure };
                Ok(())
            }
            _ => Err(WorkflowEngineError::InvalidTransition {
                transition: "reject".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}
