// Code generated by Gust compiler — DO NOT EDIT.

package orders

import (
	"encoding/json"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf

type Order struct {
	Id string `json:"id"`
	Customer string `json:"customer"`
	Items []string `json:"items"`
}

type Money struct {
	Cents int64 `json:"cents"`
	Currency string `json:"currency"`
}

type Receipt struct {
	TransactionId string `json:"transaction_id"`
	Amount Money `json:"amount"`
}

type OrderProcessorState int

const (
	OrderProcessorStatePending OrderProcessorState = iota
	OrderProcessorStateValidated
	OrderProcessorStateCharged
	OrderProcessorStateShipped
	OrderProcessorStateFailed
)

func (s OrderProcessorState) String() string {
	switch s {
	case OrderProcessorStatePending:
		return "Pending"
	case OrderProcessorStateValidated:
		return "Validated"
	case OrderProcessorStateCharged:
		return "Charged"
	case OrderProcessorStateShipped:
		return "Shipped"
	case OrderProcessorStateFailed:
		return "Failed"
	default:
		return "Unknown"
	}
}

type OrderProcessorPendingData struct {
	Order Order `json:"order"`
}

type OrderProcessorValidatedData struct {
	Order Order `json:"order"`
	Total Money `json:"total"`
}

type OrderProcessorChargedData struct {
	Order Order `json:"order"`
	Payment Receipt `json:"payment"`
}

type OrderProcessorShippedData struct {
	Order Order `json:"order"`
	Tracking string `json:"tracking"`
}

type OrderProcessorFailedData struct {
	Reason string `json:"reason"`
}

type OrderProcessorEffects interface {
	CalculateTotal(order Order) Money
	ProcessPayment(total Money) Receipt
	CreateShipment(order Order) string
}

type OrderProcessor struct {
	State OrderProcessorState `json:"state"`
	PendingData *OrderProcessorPendingData `json:"pending_data,omitempty"`
	ValidatedData *OrderProcessorValidatedData `json:"validated_data,omitempty"`
	ChargedData *OrderProcessorChargedData `json:"charged_data,omitempty"`
	ShippedData *OrderProcessorShippedData `json:"shipped_data,omitempty"`
	FailedData *OrderProcessorFailedData `json:"failed_data,omitempty"`
}

func NewOrderProcessor(order Order) *OrderProcessor {
	return &OrderProcessor{
		State: OrderProcessorStatePending,
		PendingData: &OrderProcessorPendingData{
			Order: order,
		},
	}
}

type OrderProcessorError struct {
	Transition string
	From      string
	Message   string
}

func (e *OrderProcessorError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *OrderProcessor) Validate(ctx ValidationCtx, effects OrderProcessorEffects) error {
	if m.State != OrderProcessorStatePending {
		return &OrderProcessorError{Transition: "validate", From: m.State.String()}
	}

	total := effects.CalculateTotal(ctx.Order)
	if total.Cents > 0 {
		m.State = OrderProcessorStateValidated
		m.PendingData = nil
		m.ValidatedData = nil
		m.ChargedData = nil
		m.ShippedData = nil
		m.FailedData = nil
		m.ValidatedData = &OrderProcessorValidatedData{
			Order: ctx.Order,
			Total: total,
		}
	} else {
		m.State = OrderProcessorStateFailed
		m.PendingData = nil
		m.ValidatedData = nil
		m.ChargedData = nil
		m.ShippedData = nil
		m.FailedData = nil
		m.FailedData = &OrderProcessorFailedData{
			Reason: "invalid order total",
		}
	}

	return nil
}

func (m *OrderProcessor) Charge(ctx PaymentCtx, effects OrderProcessorEffects) error {
	if m.State != OrderProcessorStateValidated {
		return &OrderProcessorError{Transition: "charge", From: m.State.String()}
	}

	receipt := effects.ProcessPayment(ctx.Total)
	m.State = OrderProcessorStateCharged
	m.PendingData = nil
	m.ValidatedData = nil
	m.ChargedData = nil
	m.ShippedData = nil
	m.FailedData = nil
	m.ChargedData = &OrderProcessorChargedData{
		Order: ctx.Order,
		Payment: receipt,
	}

	return nil
}

func (m *OrderProcessor) Ship(ctx ShippingCtx, effects OrderProcessorEffects) error {
	if m.State != OrderProcessorStateCharged {
		return &OrderProcessorError{Transition: "ship", From: m.State.String()}
	}

	tracking := effects.CreateShipment(ctx.Order)
	m.State = OrderProcessorStateShipped
	m.PendingData = nil
	m.ValidatedData = nil
	m.ChargedData = nil
	m.ShippedData = nil
	m.FailedData = nil
	m.ShippedData = &OrderProcessorShippedData{
		Order: ctx.Order,
		Tracking: tracking,
	}

	return nil
}

func (m *OrderProcessor) Retry(ctx RetryCtx) error {
	if m.State != OrderProcessorStateFailed {
		return &OrderProcessorError{Transition: "retry", From: m.State.String()}
	}

	m.State = OrderProcessorStatePending
	m.PendingData = nil
	m.ValidatedData = nil
	m.ChargedData = nil
	m.ShippedData = nil
	m.FailedData = nil
	m.PendingData = &OrderProcessorPendingData{
		Order: ctx.OriginalOrder,
	}

	return nil
}

func (m *OrderProcessor) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func OrderProcessorFromJSON(data []byte) (*OrderProcessor, error) {
	var m OrderProcessor
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

type OrderSupervisorState int

const (
	OrderSupervisorStateWatching OrderSupervisorState = iota
	OrderSupervisorStateDegraded
	OrderSupervisorStateShutdown
)

func (s OrderSupervisorState) String() string {
	switch s {
	case OrderSupervisorStateWatching:
		return "Watching"
	case OrderSupervisorStateDegraded:
		return "Degraded"
	case OrderSupervisorStateShutdown:
		return "Shutdown"
	default:
		return "Unknown"
	}
}

type OrderSupervisorWatchingData struct {
	ActiveOrders int64 `json:"active_orders"`
}

type OrderSupervisorDegradedData struct {
	FailedCount int64 `json:"failed_count"`
}

type OrderSupervisor struct {
	State OrderSupervisorState `json:"state"`
	WatchingData *OrderSupervisorWatchingData `json:"watching_data,omitempty"`
	DegradedData *OrderSupervisorDegradedData `json:"degraded_data,omitempty"`
}

func NewOrderSupervisor(active_orders int64) *OrderSupervisor {
	return &OrderSupervisor{
		State: OrderSupervisorStateWatching,
		WatchingData: &OrderSupervisorWatchingData{
			ActiveOrders: active_orders,
		},
	}
}

type OrderSupervisorError struct {
	Transition string
	From      string
	Message   string
}

func (e *OrderSupervisorError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("transition '%s' failed: %s", e.Transition, e.Message)
	}
	return fmt.Sprintf("invalid transition '%s' from state '%s'", e.Transition, e.From)
}

func (m *OrderSupervisor) OrderFailed() error {
	if m.State != OrderSupervisorStateWatching {
		return &OrderSupervisorError{Transition: "order_failed", From: m.State.String()}
	}

	m.State = OrderSupervisorStateWatching
	m.WatchingData = nil
	m.DegradedData = nil
	m.WatchingData = &OrderSupervisorWatchingData{
		ActiveOrders: 0 /* TODO: missing arg */,
	}

	return nil
}

func (m *OrderSupervisor) Recover() error {
	if m.State != OrderSupervisorStateDegraded {
		return &OrderSupervisorError{Transition: "recover", From: m.State.String()}
	}

	m.State = OrderSupervisorStateWatching
	m.WatchingData = nil
	m.DegradedData = nil
	m.WatchingData = &OrderSupervisorWatchingData{
		ActiveOrders: 0 /* TODO: missing arg */,
	}

	return nil
}

func (m *OrderSupervisor) Kill() error {
	if m.State != OrderSupervisorStateDegraded {
		return &OrderSupervisorError{Transition: "kill", From: m.State.String()}
	}

	m.State = OrderSupervisorStateShutdown
	m.WatchingData = nil
	m.DegradedData = nil

	return nil
}

func (m *OrderSupervisor) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

func OrderSupervisorFromJSON(data []byte) (*OrderSupervisor, error) {
	var m OrderSupervisor
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

