// Generated by Gust compiler — do not edit manually
use serde::{Serialize, Deserialize};
use gust_runtime::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub id: String,
    pub customer: String,
    pub items: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Money {
    pub cents: i64,
    pub currency: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Receipt {
    pub transaction_id: String,
    pub amount: Money,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OrderProcessorState {
    Pending {
        order: Order,
    },
    Validated {
        order: Order,
        total: Money,
    },
    Charged {
        order: Order,
        payment: Receipt,
    },
    Shipped {
        order: Order,
        tracking: String,
    },
    Failed {
        reason: String,
    },
}

pub trait OrderProcessorEffects {
    /// gust:effect -- replay-safe / idempotent
    fn calculate_total(&self, order: &Order) -> Money;
    /// gust:effect -- replay-safe / idempotent
    fn process_payment(&self, total: &Money) -> Receipt;
    /// gust:effect -- replay-safe / idempotent
    fn create_shipment(&self, order: &Order) -> String;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderProcessor {
    pub state: OrderProcessorState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderProcessorError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl OrderProcessor {
    pub fn new(order: Order) -> Self {
        Self { state: OrderProcessorState::Pending { order } }
    }

    pub fn state(&self) -> &OrderProcessorState {
        &self.state
    }

    pub fn validate(&mut self, effects: &impl OrderProcessorEffects) -> Result<(), OrderProcessorError> {
        match self.state.clone() {
            OrderProcessorState::Pending { order } => {
                let total = effects.calculate_total(&order);
                if total.cents > 0 {
                    self.state = OrderProcessorState::Validated { order: order, total: total };
                } else {
                    self.state = OrderProcessorState::Failed { reason: "invalid order total".to_string() };
                }
                Ok(())
            }
            _ => Err(OrderProcessorError::InvalidTransition {
                transition: "validate".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn charge(&mut self, effects: &impl OrderProcessorEffects) -> Result<(), OrderProcessorError> {
        match self.state.clone() {
            OrderProcessorState::Validated { order, total } => {
                let receipt = effects.process_payment(&total);
                self.state = OrderProcessorState::Charged { order: order, payment: receipt };
                Ok(())
            }
            _ => Err(OrderProcessorError::InvalidTransition {
                transition: "charge".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn ship(&mut self, effects: &impl OrderProcessorEffects) -> Result<(), OrderProcessorError> {
        match self.state.clone() {
            OrderProcessorState::Charged { order, payment: _payment } => {
                let tracking = effects.create_shipment(&order);
                self.state = OrderProcessorState::Shipped { order: order, tracking: tracking };
                Ok(())
            }
            _ => Err(OrderProcessorError::InvalidTransition {
                transition: "ship".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn retry(&mut self, original_order: Order) -> Result<(), OrderProcessorError> {
        match self.state.clone() {
            OrderProcessorState::Failed { reason: _reason } => {
                self.state = OrderProcessorState::Pending { order: original_order };
                Ok(())
            }
            _ => Err(OrderProcessorError::InvalidTransition {
                transition: "retry".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OrderSupervisorState {
    Watching {
        active_orders: i64,
    },
    Degraded {
        failed_count: i64,
    },
    Shutdown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderSupervisor {
    pub state: OrderSupervisorState,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderSupervisorError {
    #[error("invalid transition '{transition}' from state '{from}'")]
    InvalidTransition { transition: String, from: String },
    #[error("transition failed: {reason}")]
    Failed { reason: String },
}

impl OrderSupervisor {
    pub fn new(active_orders: i64) -> Self {
        Self { state: OrderSupervisorState::Watching { active_orders } }
    }

    pub fn state(&self) -> &OrderSupervisorState {
        &self.state
    }

    pub fn order_failed(&mut self) -> Result<(), OrderSupervisorError> {
        match self.state.clone() {
            OrderSupervisorState::Watching { active_orders: _active_orders } => {
                // Cannot auto-transition to Watching - requires fields
                Ok(())
            }
            _ => Err(OrderSupervisorError::InvalidTransition {
                transition: "order_failed".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn recover(&mut self) -> Result<(), OrderSupervisorError> {
        match self.state.clone() {
            OrderSupervisorState::Degraded { failed_count: _failed_count } => {
                // Cannot auto-transition to Watching - requires fields
                Ok(())
            }
            _ => Err(OrderSupervisorError::InvalidTransition {
                transition: "recover".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

    pub fn kill(&mut self) -> Result<(), OrderSupervisorError> {
        match self.state.clone() {
            OrderSupervisorState::Degraded { failed_count: _failed_count } => {
                self.state = OrderSupervisorState::Shutdown;
                Ok(())
            }
            _ => Err(OrderSupervisorError::InvalidTransition {
                transition: "kill".to_string(),
                from: format!("{:?}", self.state),
            }),
        }
    }

}

